const the80sMusicData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "MICHAEL JACKSON", u: "../images/80s-music/michael-jackson.jpg" },
    { n: "MADONNA", u: "../images/80s-music/madonna.jpg" },
    { n: "PRINCE", u: "../images/80s-music/prince.jpg" },
    { n: "WHITNEY HOUSTON", u: "../images/80s-music/whitney-houston.jpg" },
    { n: "BRUCE SPRINGSTEEN", u: "../images/80s-music/bruce-springsteen.jpg" },
    { n: "QUEEN", u: "../images/80s-music/queen.jpg" },
    { n: "DAVID BOWIE", u: "../images/80s-music/david-bowie.jpg" },
    { n: "TINA TURNER", u: "../images/80s-music/tina-turner.jpg" },
    { n: "CYNDI LAUPER", u: "../images/80s-music/cyndi-lauper.jpg" },
    { n: "BON JOVI", u: "../images/80s-music/bon-jovi.jpg" },
    { n: "GUNS N' ROSES", u: "../images/80s-music/guns-n-roses.jpg" },
    { n: "U2", u: "../images/80s-music/u2.jpg" },
    { n: "AC/DC", u: "../images/80s-music/ac-dc.jpg" },
    { n: "AEROSMITH", u: "../images/80s-music/aerosmith.jpg" },
    { n: "THE POLICE", u: "../images/80s-music/the-police.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "GEORGE MICHAEL", u: "../images/80s-music/george-michael.jpg" },
    { n: "ELTON JOHN", u: "../images/80s-music/elton-john.jpg" },
    { n: "BILLY JOEL", u: "../images/80s-music/billy-joel.jpg" },
    { n: "PHIL COLLINS", u: "../images/80s-music/phil-collins.jpg" },
    { n: "HALL & OATES", u: "../images/80s-music/hall-oates.jpg" },
    { n: "DEF LEPPARD", u: "../images/80s-music/def-leppard.jpg" },
    { n: "JOURNEY", u: "../images/80s-music/journey.jpg" },
    { n: "METALLICA", u: "../images/80s-music/metallica.jpg" },
    { n: "IRON MAIDEN", u: "../images/80s-music/iron-maiden.jpg" },
    { n: "MÖTLEY CRÜE", u: "../images/80s-music/motley-crue.jpg" },
    { n: "VAN HALEN", u: "../images/80s-music/van-halen.jpg" },
    { n: "POISON", u: "../images/80s-music/poison.jpg" },
    { n: "THE ROLLING STONES", u: "../images/80s-music/rolling-stones.jpg" },
    { n: "PINK FLOYD", u: "../images/80s-music/pink-floyd.jpg" },
    { n: "THE CLASH", u: "../images/80s-music/the-clash.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "THE CURE", u: "../images/80s-music/the-cure.jpg" },
    { n: "THE SMITHS", u: "../images/80s-music/the-smiths.jpg" },
    { n: "DEPECHE MODE", u: "../images/80s-music/depeche-mode.jpg" },
    { n: "NEW ORDER", u: "../images/80s-music/new-order.jpg" },
    { n: "DURAN DURAN", u: "../images/80s-music/duran-duran.jpg" },
    { n: "CULTURE CLUB", u: "../images/80s-music/culture-club.jpg" },
    { n: "EURYTHMICS", u: "../images/80s-music/eurythmics.jpg" },
    { n: "TEARS FOR FEARS", u: "../images/80s-music/tears-for-fears.jpg" },
    { n: "A-HA", u: "../images/80s-music/a-ha.jpg" },
    { n: "WHAM!", u: "../images/80s-music/wham.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "THE BANGLES", u: "../images/80s-music/the-bangles.jpg" },
    { n: "THE GO-GO'S", u: "../images/80s-music/the-go-gos.jpg" },
    { n: "BLONDIE", u: "../images/80s-music/blondie.jpg" },
    { n: "PRETENDERS", u: "../images/80s-music/pretenders.jpg" },
    { n: "FLEETWOOD MAC", u: "../images/80s-music/fleetwood-mac.jpg" },
    { n: "TOM PETTY", u: "../images/80s-music/tom-petty.jpg" },
    { n: "JOHN MELLENCAMP", u: "../images/80s-music/john-mellencamp.jpg" },
    { n: "BRYAN ADAMS", u: "../images/80s-music/bryan-adams.jpg" },
    { n: "RICHARD MARX", u: "../images/80s-music/richard-marx.jpg" },
    { n: "RICK ASTLEY", u: "../images/80s-music/rick-astley.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "KENNY LOGGINS", u: "../images/80s-music/kenny-loggins.jpg" },
    { n: "HUEY LEWIS AND THE NEWS", u: "../images/80s-music/huey-lewis.jpg" },
    { n: "MEN AT WORK", u: "../images/80s-music/men-at-work.jpg" },
    { n: "THE CARS", u: "../images/80s-music/the-cars.jpg" },
    { n: "CHEAP TRICK", u: "../images/80s-music/cheap-trick.jpg" },
    { n: "REO SPEEDWAGON", u: "../images/80s-music/reo-speedwagon.jpg" },
    { n: "STYX", u: "../images/80s-music/styx.jpg" },
    { n: "FOREIGNER", u: "../images/80s-music/foreigner.jpg" },
    { n: "TOTO", u: "../images/80s-music/toto.jpg" },
    { n: "THE B-52'S", u: "../images/80s-music/the-b-52s.jpg" },
];
if (typeof window !== 'undefined') window.the80sMusicData = the80sMusicData;
