const the90sAlbumsData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "NEVERMIND", u: "../images/90s-albums/nevermind.jpg" },
    { n: "...BABY ONE MORE TIME", u: "../images/90s-albums/baby-one-more-time.jpg" },
    { n: "SPICE", u: "../images/90s-albums/spice.jpg" },
    { n: "THE BLACK ALBUM", u: "../images/90s-albums/the-black-album.jpg" },
    { n: "THE SLIM SHADY LP", u: "../images/90s-albums/the-slim-shady-lp.jpg" },
    { n: "DOOKIE", u: "../images/90s-albums/dookie.jpg" },
    { n: "OK COMPUTER", u: "../images/90s-albums/ok-computer.jpg" },
    { n: "MILLENNIUM", u: "../images/90s-albums/millennium.jpg" },
    { n: "COME ON OVER", u: "../images/90s-albums/come-on-over.jpg" },
    { n: "JAGGED LITTLE PILL", u: "../images/90s-albums/jagged-little-pill.jpg" },
    { n: "CRAZYSEXYCOOL", u: "../images/90s-albums/crazysexycool.jpg" },
    { n: "THE MISEDUCATION OF LAURYN HILL", u: "../images/90s-albums/the-miseducation-of-lauryn-hill.jpg" },
    { n: "DANGEROUS", u: "../images/90s-albums/dangerous.jpg" },
    { n: "ALL EYEZ ON ME", u: "../images/90s-albums/all-eyez-on-me.jpg" },
    { n: "THE CHRONIC", u: "../images/90s-albums/the-chronic.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "TEN", u: "../images/90s-albums/ten.jpg" },
    { n: "CALIFORNICATION", u: "../images/90s-albums/californication.jpg" },
    { n: "RAY OF LIGHT", u: "../images/90s-albums/ray-of-light.jpg" },
    { n: "ENEMA OF THE STATE", u: "../images/90s-albums/enema-of-the-state.jpg" },
    { n: "TRAGIC KINGDOM", u: "../images/90s-albums/tragic-kingdom.jpg" },
    { n: "AQUARIUM", u: "../images/90s-albums/aquarium.jpg" },
    { n: "MELLON COLLIE AND THE INFINITE SADNESS", u: "../images/90s-albums/mellon-collie.jpg" },
    { n: "READY TO DIE", u: "../images/90s-albums/ready-to-die.jpg" },
    { n: "ILLMATIC", u: "../images/90s-albums/illmatic.jpg" },
    { n: "SUPERNATURAL", u: "../images/90s-albums/supernatural.jpg" },
    { n: "CHRISTINA AGUILERA", u: "../images/90s-albums/christina-aguilera.jpg" },
    { n: "FALLING INTO YOU", u: "../images/90s-albums/falling-into-you.jpg" },
    { n: "DAYDREAM", u: "../images/90s-albums/daydream.jpg" },
    { n: "THE SCORE", u: "../images/90s-albums/the-score.jpg" },
    { n: "WEEZER (THE BLUE ALBUM)", u: "../images/90s-albums/weezer-blue.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "AUTOMATIC FOR THE PEOPLE", u: "../images/90s-albums/automatic-for-the-people.jpg" },
    { n: "DIRT", u: "../images/90s-albums/dirt.jpg" },
    { n: "THE DOWNWARD SPIRAL", u: "../images/90s-albums/the-downward-spiral.jpg" },
    { n: "ODELAY", u: "../images/90s-albums/odelay.jpg" },
    { n: "SURFACING", u: "../images/90s-albums/surfacing.jpg" },
    { n: "REASONABLE DOUBT", u: "../images/90s-albums/reasonable-doubt.jpg" },
    { n: "MY WAY", u: "../images/90s-albums/my-way.jpg" },
    { n: "THE BOY IS MINE", u: "../images/90s-albums/the-boy-is-mine.jpg" },
    { n: "HOMOGENIC", u: "../images/90s-albums/homogenic.jpg" },
    { n: "POST", u: "../images/90s-albums/post.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "DEFINITELY MAYBE", u: "../images/90s-albums/definitely-maybe.jpg" },
    { n: "(WHAT'S THE STORY) MORNING GLORY?", u: "../images/90s-albums/morning-glory.jpg" },
    { n: "ENTER THE WU-TANG (36 CHAMBERS)", u: "../images/90s-albums/wu-tang.jpg" },
    { n: "BLOOD SUGAR SEX MAGIK", u: "../images/90s-albums/blood-sugar-sex-magik.jpg" },
    { n: "USE YOUR ILLUSION I", u: "../images/90s-albums/use-your-illusion-i.jpg" },
    { n: "GRACE", u: "../images/90s-albums/grace.jpg" },
    { n: "DUMMY", u: "../images/90s-albums/dummy.jpg" },
    { n: "EITHER/OR", u: "../images/90s-albums/either-or.jpg" },
    { n: "IN THE AEROPLANE OVER THE SEA", u: "../images/90s-albums/aeroplane.jpg" },
    { n: "LOVELESS", u: "../images/90s-albums/loveless.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "THE BENDS", u: "../images/90s-albums/the-bends.jpg" },
    { n: "SIAMESE DREAM", u: "../images/90s-albums/siamese-dream.jpg" },
    { n: "CORE", u: "../images/90s-albums/core.jpg" },
    { n: "BADMOTORFINGER", u: "../images/90s-albums/badmotorfinger.jpg" },
    { n: "ANTICHRIST SUPERSTAR", u: "../images/90s-albums/antichrist-superstar.jpg" },
    { n: "FOLLOW THE LEADER", u: "../images/90s-albums/follow-the-leader.jpg" },
    { n: "SIGNIFICANT OTHER", u: "../images/90s-albums/significant-other.jpg" },
    { n: "SLIPKNOT", u: "../images/90s-albums/slipknot.jpg" },
    { n: "RITUAL DE LO HABITUAL", u: "../images/90s-albums/ritual-de-lo-habitual.jpg" },
    { n: "SUPERUNKNOWN", u: "../images/90s-albums/superunknown.jpg" },
];
if (typeof window !== 'undefined') window.the90sAlbumsData = the90sAlbumsData;
