// Anime — images in images/anime/
const animeData = [
    // Tier 1 — Obvious (1–15)
    { n: "DRAGON BALL Z", u: "../images/anime/dragon-ball-z.jpg" },
    { n: "NARUTO", u: "../images/anime/naruto.jpg" },
    { n: "ONE PIECE", u: "../images/anime/one-piece.jpg" },
    { n: "ATTACK ON TITAN", u: "../images/anime/attack-on-titan.jpg" },
    { n: "SAILOR MOON", u: "../images/anime/sailor-moon.jpg" },
    { n: "DEMON SLAYER", u: "../images/anime/demon-slayer.jpg" },
    { n: "DEATH NOTE", u: "../images/anime/death-note.jpg" },
    { n: "MY HERO ACADEMIA", u: "../images/anime/my-hero-academia.jpg" },
    { n: "SPIRITED AWAY", u: "../images/anime/spirited-away.jpg" },
    { n: "ONE PUNCH MAN", u: "../images/anime/one-punch-man.jpg" },
    { n: "JUJUTSU KAISEN", u: "../images/anime/jujutsu-kaisen.jpg" },
    { n: "FULLMETAL ALCHEMIST", u: "../images/anime/fullmetal-alchemist.webp" },
    { n: "SWORD ART ONLINE", u: "../images/anime/sword-art-online.jpg" },
    { n: "SPY X FAMILY", u: "../images/anime/spy-x-family.png" },
    { n: "TOKYO GHOUL", u: "../images/anime/tokyo-ghoul.webp" },

    // Tier 2 — Familiar (16–30)
    { n: "HUNTER X HUNTER", u: "../images/anime/hunter-x-hunter.jpg" },
    { n: "BLEACH", u: "../images/anime/bleach.jpg" },
    { n: "COWBOY BEBOP", u: "../images/anime/cowboy-bebop.jpg" },
    { n: "NEON GENESIS EVANGELION", u: "../images/anime/neon-genesis-evangelion.jpg" },
    { n: "MY NEIGHBOR TOTORO", u: "../images/anime/my-neighbor-totoro.jpg" },
    { n: "CHAINSAW MAN", u: "../images/anime/chainsaw-man.jpg" },
    { n: "FAIRY TAIL", u: "../images/anime/fairy-tail.jpg" },
    { n: "BLACK CLOVER", u: "../images/anime/black-clover.jpg" },
    { n: "INUYASHA", u: "../images/anime/inuyasha.jpg" },
    { n: "AKIRA", u: "../images/anime/akira.jpg" },
    { n: "PRINCESS MONONOKE", u: "../images/anime/princess-mononoke.jpg" },
    { n: "MOB PSYCHO 100", u: "../images/anime/mob-psycho-100.png" },
    { n: "HAIKYUU", u: "../images/anime/haikyuu.jpg" },
    { n: "BLUE LOCK", u: "../images/anime/blue-lock.jpg" },
    { n: "SOLO LEVELING", u: "../images/anime/solo-leveling.jpg" },

    // Tier 3 — Knowledgeable (31–40)
    { n: "VINLAND SAGA", u: "../images/anime/vinland-saga.png" },
    { n: "STEINS;GATE", u: "../images/anime/steins-gate.png" },
    { n: "FIRE FORCE", u: "../images/anime/fire-force.webp" },
    { n: "CODE GEASS", u: "../images/anime/code-geass.jpg" },
    { n: "RE:ZERO", u: "../images/anime/re-zero.png" },
    { n: "DR. STONE", u: "../images/anime/dr-stone.jpg" },
    { n: "SOUL EATER", u: "../images/anime/soul-eater.webp" },
    { n: "TRIGUN", u: "../images/anime/trigun.jpg" },
    { n: "FRUITS BASKET", u: "../images/anime/fruits-basket.webp" },
    { n: "BERSERK", u: "../images/anime/berserk.png" },

    // Tier 4 — Expert (41–50)
    { n: "GHOST IN THE SHELL", u: "../images/anime/ghost-in-the-shell.jpg" },
    { n: "ERASED", u: "../images/anime/erased.webp" },
    { n: "PARASYTE", u: "../images/anime/parasyte.jpg" },
    { n: "MADE IN ABYSS", u: "../images/anime/made-in-abyss.webp" },
    { n: "PSYCHO-PASS", u: "../images/anime/psycho-pass.png" },
    { n: "SAMURAI CHAMPLOO", u: "../images/anime/samurai-champloo.jpg" },
    { n: "MONSTER", u: "../images/anime/monster.jpg" },
    { n: "SERIAL EXPERIMENTS LAIN", u: "../images/anime/serial-experiments-lain.jpg" },
    { n: "PAPRIKA", u: "../images/anime/paprika.jpg" },
    { n: "PERFECT BLUE", u: "../images/anime/perfect-blue.jpg" },

    // ── BACKUPS (51–60) ────────────────
    { n: "GURREN LAGANN", u: "../images/anime/gurren-lagann.jpg" },
    { n: "FLCL", u: "../images/anime/flcl.jpg" },
    { n: "CLAYMORE", u: "../images/anime/claymore.jpg" },
    { n: "DURARARA", u: "../images/anime/durarara.jpg" },
    { n: "MUSHISHI", u: "../images/anime/mushishi.webp" },
    { n: "DARKER THAN BLACK", u: "../images/anime/darker-than-black.jpg" },
    { n: "ELFEN LIED", u: "../images/anime/elfen-lied.jpg" },
    { n: "LEGEND OF THE GALACTIC HEROES", u: "../images/anime/legend-of-the-galactic-heroes.webp" },
    { n: "TEXHNOLYZE", u: "../images/anime/texhnolyze.jpg" },
    { n: "GOLDEN KAMUY", u: "../images/anime/golden-kamuy.jpg" },
];
if (typeof window !== 'undefined') window.animeData = animeData;
