const birdsData = [
    { n: "BALD EAGLE", u: "../images/birds/bald-eagle.webp" },
    { n: "PENGUIN", u: "../images/birds/penguin.webp" },
    { n: "OSTRICH", u: "../images/birds/ostrich.webp" },
    { n: "PEACOCK", u: "../images/birds/peacock.webp" },
    { n: "FLAMINGO", u: "../images/birds/flamingo.webp" },
    { n: "OWL", u: "../images/birds/owl.webp" },
    { n: "PIGEON", u: "../images/birds/pigeon.webp" },
    { n: "SEAGULL", u: "../images/birds/seagull.webp" },
    { n: "PELICAN", u: "../images/birds/pelican.webp" },
    { n: "SWAN", u: "../images/birds/swan.webp" },
    { n: "DUCK", u: "../images/birds/duck.webp" },
    { n: "WOODPECKER", u: "../images/birds/woodpecker.webp" },
    { n: "TOUCAN", u: "../images/birds/toucan.webp" },
    { n: "CHICKEN", u: "../images/birds/chicken.webp" },
    { n: "TURKEY", u: "../images/birds/turkey.webp" },
    { n: "CROW", u: "../images/birds/crow.webp" },
    { n: "HUMMINGBIRD", u: "../images/birds/hummingbird.webp" },
    { n: "BLUE JAY", u: "../images/birds/blue-jay.webp" },
    { n: "CARDINAL", u: "../images/birds/cardinal.webp" },
    { n: "ROBIN", u: "../images/birds/robin.webp" },
    { n: "ROOSTER", u: "../images/birds/rooster.webp" },
    { n: "GOOSE", u: "../images/birds/goose.webp" },
    { n: "FALCON", u: "../images/birds/falcon.webp" },
    { n: "HAWK", u: "../images/birds/hawk.webp" },
    { n: "VULTURE", u: "../images/birds/vulture.webp" },
    { n: "DODO", u: "../images/birds/dodo.webp" },
    { n: "KIWI", u: "../images/birds/kiwi.webp" },
    { n: "EMU", u: "../images/birds/emu.webp" },
    { n: "MACAW", u: "../images/birds/macaw.webp" },
    { n: "COCKATOO", u: "../images/birds/cockatoo.webp" },
    { n: "PARAKEET", u: "../images/birds/parakeet.webp" },
    { n: "ALBATROSS", u: "../images/birds/albatross.webp" },
    { n: "KINGFISHER", u: "../images/birds/kingfisher.webp" },
    { n: "PUFFIN", u: "../images/birds/puffin.webp" },
    { n: "CRANE", u: "../images/birds/crane.webp" },
    { n: "HERON", u: "../images/birds/heron.webp" },
    { n: "OSPREY", u: "../images/birds/osprey.webp" },
    { n: "KOOKABURRA", u: "../images/birds/kookaburra.webp" },
    { n: "CANARY", u: "../images/birds/canary.webp" },
    { n: "FINCH", u: "../images/birds/finch.webp" },
    { n: "SPARROW", u: "../images/birds/sparrow.webp" },
    { n: "MOCKINGBIRD", u: "../images/birds/mockingbird.webp" },
    { n: "QUAIL", u: "../images/birds/quail.webp" },
    { n: "PHEASANT", u: "../images/birds/pheasant.webp" },
    { n: "STORK", u: "../images/birds/stork.webp" },
    { n: "ROADRUNNER", u: "../images/birds/roadrunner.webp" },
    { n: "MAGPIE", u: "../images/birds/magpie.webp" },
    { n: "CONDOR", u: "../images/birds/condor.webp" },
    { n: "CASSOWARY", u: "../images/birds/cassowary.webp" },
    
    // ── BACKUPS (items 51–60) ────────────────
    { n: "IBIS", u: "../images/birds/ibis.webp" },
    { n: "EGRET", u: "../images/birds/egret.webp" },
    { n: "HORNBILL", u: "../images/birds/hornbill.webp" },
    { n: "GUINEAFOWL", u: "../images/birds/guineafowl.webp" },
    { n: "NUTHATCH", u: "../images/birds/nuthatch.webp" },
    { n: "CHICKADEE", u: "../images/birds/chickadee.webp" },
    { n: "STARLING", u: "../images/birds/starling.webp" },
    { n: "LOON", u: "../images/birds/loon.webp" },
    { n: "HOOPOE", u: "../images/birds/hoopoe.webp" },
    { n: "SWALLOW", u: "../images/birds/swallow.webp" }
];
if (typeof window !== 'undefined') window.birdsData = birdsData;
