const blackLeadersData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "MARTIN LUTHER KING JR.", u: "../images/black-leaders/martin-luther-king-jr.jpg" },
    { n: "ROSA PARKS", u: "../images/black-leaders/rosa-parks.jpg" },
    { n: "BARACK OBAMA", u: "../images/black-leaders/barack-obama.jpg" },
    { n: "NELSON MANDELA", u: "../images/black-leaders/nelson-mandela.jpg" },
    { n: "MALCOLM X", u: "../images/black-leaders/malcolm-x.jpg" },
    { n: "HARRIET TUBMAN", u: "../images/black-leaders/harriet-tubman.jpg" },
    { n: "FREDERICK DOUGLASS", u: "../images/black-leaders/frederick-douglass.jpg" },
    { n: "MUHAMMAD ALI", u: "../images/black-leaders/muhammad-ali.jpg" },
    { n: "KAMALA HARRIS", u: "../images/black-leaders/kamala-harris.jpg" },
    { n: "MICHELLE OBAMA", u: "../images/black-leaders/michelle-obama.jpg" },
    { n: "THURGOOD MARSHALL", u: "../images/black-leaders/thurgood-marshall.jpg" },
    { n: "COLIN POWELL", u: "../images/black-leaders/colin-powell.jpg" },
    { n: "JOHN LEWIS", u: "../images/black-leaders/john-lewis.jpg" },
    { n: "MAYA ANGELOU", u: "../images/black-leaders/maya-angelou.jpg" },
    { n: "JACKIE ROBINSON", u: "../images/black-leaders/jackie-robinson.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "BOOKER T. WASHINGTON", u: "../images/black-leaders/booker-t-washington.jpg" },
    { n: "W.E.B. DU BOIS", u: "../images/black-leaders/web-du-bois.jpg" },
    { n: "SHIRLEY CHISHOLM", u: "../images/black-leaders/shirley-chisholm.jpg" },
    { n: "CORETTA SCOTT KING", u: "../images/black-leaders/coretta-scott-king.jpg" },
    { n: "JESSE JACKSON", u: "../images/black-leaders/jesse-jackson.jpg" },
    { n: "KETANJI BROWN JACKSON", u: "../images/black-leaders/ketanji-brown-jackson.jpg" },
    { n: "CLARENCE THOMAS", u: "../images/black-leaders/clarence-thomas.jpg" },
    { n: "CONDOLEEZZA RICE", u: "../images/black-leaders/condoleezza-rice.jpg" },
    { n: "GEORGE WASHINGTON CARVER", u: "../images/black-leaders/george-washington-carver.jpg" },
    { n: "SOJOURNER TRUTH", u: "../images/black-leaders/sojourner-truth.jpg" },
    { n: "AL SHARPTON", u: "../images/black-leaders/al-sharpton.jpg" },
    { n: "IDA B. WELLS", u: "../images/black-leaders/ida-b-wells.jpg" },
    { n: "MARCUS GARVEY", u: "../images/black-leaders/marcus-garvey.jpg" },
    { n: "MEDGAR EVERS", u: "../images/black-leaders/medgar-evers.jpg" },
    { n: "DESMOND TUTU", u: "../images/black-leaders/desmond-tutu.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "LANGSTON HUGHES", u: "../images/black-leaders/langston-hughes.jpg" },
    { n: "RALPH ABERNATHY", u: "../images/black-leaders/ralph-abernathy.jpg" },
    { n: "ANDREW YOUNG", u: "../images/black-leaders/andrew-young.jpg" },
    { n: "KOFI ANNAN", u: "../images/black-leaders/kofi-annan.jpg" },
    { n: "BARBARA JORDAN", u: "../images/black-leaders/barbara-jordan.jpg" },
    { n: "STACEY ABRAMS", u: "../images/black-leaders/stacey-abrams.jpg" },
    { n: "ELIJAH CUMMINGS", u: "../images/black-leaders/elijah-cummings.jpg" },
    { n: "HAKEEM JEFFRIES", u: "../images/black-leaders/hakeem-jeffries.jpg" },
    { n: "MAXINE WATERS", u: "../images/black-leaders/maxine-waters.jpg" },
    { n: "CORY BOOKER", u: "../images/black-leaders/cory-booker.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "RAPHAEL WARNOCK", u: "../images/black-leaders/raphael-warnock.jpg" },
    { n: "CAROL MOSELEY BRAUN", u: "../images/black-leaders/carol-moseley-braun.jpg" },
    { n: "ERIC HOLDER", u: "../images/black-leaders/eric-holder.jpg" },
    { n: "LLOYD AUSTIN", u: "../images/black-leaders/lloyd-austin.jpg" },
    { n: "JULIAN BOND", u: "../images/black-leaders/julian-bond.jpg" },
    { n: "BAYARD RUSTIN", u: "../images/black-leaders/bayard-rustin.jpg" },
    { n: "FANNIE LOU HAMER", u: "../images/black-leaders/fannie-lou-hamer.jpg" },
    { n: "ELLA BAKER", u: "../images/black-leaders/ella-baker.jpg" },
    { n: "A. PHILIP RANDOLPH", u: "../images/black-leaders/a-philip-randolph.jpg" },
    { n: "WHITNEY YOUNG", u: "../images/black-leaders/whitney-young.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "HARRY BELAFONTE", u: "../images/black-leaders/harry-belafonte.jpg" },
    { n: "JAMES BALDWIN", u: "../images/black-leaders/james-baldwin.jpg" },
    { n: "ARTHUR ASHE", u: "../images/black-leaders/arthur-ashe.jpg" },
    { n: "MARY MCLEOD BETHUNE", u: "../images/black-leaders/mary-mcleod-bethune.jpg" },
    { n: "SHIRLEY FRANKLIN", u: "../images/black-leaders/shirley-franklin.jpg" },
    { n: "EDWARD BROOKE", u: "../images/black-leaders/edward-brooke.jpg" },
    { n: "DOUGLAS WILDER", u: "../images/black-leaders/douglas-wilder.jpg" },
    { n: "DEVAL PATRICK", u: "../images/black-leaders/deval-patrick.jpg" },
    { n: "DAVID DINKINS", u: "../images/black-leaders/david-dinkins.jpg" },
    { n: "HAROLD WASHINGTON", u: "../images/black-leaders/harold-washington.jpg" },
];
if (typeof window !== 'undefined') window.blackLeadersData = blackLeadersData;
