const chemistryData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "BEAKER", u: "../images/chemistry/beaker.jpg" },
    { n: "TEST TUBE", u: "../images/chemistry/test-tube.jpg" },
    { n: "PERIODIC TABLE", u: "../images/chemistry/periodic-table.jpg" },
    { n: "BUNSEN BURNER", u: "../images/chemistry/bunsen-burner.jpg" },
    { n: "SAFETY GOGGLES", u: "../images/chemistry/safety-goggles.jpg" },
    { n: "ERLENMEYER FLASK", u: "../images/chemistry/erlenmeyer-flask.jpg" },
    { n: "GRADUATED CYLINDER", u: "../images/chemistry/graduated-cylinder.jpg" },
    { n: "PIPETTE", u: "../images/chemistry/pipette.jpg" },
    { n: "DROPPER", u: "../images/chemistry/dropper.jpg" },
    { n: "THERMOMETER", u: "../images/chemistry/thermometer.jpg" },
    { n: "FUNNEL", u: "../images/chemistry/funnel.jpg" },
    { n: "TONGS", u: "../images/chemistry/tongs.jpg" },
    { n: "MORTAR AND PESTLE", u: "../images/chemistry/mortar-and-pestle.jpg" },
    { n: "ATOM (MODEL)", u: "../images/chemistry/atom-model.jpg" },
    { n: "WATER MOLECULE (H2O)", u: "../images/chemistry/water-molecule.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "MARIE CURIE", u: "../images/chemistry/marie-curie.jpg" },
    { n: "DMITRI MENDELEEV", u: "../images/chemistry/dmitri-mendeleev.jpg" },
    { n: "ROSALIND FRANKLIN", u: "../images/chemistry/rosalind-franklin.jpg" },
    { n: "LOUIS PASTEUR", u: "../images/chemistry/louis-pasteur.jpg" },
    { n: "GOLD (Au)", u: "../images/chemistry/gold.jpg" },
    { n: "SILVER (Ag)", u: "../images/chemistry/silver.jpg" },
    { n: "COPPER (Cu)", u: "../images/chemistry/copper.jpg" },
    { n: "IRON (Fe)", u: "../images/chemistry/iron.jpg" },
    { n: "CARBON (DIAMOND)", u: "../images/chemistry/diamond.jpg" },
    { n: "CARBON (COAL)", u: "../images/chemistry/coal.jpg" },
    { n: "NEON (SIGN)", u: "../images/chemistry/neon-sign.jpg" },
    { n: "HELIUM (BALLOONS)", u: "../images/chemistry/helium-balloons.jpg" },
    { n: "SULFUR (YELLOW POWDER)", u: "../images/chemistry/sulfur-powder.jpg" },
    { n: "MERCURY (LIQUID METAL)", u: "../images/chemistry/mercury.jpg" },
    { n: "LITMUS PAPER", u: "../images/chemistry/litmus-paper.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "BURETTE", u: "../images/chemistry/burette.jpg" },
    { n: "VOLUMETRIC FLASK", u: "../images/chemistry/volumetric-flask.jpg" },
    { n: "CRUCIBLE", u: "../images/chemistry/crucible.jpg" },
    { n: "WATCH GLASS", u: "../images/chemistry/watch-glass.jpg" },
    { n: "RING STAND", u: "../images/chemistry/ring-stand.jpg" },
    { n: "WIRE GAUZE", u: "../images/chemistry/wire-gauze.jpg" },
    { n: "EVAPORATING DISH", u: "../images/chemistry/evaporating-dish.jpg" },
    { n: "WASH BOTTLE", u: "../images/chemistry/wash-bottle.jpg" },
    { n: "CENTRIFUGE", u: "../images/chemistry/centrifuge.jpg" },
    { n: "FUME HOOD", u: "../images/chemistry/fume-hood.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "DRY ICE", u: "../images/chemistry/dry-ice.jpg" },
    { n: "LIQUID NITROGEN", u: "../images/chemistry/liquid-nitrogen.jpg" },
    { n: "CRYSTALS", u: "../images/chemistry/crystals.jpg" },
    { n: "RUST (OXIDATION)", u: "../images/chemistry/rust.jpg" },
    { n: "PH METER", u: "../images/chemistry/ph-meter.jpg" },
    { n: "BALANCE SCALE", u: "../images/chemistry/balance-scale.jpg" },
    { n: "HOT PLATE", u: "../images/chemistry/hot-plate.jpg" },
    { n: "MAGNETIC STIRRER", u: "../images/chemistry/magnetic-stirrer.jpg" },
    { n: "CORK STOPPER", u: "../images/chemistry/cork-stopper.jpg" },
    { n: "RUBBER STOPPER", u: "../images/chemistry/rubber-stopper.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "TEST TUBE RACK", u: "../images/chemistry/test-tube-rack.jpg" },
    { n: "TEST TUBE BRUSH", u: "../images/chemistry/test-tube-brush.jpg" },
    { n: "SPATULA", u: "../images/chemistry/spatula.jpg" },
    { n: "FORCEPS", u: "../images/chemistry/forceps.jpg" },
    { n: "DESICCATOR", u: "../images/chemistry/desiccator.jpg" },
    { n: "CONDENSER", u: "../images/chemistry/condenser.jpg" },
    { n: "CALORIMETER", u: "../images/chemistry/calorimeter.jpg" },
    { n: "SPECTROPHOTOMETER", u: "../images/chemistry/spectrophotometer.jpg" },
    { n: "CHROMATOGRAPHY PAPER", u: "../images/chemistry/chromatography-paper.jpg" },
    { n: "DISTILLATION APPARATUS", u: "../images/chemistry/distillation-apparatus.jpg" },
];
if (typeof window !== 'undefined') window.chemistryData = chemistryData;
