// College Logos — images in images/college-logos/
const collegeLogosData = [
    // Tier 1 — Obvious (1–15)
    { n: "MICHIGAN", u: "../images/college-logos/michigan.webp" },
    { n: "ALABAMA", u: "../images/college-logos/alabama.webp" },
    { n: "OHIO STATE", u: "../images/college-logos/ohio-state.webp" },
    { n: "NOTRE DAME", u: "../images/college-logos/notre-dame.webp" },
    { n: "TEXAS", u: "../images/college-logos/texas.webp" },
    { n: "CLEMSON", u: "../images/college-logos/clemson.webp" },
    { n: "OREGON", u: "../images/college-logos/oregon.webp" },
    { n: "PENN STATE", u: "../images/college-logos/penn-state.webp" },
    { n: "FLORIDA STATE", u: "../images/college-logos/florida-state.webp" },
    { n: "LSU", u: "../images/college-logos/lsu.webp" },
    { n: "USC", u: "../images/college-logos/usc.webp" },
    { n: "FLORIDA", u: "../images/college-logos/florida.webp" },
    { n: "GEORGIA", u: "../images/college-logos/georgia.webp" },
    { n: "MICHIGAN STATE", u: "../images/college-logos/michigan-state.webp" },
    { n: "TENNESSEE", u: "../images/college-logos/tennessee.webp" },

    // Tier 2 — Familiar (16–30)
    { n: "AUBURN", u: "../images/college-logos/auburn.webp" },
    { n: "OKLAHOMA", u: "../images/college-logos/oklahoma.webp" },
    { n: "WISCONSIN", u: "../images/college-logos/wisconsin.webp" },
    { n: "TEXAS A&M", u: "../images/college-logos/texas-am.webp" },
    { n: "DUKE", u: "../images/college-logos/duke.webp" },
    { n: "NORTH CAROLINA", u: "../images/college-logos/north-carolina.webp" },
    { n: "KENTUCKY", u: "../images/college-logos/kentucky.webp" },
    { n: "SOUTH CAROLINA", u: "../images/college-logos/south-carolina.webp" },
    { n: "MIAMI", u: "../images/college-logos/miami.webp" },
    { n: "IOWA", u: "../images/college-logos/iowa.webp" },
    { n: "NEBRASKA", u: "../images/college-logos/nebraska.webp" },
    { n: "VIRGINIA TECH", u: "../images/college-logos/virginia-tech.webp" },
    { n: "STANFORD", u: "../images/college-logos/stanford.webp" },
    { n: "ARKANSAS", u: "../images/college-logos/arkansas.webp" },
    { n: "WASHINGTON", u: "../images/college-logos/washington.webp" },

    // Tier 3 — Knowledgeable (31–40)
    { n: "KANSAS", u: "../images/college-logos/kansas.webp" },
    { n: "COLORADO", u: "../images/college-logos/colorado.webp" },
    { n: "MARYLAND", u: "../images/college-logos/maryland.webp" },
    { n: "BAYLOR", u: "../images/college-logos/baylor.webp" },
    { n: "MISSISSIPPI STATE", u: "../images/college-logos/mississippi-state.webp" },
    { n: "ARIZONA STATE", u: "../images/college-logos/arizona-state.webp" },
    { n: "IOWA STATE", u: "../images/college-logos/iowa-state.webp" },
    { n: "OREGON STATE", u: "../images/college-logos/oregon-state.webp" },
    { n: "PITTSBURGH", u: "../images/college-logos/pittsburgh.webp" },
    { n: "OLE MISS", u: "../images/college-logos/ole-miss.webp" },

    // Tier 4 — Expert (41–50)
    { n: "WAKE FOREST", u: "../images/college-logos/wake-forest.webp" },
    { n: "PURDUE", u: "../images/college-logos/purdue.webp" },
    { n: "VANDERBILT", u: "../images/college-logos/vanderbilt.webp" },
    { n: "BOSTON COLLEGE", u: "../images/college-logos/boston-college.webp" },
    { n: "SYRACUSE", u: "../images/college-logos/syracuse.webp" },
    { n: "MINNESOTA", u: "../images/college-logos/minnesota.webp" },
    { n: "RUTGERS", u: "../images/college-logos/rutgers.webp" },
    { n: "CINCINNATI", u: "../images/college-logos/cincinnati.webp" },
    { n: "HOUSTON", u: "../images/college-logos/houston.webp" },
    { n: "UCF", u: "../images/college-logos/ucf.webp" },

    // ── BACKUPS (51–60) ────────────────
    { n: "BYU", u: "../images/college-logos/byu.webp" },
    { n: "ARMY", u: "../images/college-logos/army.webp" },
    { n: "NAVY", u: "../images/college-logos/navy.webp" },
    { n: "BOISE STATE", u: "../images/college-logos/boise-state.webp" },
    { n: "MEMPHIS", u: "../images/college-logos/memphis.webp" },
    { n: "GONZAGA", u: "../images/college-logos/gonzaga.webp" },
    { n: "TULANE", u: "../images/college-logos/tulane.webp" },
    { n: "VILLANOVA", u: "../images/college-logos/villanova.webp" },
    { n: "CONNECTICUT", u: "../images/college-logos/connecticut.webp" },
    { n: "AIR FORCE", u: "../images/college-logos/air-force.webp" },
];
if (typeof window !== 'undefined') window.collegeLogosData = collegeLogosData;
