// College Logos — images in images/college-logos/
const collegeLogosData = [
    // Tier 1 — Obvious (1–15)
    { n: "MICHIGAN", u: "../images/college-logos/michigan.svg" },
    { n: "ALABAMA", u: "../images/college-logos/alabama.svg" },
    { n: "OHIO STATE", u: "../images/college-logos/ohio-state.png" },
    { n: "NOTRE DAME", u: "../images/college-logos/notre-dame.jpg" },
    { n: "TEXAS A&M", u: "../images/college-logos/texas.png" },
    { n: "CLEMSON", u: "../images/college-logos/clemson.svg" },
    { n: "OREGON", u: "../images/college-logos/oregon.png" },
    { n: "PENN STATE", u: "../images/college-logos/penn-state.webp" },
    { n: "FLORIDA STATE", u: "../images/college-logos/florida-state.png" },
    { n: "LSU", u: "../images/college-logos/lsu.png" },
    { n: "USC", u: "../images/college-logos/usc.png" },
    { n: "FLORIDA", u: "../images/college-logos/florida.svg" },
    { n: "GEORGIA", u: "../images/college-logos/georgia.svg" },
    { n: "MICHIGAN STATE", u: "../images/college-logos/michigan-state.jpg" },
    { n: "TENNESSEE", u: "../images/college-logos/tennessee.png" },

    // Tier 2 — Familiar (16–30)
    { n: "AUBURN", u: "../images/college-logos/auburn.svg" },
    { n: "OKLAHOMA", u: "../images/college-logos/oklahoma.svg" },
    { n: "WISCONSIN", u: "../images/college-logos/wisconsin.svg" },
    { n: "DUKE", u: "../images/college-logos/duke.jpg" },
    { n: "NORTH CAROLINA", u: "../images/college-logos/north-carolina.png" },
    { n: "KENTUCKY", u: "../images/college-logos/kentucky.svg" },
    { n: "SOUTH CAROLINA", u: "../images/college-logos/south-carolina.png" },
    { n: "MIAMI", u: "../images/college-logos/miami.svg" },
    { n: "IOWA", u: "../images/college-logos/iowa.png" },
    { n: "NEBRASKA", u: "../images/college-logos/nebraska.png" },
    { n: "VIRGINIA TECH", u: "../images/college-logos/virginia-tech.png" },
    { n: "STANFORD", u: "../images/college-logos/stanford.svg" },
    { n: "ARKANSAS", u: "../images/college-logos/arkansas.jpg" },
    { n: "WASHINGTON", u: "../images/college-logos/washington.png" },

    // Tier 3 — Knowledgeable (31–40)
    { n: "KANSAS", u: "../images/college-logos/kansas.svg" },
    { n: "COLORADO", u: "../images/college-logos/colorado.svg" },
    { n: "MARYLAND", u: "../images/college-logos/maryland.png" },
    { n: "BAYLOR", u: "../images/college-logos/baylor.jpg" },
    { n: "MISSISSIPPI STATE", u: "../images/college-logos/mississippi-state.jpg" },
    { n: "ARIZONA STATE", u: "../images/college-logos/arizona-state.jpg" },
    { n: "IOWA STATE", u: "../images/college-logos/iowa-state.svg" },
    { n: "OREGON STATE", u: "../images/college-logos/oregon-state.svg" },
    { n: "PITTSBURGH", u: "../images/college-logos/pittsburgh.jpg" },
    { n: "OLE MISS", u: "../images/college-logos/ole-miss.png" },

    // Tier 4 — Expert (41–50)
    { n: "WAKE FOREST", u: "../images/college-logos/wake-forest.png" },
    { n: "PURDUE", u: "../images/college-logos/purdue.svg" },
    { n: "VANDERBILT", u: "../images/college-logos/vanderbilt.jpg" },
    { n: "BOSTON COLLEGE", u: "../images/college-logos/boston-college.svg" },
    { n: "SYRACUSE", u: "../images/college-logos/syracuse.png" },
    { n: "MINNESOTA", u: "../images/college-logos/minnesota.svg" },
    { n: "RUTGERS", u: "../images/college-logos/rutgers.svg" },
    { n: "CINCINNATI", u: "../images/college-logos/cincinnati.svg" },
    { n: "HOUSTON", u: "../images/college-logos/houston.svg" },
    { n: "UCF", u: "../images/college-logos/ucf.svg" },

    // ── BACKUPS (51–60) ────────────────
    { n: "BYU", u: "../images/college-logos/byu.png" },
    { n: "ARMY", u: "../images/college-logos/army.svg" },
    { n: "NAVY", u: "../images/college-logos/navy.svg" },
    { n: "BOISE STATE", u: "../images/college-logos/boise-state.svg" },
    { n: "MEMPHIS", u: "../images/college-logos/memphis.png" },
    { n: "GONZAGA", u: "../images/college-logos/gonzaga.svg" },
    { n: "TULANE", u: "../images/college-logos/tulane.png" },
    { n: "VILLANOVA", u: "../images/college-logos/villanova.png" },
    { n: "CONNECTICUT", u: "../images/college-logos/connecticut.svg" },
    { n: "AIR FORCE", u: "../images/college-logos/air-force.svg" },
];
if (typeof window !== 'undefined') window.collegeLogosData = collegeLogosData;
