const craftsData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "YARN", u: "../images/crafts/yarn.jpg" },
    { n: "SCISSORS", u: "../images/crafts/scissors.jpg" },
    { n: "GLUE STICK", u: "../images/crafts/glue-stick.jpg" },
    { n: "HOT GLUE GUN", u: "../images/crafts/hot-glue-gun.jpg" },
    { n: "PAINTBRUSH", u: "../images/crafts/paintbrush.jpg" },
    { n: "CRAYONS", u: "../images/crafts/crayons.jpg" },
    { n: "COLORED PENCILS", u: "../images/crafts/colored-pencils.jpg" },
    { n: "MARKERS", u: "../images/crafts/markers.jpg" },
    { n: "ORIGAMI", u: "../images/crafts/origami.jpg" },
    { n: "CLAY", u: "../images/crafts/clay.jpg" },
    { n: "BEADS", u: "../images/crafts/beads.jpg" },
    { n: "SEQUINS", u: "../images/crafts/sequins.jpg" },
    { n: "GLITTER", u: "../images/crafts/glitter.jpg" },
    { n: "PIPE CLEANERS", u: "../images/crafts/pipe-cleaners.jpg" },
    { n: "POPSICLE STICKS", u: "../images/crafts/popsicle-sticks.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "GOOGLY EYES", u: "../images/crafts/googly-eyes.jpg" },
    { n: "TIE-DYE", u: "../images/crafts/tie-dye.jpg" },
    { n: "CROSS STITCH", u: "../images/crafts/cross-stitch.jpg" },
    { n: "CROCHET HOOK", u: "../images/crafts/crochet-hook.jpg" },
    { n: "KNITTING NEEDLES", u: "../images/crafts/knitting-needles.jpg" },
    { n: "WATERCOLORS", u: "../images/crafts/watercolors.jpg" },
    { n: "ACRYLIC PAINT", u: "../images/crafts/acrylic-paint.jpg" },
    { n: "CANVAS", u: "../images/crafts/canvas.jpg" },
    { n: "EASEL", u: "../images/crafts/easel.jpg" },
    { n: "TAPE MEASURE", u: "../images/crafts/tape-measure.jpg" },
    { n: "SEWING MACHINE", u: "../images/crafts/sewing-machine.jpg" },
    { n: "THREAD", u: "../images/crafts/thread.jpg" },
    { n: "THIMBLE", u: "../images/crafts/thimble.jpg" },
    { n: "PINCUSHION", u: "../images/crafts/pincushion.jpg" },
    { n: "FELT", u: "../images/crafts/felt.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "POM POMS", u: "../images/crafts/pom-poms.jpg" },
    { n: "TISSUE PAPER", u: "../images/crafts/tissue-paper.jpg" },
    { n: "MOD PODGE", u: "../images/crafts/mod-podge.jpg" },
    { n: "STAMPS", u: "../images/crafts/stamps.jpg" },
    { n: "INK PAD", u: "../images/crafts/ink-pad.jpg" },
    { n: "STENCIL", u: "../images/crafts/stencil.jpg" },
    { n: "SCRAPBOOK", u: "../images/crafts/scrapbook.jpg" },
    { n: "EMBROIDERY HOOP", u: "../images/crafts/embroidery-hoop.jpg" },
    { n: "POLYMER CLAY", u: "../images/crafts/polymer-clay.jpg" },
    { n: "RESIN", u: "../images/crafts/resin.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "MACRAME", u: "../images/crafts/macrame.jpg" },
    { n: "CALLIGRAPHY PEN", u: "../images/crafts/calligraphy-pen.jpg" },
    { n: "WAX SEAL", u: "../images/crafts/wax-seal.jpg" },
    { n: "LINOLEUM CUTTER", u: "../images/crafts/linoleum-cutter.jpg" },
    { n: "POTTERY WHEEL", u: "../images/crafts/pottery-wheel.jpg" },
    { n: "KILN", u: "../images/crafts/kiln.jpg" },
    { n: "QUILLING", u: "../images/crafts/quilling.jpg" },
    { n: "DECOUPAGE", u: "../images/crafts/decoupage.jpg" },
    { n: "LOOM", u: "../images/crafts/loom.jpg" },
    { n: "WEEDING TOOL", u: "../images/crafts/weeding-tool.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "CRICUT MACHINE", u: "../images/crafts/cricut-machine.jpg" },
    { n: "HEAT PRESS", u: "../images/crafts/heat-press.jpg" },
    { n: "FABRIC SHEARS", u: "../images/crafts/fabric-shears.jpg" },
    { n: "ROTARY CUTTER", u: "../images/crafts/rotary-cutter.jpg" },
    { n: "CUTTING MAT", u: "../images/crafts/cutting-mat.jpg" },
    { n: "BONE FOLDER", u: "../images/crafts/bone-folder.jpg" },
    { n: "SPRAY PAINT", u: "../images/crafts/spray-paint.jpg" },
    { n: "CHALK", u: "../images/crafts/chalk.jpg" },
    { n: "PASTELS", u: "../images/crafts/pastels.jpg" },
    { n: "SKETCHBOOK", u: "../images/crafts/sketchbook.jpg" },
];
if (typeof window !== 'undefined') window.craftsData = craftsData;
