const famousCouplesData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "ROMEO & JULIET", u: "../images/famous-couples/romeo-juliet.jpg" },
    { n: "BARBIE & KEN", u: "../images/famous-couples/barbie-ken.jpg" },
    { n: "MICKEY & MINNIE MOUSE", u: "../images/famous-couples/mickey-minnie.jpg" },
    { n: "HOMER & MARGE SIMPSON", u: "../images/famous-couples/homer-marge.jpg" },
    { n: "SHREK & FIONA", u: "../images/famous-couples/shrek-fiona.jpg" },
    { n: "PRINCE HARRY & MEGHAN MARKLE", u: "../images/famous-couples/harry-meghan.jpg" },
    { n: "PRINCE WILLIAM & KATE MIDDLETON", u: "../images/famous-couples/william-kate.jpg" },
    { n: "JAY-Z & BEYONCE", u: "../images/famous-couples/jay-z-beyonce.jpg" },
    { n: "DAVID & VICTORIA BECKHAM", u: "../images/famous-couples/david-victoria-beckham.jpg" },
    { n: "RYAN REYNOLDS & BLAKE LIVELY", u: "../images/famous-couples/ryan-blake.jpg" },
    { n: "TOM HOLLAND & ZENDAYA", u: "../images/famous-couples/tom-zendaya.jpg" },
    { n: "BARACK & MICHELLE OBAMA", u: "../images/famous-couples/barack-michelle-obama.jpg" },
    { n: "JOHN LEGEND & CHRISSY TEIGEN", u: "../images/famous-couples/john-chrissy.jpg" },
    { n: "TAYLOR SWIFT & TRAVIS KELCE", u: "../images/famous-couples/taylor-travis.jpg" },
    { n: "WILL SMITH & JADA PINKETT SMITH", u: "../images/famous-couples/will-jada.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "JUSTIN & HAILEY BIEBER", u: "../images/famous-couples/justin-hailey.jpg" },
    { n: "GEORGE & AMAL CLOONEY", u: "../images/famous-couples/george-amal.jpg" },
    { n: "ASHTON KUTCHER & MILA KUNIS", u: "../images/famous-couples/ashton-mila.jpg" },
    { n: "CHRIS HEMSWORTH & ELSA PATAKY", u: "../images/famous-couples/chris-elsa.jpg" },
    { n: "EMILY BLUNT & JOHN KRASINSKI", u: "../images/famous-couples/emily-john.jpg" },
    { n: "KURT RUSSELL & GOLDIE HAWN", u: "../images/famous-couples/kurt-goldie.jpg" },
    { n: "TOM HANKS & RITA WILSON", u: "../images/famous-couples/tom-rita.jpg" },
    { n: "HARRISON FORD & CALISTA FLOCKHART", u: "../images/famous-couples/harrison-calista.jpg" },
    { n: "SARAH MICHELLE GELLAR & FREDDIE PRINZE JR.", u: "../images/famous-couples/sarah-freddie.jpg" },
    { n: "KEVIN BACON & KYRA SEDGWICK", u: "../images/famous-couples/kevin-kyra.jpg" },
    { n: "NEIL PATRICK HARRIS & DAVID BURTKA", u: "../images/famous-couples/neil-david.jpg" },
    { n: "ELTON JOHN & DAVID FURNISH", u: "../images/famous-couples/elton-david.jpg" },
    { n: "ELLEN DEGENERES & PORTIA DE ROSSI", u: "../images/famous-couples/ellen-portia.jpg" },
    { n: "MEGAN FOX & MACHINE GUN KELLY", u: "../images/famous-couples/megan-mgk.jpg" },
    { n: "KATY PERRY & ORLANDO BLOOM", u: "../images/famous-couples/katy-orlando.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "CARDI B & OFFSET", u: "../images/famous-couples/cardi-offset.jpg" },
    { n: "RIHANNA & A$AP ROCKY", u: "../images/famous-couples/rihanna-asap.jpg" },
    { n: "GWEN STEFANI & BLAKE SHELTON", u: "../images/famous-couples/gwen-blake.jpg" },
    { n: "NICK JONAS & PRIYANKA CHOPRA", u: "../images/famous-couples/nick-priyanka.jpg" },
    { n: "JOHN LENNON & YOKO ONO", u: "../images/famous-couples/john-yoko.jpg" },
    { n: "JOHNNY CASH & JUNE CARTER", u: "../images/famous-couples/johnny-june.jpg" },
    { n: "SONNY & CHER", u: "../images/famous-couples/sonny-cher.jpg" },
    { n: "PAUL NEWMAN & JOANNE WOODWARD", u: "../images/famous-couples/paul-joanne.jpg" },
    { n: "HUMPHREY BOGART & LAUREN BACALL", u: "../images/famous-couples/humphrey-lauren.jpg" },
    { n: "RICHARD BURTON & ELIZABETH TAYLOR", u: "../images/famous-couples/richard-elizabeth.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "MARILYN MONROE & JOE DIMAGGIO", u: "../images/famous-couples/marilyn-joe.jpg" },
    { n: "JOHN F. KENNEDY & JACKIE KENNEDY", u: "../images/famous-couples/jfk-jackie.jpg" },
    { n: "CLEOPATRA & MARK ANTONY", u: "../images/famous-couples/cleopatra-mark.jpg" },
    { n: "BONNIE & CLYDE", u: "../images/famous-couples/bonnie-clyde.jpg" },
    { n: "PIERRE & MARIE CURIE", u: "../images/famous-couples/pierre-marie.jpg" },
    { n: "DIEGO RIVERA & FRIDA KAHLO", u: "../images/famous-couples/diego-frida.jpg" },
    { n: "QUEEN VICTORIA & PRINCE ALBERT", u: "../images/famous-couples/victoria-albert.jpg" },
    { n: "KING HENRY VIII & ANNE BOLEYN", u: "../images/famous-couples/henry-anne.jpg" },
    { n: "NAPOLEON & JOSEPHINE", u: "../images/famous-couples/napoleon-josephine.jpg" },
    { n: "DONALD & MELANIA TRUMP", u: "../images/famous-couples/donald-melania.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "BILL & HILLARY CLINTON", u: "../images/famous-couples/bill-hillary.jpg" },
    { n: "RONALD & NANCY REAGAN", u: "../images/famous-couples/ronald-nancy.jpg" },
    { n: "GOMEZ & MORTICIA ADDAMS", u: "../images/famous-couples/gomez-morticia.jpg" },
    { n: "BATMAN & CATWOMAN", u: "../images/famous-couples/batman-catwoman.jpg" },
    { n: "SUPERMAN & LOIS LANE", u: "../images/famous-couples/superman-lois.jpg" },
    { n: "SPIDER-MAN & MARY JANE", u: "../images/famous-couples/spiderman-maryjane.jpg" },
    { n: "ROSS & RACHEL", u: "../images/famous-couples/ross-rachel.jpg" },
    { n: "JIM & PAM", u: "../images/famous-couples/jim-pam.jpg" },
    { n: "JACK & ROSE", u: "../images/famous-couples/jack-rose.jpg" },
    { n: "MARIO & PRINCESS PEACH", u: "../images/famous-couples/mario-peach.jpg" },
];
if (typeof window !== 'undefined') window.famousCouplesData = famousCouplesData;
