const flagData = [
    {n: "USA", u: "https://flagcdn.com/w640/us.png"},
    {n: "CANADA", u: "https://flagcdn.com/w640/ca.png"},
    {n: "MEXICO", u: "https://flagcdn.com/w640/mx.png"},
    {n: "BRAZIL", u: "https://flagcdn.com/w640/br.png"},
    {n: "ARGENTINA", u: "https://flagcdn.com/w640/ar.png"},
    {n: "COLOMBIA", u: "https://flagcdn.com/w640/co.png"},
    {n: "PERU", u: "https://flagcdn.com/w640/pe.png"},
    {n: "CHILE", u: "https://flagcdn.com/w640/cl.png"},
    {n: "UK", u: "https://flagcdn.com/w640/gb.png"},
    {n: "FRANCE", u: "https://flagcdn.com/w640/fr.png"},
    {n: "GERMANY", u: "https://flagcdn.com/w640/de.png"},
    {n: "ITALY", u: "https://flagcdn.com/w640/it.png"},
    {n: "SPAIN", u: "https://flagcdn.com/w640/es.png"},
    {n: "PORTUGAL", u: "https://flagcdn.com/w640/pt.png"},
    {n: "RUSSIA", u: "https://flagcdn.com/w640/ru.png"},
    {n: "UKRAINE", u: "https://flagcdn.com/w640/ua.png"},
    {n: "POLAND", u: "https://flagcdn.com/w640/pl.png"},
    {n: "NETHERLANDS", u: "https://flagcdn.com/w640/nl.png"},
    {n: "BELGIUM", u: "https://flagcdn.com/w640/be.png"},
    {n: "SWEDEN", u: "https://flagcdn.com/w640/se.png"},
    {n: "NORWAY", u: "https://flagcdn.com/w640/no.png"},
    {n: "DENMARK", u: "https://flagcdn.com/w640/dk.png"},
    {n: "FINLAND", u: "https://flagcdn.com/w640/fi.png"},
    {n: "IRELAND", u: "https://flagcdn.com/w640/ie.png"},
    {n: "GREECE", u: "https://flagcdn.com/w640/gr.png"},
    {n: "TURKEY", u: "https://flagcdn.com/w640/tr.png"},
    {n: "SWITZERLAND", u: "https://flagcdn.com/w640/ch.png"},
    {n: "AUSTRIA", u: "https://flagcdn.com/w640/at.png"},
    {n: "CZECH REPUBLIC", u: "https://flagcdn.com/w640/cz.png"},
    {n: "HUNGARY", u: "https://flagcdn.com/w640/hu.png"},
    {n: "ROMANIA", u: "https://flagcdn.com/w640/ro.png"},
    {n: "CROATIA", u: "https://flagcdn.com/w640/hr.png"},
    {n: "SERBIA", u: "https://flagcdn.com/w640/rs.png"},
    {n: "CHINA", u: "https://flagcdn.com/w640/cn.png"},
    {n: "JAPAN", u: "https://flagcdn.com/w640/jp.png"},
    {n: "SOUTH KOREA", u: "https://flagcdn.com/w640/kr.png"},
    {n: "NORTH KOREA", u: "https://flagcdn.com/w640/kp.png"},
    {n: "INDIA", u: "https://flagcdn.com/w640/in.png"},
    {n: "PAKISTAN", u: "https://flagcdn.com/w640/pk.png"},
    {n: "BANGLADESH", u: "https://flagcdn.com/w640/bd.png"},
    {n: "INDONESIA", u: "https://flagcdn.com/w640/id.png"},
    {n: "PHILIPPINES", u: "https://flagcdn.com/w640/ph.png"},
    {n: "VIETNAM", u: "https://flagcdn.com/w640/vn.png"},
    {n: "THAILAND", u: "https://flagcdn.com/w640/th.png"},
    {n: "MALAYSIA", u: "https://flagcdn.com/w640/my.png"},
    {n: "SINGAPORE", u: "https://flagcdn.com/w640/sg.png"},
    {n: "AUSTRALIA", u: "https://flagcdn.com/w640/au.png"},
    {n: "NEW ZEALAND", u: "https://flagcdn.com/w640/nz.png"},
    {n: "EGYPT", u: "https://flagcdn.com/w640/eg.png"},
    {n: "SOUTH AFRICA", u: "https://flagcdn.com/w640/za.png"},
    {n: "NIGERIA", u: "https://flagcdn.com/w640/ng.png"},
    {n: "KENYA", u: "https://flagcdn.com/w640/ke.png"},
    {n: "MOROCCO", u: "https://flagcdn.com/w640/ma.png"},
    {n: "ETHIOPIA", u: "https://flagcdn.com/w640/et.png"},
    {n: "GHANA", u: "https://flagcdn.com/w640/gh.png"},
    {n: "SAUDI ARABIA", u: "https://flagcdn.com/w640/sa.png"},
    {n: "IRAN", u: "https://flagcdn.com/w640/ir.png"},
    {n: "IRAQ", u: "https://flagcdn.com/w640/iq.png"},
    {n: "ISRAEL", u: "https://flagcdn.com/w640/il.png"},
    {n: "UAE", u: "https://flagcdn.com/w640/ae.png"},
    {n: "QATAR", u: "https://flagcdn.com/w640/qa.png"},
    {n: "JAMAICA", u: "https://flagcdn.com/w640/jm.png"},
    {n: "CUBA", u: "https://flagcdn.com/w640/cu.png"},
    {n: "PANAMA", u: "https://flagcdn.com/w640/pa.png"},
    {n: "COSTA RICA", u: "https://flagcdn.com/w640/cr.png"},
    {n: "VENEZUELA", u: "https://flagcdn.com/w640/ve.png"},
    {n: "ECUADOR", u: "https://flagcdn.com/w640/ec.png"},
    {n: "URUGUAY", u: "https://flagcdn.com/w640/uy.png"},
    {n: "ICELAND", u: "https://flagcdn.com/w640/is.png"},
    {n: "SCOTLAND", u: "https://flagcdn.com/w640/gb-sct.png"},
    {n: "WALES", u: "https://flagcdn.com/w640/gb-wls.png"},
    {n: "BULGARIA", u: "https://flagcdn.com/w640/bg.png"},
    {n: "ESTONIA", u: "https://flagcdn.com/w640/ee.png"},
    {n: "LATVIA", u: "https://flagcdn.com/w640/lv.png"},
    {n: "LITHUANIA", u: "https://flagcdn.com/w640/lt.png"},
    {n: "SLOVAKIA", u: "https://flagcdn.com/w640/sk.png"},
    {n: "SLOVENIA", u: "https://flagcdn.com/w640/si.png"},
    {n: "CYPRUS", u: "https://flagcdn.com/w640/cy.png"},
    {n: "MALTA", u: "https://flagcdn.com/w640/mt.png"},
    {n: "ALBANIA", u: "https://flagcdn.com/w640/al.png"},
    {n: "GEORGIA", u: "https://flagcdn.com/w640/ge.png"},
    {n: "ARMENIA", u: "https://flagcdn.com/w640/am.png"},
    {n: "AZERBAIJAN", u: "https://flagcdn.com/w640/az.png"},
    {n: "KAZAKHSTAN", u: "https://flagcdn.com/w640/kz.png"},
    {n: "UZBEKISTAN", u: "https://flagcdn.com/w640/uz.png"},
    {n: "MONGOLIA", u: "https://flagcdn.com/w640/mn.png"},
    {n: "NEPAL", u: "https://flagcdn.com/w640/np.png"},
    {n: "SRI LANKA", u: "https://flagcdn.com/w640/lk.png"},
    {n: "CAMBODIA", u: "https://flagcdn.com/w640/kh.png"},
    {n: "LAOS", u: "https://flagcdn.com/w640/la.png"},
    {n: "MYANMAR", u: "https://flagcdn.com/w640/mm.png"},
    {n: "FIJI", u: "https://flagcdn.com/w640/fj.png"},
    {n: "PAPUA NEW GUINEA", u: "https://flagcdn.com/w640/pg.png"},
    {n: "ALGERIA", u: "https://flagcdn.com/w640/dz.png"},
    {n: "TUNISIA", u: "https://flagcdn.com/w640/tn.png"},
    {n: "SENEGAL", u: "https://flagcdn.com/w640/sn.png"},
    {n: "IVORY COAST", u: "https://flagcdn.com/w640/ci.png"},
    {n: "CAMEROON", u: "https://flagcdn.com/w640/cm.png"},
    {n: "UGANDA", u: "https://flagcdn.com/w640/ug.png"},
    {n: "TANZANIA", u: "https://flagcdn.com/w640/tz.png"}
];