// Food — images in images/food/
const foodData = [
    // Tier 1 — Obvious (1–15)
    { n: "PIZZA", u: "../images/food/pizza.jpg" },
    { n: "BANANA", u: "../images/food/banana.jpg" },
    { n: "HAMBURGER", u: "../images/food/hamburger.jpg" },
    { n: "WATERMELON", u: "../images/food/watermelon.jpg" },
    { n: "SUSHI", u: "../images/food/sushi.jpg" },
    { n: "ICE CREAM", u: "../images/food/ice-cream.jpg" },
    { n: "TACO", u: "../images/food/taco.webp" },
    { n: "FRENCH FRIES", u: "../images/food/french-fries.jpg" },
    { n: "DONUT", u: "../images/food/donut.jpg" },
    { n: "PANCAKES", u: "../images/food/pancakes.jpg" },
    { n: "PRETZEL", u: "../images/food/pretzel.jpg" },
    { n: "AVOCADO", u: "../images/food/avocado.jpg" },
    { n: "STEAK", u: "../images/food/steak.jpg" },
    { n: "CROISSANT", u: "../images/food/croissant.png" },
    { n: "LOBSTER", u: "../images/food/lobster.jpg" },

    // Tier 2 — Familiar (16–30)
    { n: "BROCCOLI", u: "../images/food/broccoli.png" },
    { n: "WAFFLE", u: "../images/food/waffle.jpg" },
    { n: "SPAGHETTI", u: "../images/food/spaghetti.jpg" },
    { n: "CUPCAKE", u: "../images/food/cupcake.jpg" },
    { n: "SHRIMP", u: "../images/food/shrimp.jpg" },
    { n: "MANGO", u: "../images/food/mango.png" },
    { n: "BURRITO", u: "../images/food/burrito.jpg" },
    { n: "EDAMAME", u: "../images/food/edamame.jpg" },
    { n: "POMEGRANATE", u: "../images/food/pomegranate.jpg" },
    { n: "MACARON", u: "../images/food/macaron.jpg" },
    { n: "DUMPLING", u: "../images/food/dumpling.jpg" },
    { n: "ARTICHOKE", u: "../images/food/artichoke.jpg" },
    { n: "DRAGON FRUIT", u: "../images/food/dragon-fruit.jpg" },
    { n: "CANNOLI", u: "../images/food/cannoli.jpg" },
    { n: "RAMEN", u: "../images/food/ramen.jpg" },

    // Tier 3 — Knowledgeable (31–40)
    { n: "FALAFEL", u: "../images/food/falafel.jpg" },
    { n: "BAGUETTE", u: "../images/food/baguette.jpg" },
    { n: "BAKLAVA", u: "../images/food/baklava.jpg" },
    { n: "STAR FRUIT", u: "../images/food/star-fruit.jpg" },
    { n: "GNOCCHI", u: "../images/food/gnocchi.jpg" },
    { n: "CHURRO", u: "../images/food/churro.jpg" },
    { n: "LYCHEE", u: "../images/food/lychee.jpg" },
    { n: "PLANTAIN", u: "../images/food/plantain.jpg" },
    { n: "PERSIMMON", u: "../images/food/persimmon.jpg" },
    { n: "JACKFRUIT", u: "../images/food/jackfruit.webp" },

    // Tier 4 — Expert (41–60)
    { n: "TRUFFLE", u: "../images/food/truffle.jpg" },
    { n: "DURIAN", u: "../images/food/durian.jpg" },
    { n: "BEET", u: "../images/food/beet.jpg" },
    { n: "RAMBUTAN", u: "../images/food/rambutan.jpg" },
    { n: "ROMANESCO", u: "../images/food/romanesco.jpg" },
    { n: "TAMARIND", u: "../images/food/tamarind.jpg" },
    { n: "TEMPEH", u: "../images/food/tempeh.jpg" },
    { n: "CELERIAC", u: "../images/food/celeriac.jpg" },
    { n: "KOHLRABI", u: "../images/food/kohlrabi.jpg" },
    { n: "TOMATILLO", u: "../images/food/tomatillo.jpg" },
    { n: "JICAMA", u: "../images/food/jicama.jpg" },
    { n: "DAIKON", u: "../images/food/daikon.png" },
    { n: "GALANGAL", u: "../images/food/galangal.png" },
    { n: "CHAYOTE", u: "../images/food/chayote.png" },
    { n: "YUZU", u: "../images/food/yuzu.jpg" },
    { n: "FEIJOA", u: "../images/food/feijoa.jpg" },
    { n: "CHERIMOYA", u: "../images/food/cherimoya.jpg" },
    { n: "ENDIVE", u: "../images/food/endive.jpg" },
    { n: "CROQUEMBOUCHE", u: "../images/food/croquembouche.jpg" },
    { n: "LONGAN", u: "../images/food/longan.webp" },

    // ── BACKUPS (61–70) ────────────────
    { n: "WONTON", u: "../images/food/wonton.jpg" },
    { n: "BRIOCHE", u: "../images/food/brioche.jpg" },
    { n: "PASSION FRUIT", u: "../images/food/passion-fruit.jpg" },
    { n: "KIMCHI", u: "../images/food/kimchi.jpg" },
    { n: "TIRAMISU", u: "../images/food/tiramisu.jpg" },
    { n: "FIG", u: "../images/food/fig.jpg" },
    { n: "PAD THAI", u: "../images/food/pad-thai.jpg" },
    { n: "ÉCLAIR", u: "../images/food/eclair.jpg" },
    { n: "OKRA", u: "../images/food/okra.jpg" },
    { n: "KIWI", u: "../images/food/kiwi.jpg" },
];
if (typeof window !== 'undefined') window.foodData = foodData;
