// Food — images in images/food/
const foodData = [
    // Tier 1 — Obvious (1–15)
    { n: "PIZZA", u: "../images/food/pizza.webp" },
    { n: "BANANA", u: "../images/food/banana.webp" },
    { n: "HAMBURGER", u: "../images/food/hamburger.webp" },
    { n: "WATERMELON", u: "../images/food/watermelon.webp" },
    { n: "SUSHI", u: "../images/food/sushi.webp" },
    { n: "ICE CREAM", u: "../images/food/ice-cream.webp" },
    { n: "TACO", u: "../images/food/taco.webp" },
    { n: "FRENCH FRIES", u: "../images/food/french-fries.webp" },
    { n: "DONUT", u: "../images/food/donut.webp" },
    { n: "PANCAKES", u: "../images/food/pancakes.webp" },
    { n: "PRETZEL", u: "../images/food/pretzel.webp" },
    { n: "AVOCADO", u: "../images/food/avocado.webp" },
    { n: "STEAK", u: "../images/food/steak.webp" },
    { n: "CROISSANT", u: "../images/food/croissant.webp" },
    { n: "LOBSTER", u: "../images/food/lobster.webp" },

    // Tier 2 — Familiar (16–30)
    { n: "BROCCOLI", u: "../images/food/broccoli.webp" },
    { n: "WAFFLE", u: "../images/food/waffle.webp" },
    { n: "SPAGHETTI", u: "../images/food/spaghetti.webp" },
    { n: "CUPCAKE", u: "../images/food/cupcake.webp" },
    { n: "SHRIMP", u: "../images/food/shrimp.webp" },
    { n: "MANGO", u: "../images/food/mango.webp" },
    { n: "BURRITO", u: "../images/food/burrito.webp" },
    { n: "EDAMAME", u: "../images/food/edamame.webp" },
    { n: "POMEGRANATE", u: "../images/food/pomegranate.webp" },
    { n: "MACARON", u: "../images/food/macaron.webp" },
    { n: "DUMPLING", u: "../images/food/dumpling.webp" },
    { n: "ARTICHOKE", u: "../images/food/artichoke.webp" },
    { n: "DRAGON FRUIT", u: "../images/food/dragon-fruit.webp" },
    { n: "CANNOLI", u: "../images/food/cannoli.webp" },
    { n: "RAMEN", u: "../images/food/ramen.webp" },

    // Tier 3 — Knowledgeable (31–40)
    { n: "FALAFEL", u: "../images/food/falafel.webp" },
    { n: "BAGUETTE", u: "../images/food/baguette.webp" },
    { n: "BAKLAVA", u: "../images/food/baklava.webp" },
    { n: "STAR FRUIT", u: "../images/food/star-fruit.webp" },
    { n: "GNOCCHI", u: "../images/food/gnocchi.webp" },
    { n: "CHURRO", u: "../images/food/churro.webp" },
    { n: "LYCHEE", u: "../images/food/lychee.webp" },
    { n: "PLANTAIN", u: "../images/food/plantain.webp" },
    { n: "PERSIMMON", u: "../images/food/persimmon.webp" },
    { n: "JACKFRUIT", u: "../images/food/jackfruit.webp" },

    // Tier 4 — Expert (41–60)
    { n: "TRUFFLE", u: "../images/food/truffle.webp" },
    { n: "DURIAN", u: "../images/food/durian.webp" },
    { n: "BEET", u: "../images/food/beet.webp" },
    { n: "RAMBUTAN", u: "../images/food/rambutan.webp" },
    { n: "ROMANESCO", u: "../images/food/romanesco.webp" },
    { n: "TAMARIND", u: "../images/food/tamarind.webp" },
    { n: "TEMPEH", u: "../images/food/tempeh.webp" },
    { n: "CELERIAC", u: "../images/food/celeriac.webp" },
    { n: "KOHLRABI", u: "../images/food/kohlrabi.webp" },
    { n: "TOMATILLO", u: "../images/food/tomatillo.webp" },
    { n: "JICAMA", u: "../images/food/jicama.webp" },
    { n: "DAIKON", u: "../images/food/daikon.webp" },
    { n: "GALANGAL", u: "../images/food/galangal.webp" },
    { n: "CHAYOTE", u: "../images/food/chayote.webp" },
    { n: "YUZU", u: "../images/food/yuzu.webp" },
    { n: "FEIJOA", u: "../images/food/feijoa.webp" },
    { n: "CHERIMOYA", u: "../images/food/cherimoya.webp" },
    { n: "ENDIVE", u: "../images/food/endive.webp" },
    { n: "CROQUEMBOUCHE", u: "../images/food/croquembouche.webp" },
    { n: "LONGAN", u: "../images/food/longan.webp" },

    // ── BACKUPS (61–70) ────────────────
    { n: "WONTON", u: "../images/food/wonton.webp" },
    { n: "BRIOCHE", u: "../images/food/brioche.webp" },
    { n: "PASSION FRUIT", u: "../images/food/passion-fruit.webp" },
    { n: "KIMCHI", u: "../images/food/kimchi.webp" },
    { n: "TIRAMISU", u: "../images/food/tiramisu.webp" },
    { n: "FIG", u: "../images/food/fig.webp" },
    { n: "PAD THAI", u: "../images/food/pad-thai.webp" },
    { n: "ÉCLAIR", u: "../images/food/eclair.webp" },
    { n: "OKRA", u: "../images/food/okra.webp" },
    { n: "KIWI", u: "../images/food/kiwi.webp" },
];
if (typeof window !== 'undefined') window.foodData = foodData;
