// Local images in images/hockey/ — extensions match folder
const hockeyData = [
    // Interleaved: equipment, logos, players, other — no 2+ same type in a row (except equipment)
    { n: "HOCKEY STICK", u: "../images/hockey/hockey-stick.jpeg" },
    { n: "PUCK", u: "../images/hockey/puck.webp" },
    { n: "HELMET", u: "../images/hockey/helmet.jpg" },
    { n: "JERSEY", u: "../images/hockey/jersey.webp" },
    { n: "SKATES", u: "../images/hockey/skates.jpg" },
    { n: "STANLEY CUP", u: "../images/hockey/stanley-cup.jpeg" },
    { n: "MONTREAL CANADIENS", u: "../images/hockey/canadiens-logo.jpg" },
    { n: "WAYNE GRETZKY", u: "../images/hockey/gretzky.jpeg" },
    { n: "WATER BOTTLE", u: "../images/hockey/water-bottle.jpg" },
    { n: "TORONTO MAPLE LEAFS", u: "../images/hockey/maple-leafs-logo.png" },
    { n: "BOSTON BRUINS", u: "../images/hockey/bruins-logo.png" },
    { n: "GOALIE MASK", u: "../images/hockey/goalie-mask.jpg" },
    { n: "MARIO LEMIEUX", u: "../images/hockey/lemieux.jpg" },
    { n: "GLOVES", u: "../images/hockey/gloves.jpg" },
    { n: "CHICAGO BLACKHAWKS", u: "../images/hockey/blackhawks-logo.jpg" },
    { n: "SHOULDER PADS", u: "../images/hockey/shoulder-pads.jpg" },
    { n: "ZAMBONI", u: "../images/hockey/zamboni.webp" },
    { n: "DETROIT RED WINGS", u: "../images/hockey/red-wings-logo.jpg" },
    { n: "GOAL NET", u: "../images/hockey/goal-net.jpg" },
    { n: "BOBBY ORR", u: "../images/hockey/orr.jpg" },
    { n: "NEW YORK RANGERS", u: "../images/hockey/rangers-logo.jpg" },
    { n: "SIDNEY CROSBY", u: "../images/hockey/crosby.webp" },
    { n: "PITTSBURGH PENGUINS", u: "../images/hockey/penguins-logo.png" },
    { n: "SHIN GUARDS", u: "../images/hockey/shin-guards.jpg" },
    { n: "ELBOW PADS", u: "../images/hockey/elbow-pads.jpg" },
    { n: "EDMONTON OILERS", u: "../images/hockey/oilers-logo.jpg" },
    { n: "HOCKEY BAG", u: "../images/hockey/hockey-bag.jpg" },
    { n: "SKATE BLADE", u: "../images/hockey/skate-blade.webp" },
    { n: "GOAL LIGHT", u: "../images/hockey/goal-light.webp" },
    { n: "BLOCKER", u: "../images/hockey/blocker.webp" },
    { n: "CATCHING GLOVE", u: "../images/hockey/catching-glove.webp" },
    { n: "GOALIE STICK", u: "../images/hockey/goalie-stick.webp" },
    { n: "HOCKEY SOCK", u: "../images/hockey/hockey-sock.jpg" },
    { n: "VISOR", u: "../images/hockey/visor.png" },
    { n: "STICK TAPE", u: "../images/hockey/stick-tape.webp" },
    { n: "RINK", u: "../images/hockey/rink.jpg" },
    { n: "BENCH", u: "../images/hockey/bench.jpg" },
    { n: "REFEREE", u: "../images/hockey/referee.webp" }
];
if (typeof window !== 'undefined') window.hockeyData = hockeyData;
