/**
 * Central Category Registry — single source of truth.
 * To add a new category, just append one entry here.
 *
 * key    — internal identifier (lowercase, no spaces)
 * label  — display name shown in UI
 * script — filename inside categories/ folder
 * global — the window.* variable name the script creates
 */
const CATEGORY_REGISTRY = [
    // REAL DEAL
    { key: 'niche-survivor-players', label: 'Niche Survivor Players', emoji: '🏝️', script: 'niche-survivor-players.js', global: 'nicheSurvivorPlayersData', tier: 'Gible Verified' },
    { key: '2000s-artists', label: '2000s Artists', emoji: '🎤', script: '2000s-artists.js', global: 'artists2000sData', tier: 'Gible Verified' },
    { key: 'anime', label: 'Anime', emoji: '⛩️', script: 'anime.js', global: 'animeData', tier: 'Gible Verified' },
    { key: 'best-picture', label: 'Best Picture', emoji: '🏆', script: 'best-picture.js', global: 'bestPictureData', tier: 'Gible Verified' },
    { key: 'birds', label: 'Birds', emoji: '🐦', script: 'birds.js', global: 'birdsData', tier: 'Gible Verified' },
    { key: 'board-games', label: 'Board Games', emoji: '🎲', script: 'board-games.js', global: 'boardGamesData', tier: 'Gible Verified' },
    { key: 'capital-cities', label: 'Capital Cities', emoji: '🏛️', script: 'capital-cities.js', global: 'capitalCitiesData', tier: 'Gible Verified' },
    { key: 'card-games', label: 'Card Games', emoji: '🃏', script: 'card-games.js', global: 'cardGamesData', tier: 'Gible Verified' },
    { key: 'college-logos', label: 'College Logos', emoji: '🎓', script: 'college-logos.js', global: 'collegeLogosData', tier: 'Gible Verified' },
    { key: 'disney-movies', label: 'Disney Movies', emoji: '🏰', script: 'disney-movies.js', global: 'disneyMoviesData', tier: 'Gible Verified' },
    { key: 'dolls', label: 'Dolls', emoji: '🎎', script: 'dolls.js', global: 'dollsData', tier: 'Gible Verified' },
    { key: 'f1', label: 'F1', emoji: '🏎️', script: 'f1.js', global: 'f1Data', tier: 'Gible Verified' },
    { key: 'fishing', label: 'Fishing', emoji: '🎣', script: 'fishing.js', global: 'fishingData', tier: 'Gible Verified' },
    { key: 'football', label: 'Football', emoji: '🏈', script: 'football.js', global: 'footballData', tier: 'Gible Verified' },
    { key: 'soccer', label: 'Soccer', emoji: '⚽', script: 'soccer.js', global: 'soccerData', tier: 'Gible Verified' },
    { key: 'gameshows', label: 'Gameshows', emoji: '🎰', script: 'gameshows.js', global: 'gameshowsData', tier: 'Gible Verified' },
    { key: 'girl-groups', label: 'Girl Groups', emoji: '👩‍🎤', script: 'girl-groups.js', global: 'girlGroupsData', tier: 'Gible Verified' },
    { key: 'golf', label: 'Golf', emoji: '⛳', script: 'golf.js', global: 'golfData', tier: 'Gible Verified' },
    { key: 'horror-movies', label: 'Horror Movies', emoji: '🔪', script: 'horror-movies.js', global: 'horrorMoviesData', tier: 'Gible Verified' },
    { key: 'indiana-university', label: 'Indiana University', emoji: '🔱', script: 'indiana-university.js', global: 'indianaUniversityData', tier: 'Gible Verified' },
    { key: 'instruments', label: 'Instruments', emoji: '🎵', script: 'instruments.js', global: 'instrumentsData', tier: 'Gible Verified' },
    { key: 'marching-band', label: 'Marching Band', emoji: '🥁', script: 'marching-band.js', global: 'marchingBandData', tier: 'Gible Verified' },
    { key: 'minecraft', label: 'Minecraft', emoji: '⛏️', script: 'minecraft.js', global: 'minecraftData', tier: 'Gible Verified' },
    { key: 'fortnite-collabs', label: 'Fortnite Collabs', emoji: '🎮', script: 'fortnite-collabs.js', global: 'fortniteCollabsData', tier: 'Gible Verified' },
    { key: 'queer-movies-tv', label: 'Queer Movies & TV', emoji: '🏳️‍🌈', script: 'queer-movies-tv.js', global: 'queerMoviesTvData', tier: 'Gible Verified' },
    { key: 'retro-video-games', label: 'Retro Video Games', emoji: '👾', script: 'retro-video-games.js', global: 'retroVideoGamesData', tier: 'Gible Verified' },
    { key: 'sports-logos', label: 'Sports Logos', emoji: '🏅', script: 'sports-logos.js', global: 'sportsLogosData', tier: 'Gible Verified' },
    { key: 'state-flags', label: 'State Flags', emoji: '🇺🇸', script: 'state-flags.js', global: 'stateFlagsData', tier: 'Gible Verified' },
    { key: 'strange-animals', label: 'Strange Animals', emoji: '🦠', script: 'strange-animals.js', global: 'strangeAnimalsData', tier: 'Gible Verified' },
    { key: 'taylor-swift', label: 'Taylor Swift', emoji: '🎶', script: 'taylor-swift.js', global: 'taylorSwiftData', tier: 'Gible Verified' },
    { key: 'track-and-field', label: 'Track & Field', emoji: '🏃', script: 'track-and-field.js', global: 'trackAndFieldData', tier: 'Gible Verified' },
    { key: 'visual-novels', label: 'Visual Novels', emoji: '📖', script: 'visual-novels.js', global: 'visualNovelsData', tier: 'Gible Verified' },

    // EXAMPLES
    { key: 'flags', label: 'Flags', emoji: '🏁', script: 'flags.js', global: 'flagData', tier: 'Gible Verified' },
    { key: 'hockey', label: 'Hockey', emoji: '🏒', script: 'hockey.js', global: 'hockeyData', tier: 'Gible Verified' },
    { key: 'dogs', label: 'Dogs', emoji: '🐕', script: 'dogs.js', global: 'dogData', tier: 'Gible Verified' },
    { key: 'attractive-men', label: 'Attractive Men', emoji: '💪', script: 'attractive-men.js', global: 'attractiveMenData', tier: 'Gible Verified' },
    { key: 'math', label: 'Math', emoji: '➗', script: 'math.js', global: 'mathData', tier: 'Gible Verified' },
    { key: 'pokemon', label: 'Pokemon', emoji: '⚡', script: 'pokemon.js', global: 'pokemonData', tier: 'Gible Verified' },

    // TIEBREAK
    { key: 'orange-things', label: 'Orange Things', emoji: '🟠', script: 'orange-things.js', global: 'orangeThingsData', tier: 'Gible Verified' },
    { key: 'baby-animals', label: 'Baby Animals', emoji: '🐣', script: 'baby-animals.js', global: 'babyAnimalsData', tier: 'Gible Verified' },
    { key: 'furniture', label: 'Furniture', emoji: '🪑', script: 'furniture.js', global: 'furnitureData', tier: 'Gible Verified' },

    // EXTRAS
    { key: 'mega', label: 'Mega Category', emoji: '🌟', script: 'mega.js', global: 'megaData', tier: 'Gible Verified' },
    { key: 'mega-filtered', label: 'Mega-Filtered', emoji: '✨', script: 'mega-filtered.js', global: 'megaFilteredData', tier: 'Gible Verified' },
    { key: 'religion', label: 'Religion', emoji: '⛪', script: 'religion.js', global: 'religionData', tier: 'Gible Verified' },
    { key: 'mobile-apps', label: 'Mobile Apps', emoji: '📱', script: 'mobile-apps.js', global: 'mobileAppsData', tier: 'Gible Verified' },
    { key: 'the-90s', label: 'The 90s', emoji: '📼', script: 'the-90s.js', global: 'the90sData', tier: 'Gible Verified' },
    { key: 'famous-books', label: 'Famous Books', emoji: '📚', script: 'famous-books.js', global: 'famousBooksData', tier: 'Gible Verified' },
    { key: 'food', label: 'Food', emoji: '🍕', script: 'food.js', global: 'foodData', tier: 'Gible Verified' },
    { key: 'historic-events', label: 'Historic Events', emoji: '📜', script: 'historic-events.js', global: 'historicEventsData', tier: 'Gible Verified' },
    { key: 'nintendo', label: 'Nintendo', emoji: '🎮', script: 'nintendo.js', global: 'nintendoData', tier: 'Gible Verified' },
    { key: 'flowers', label: 'Flowers', emoji: '🌻', script: 'flowers.js', global: 'flowersData', tier: 'Gible Verified' },
    { key: 'pokemon-everything', label: 'Pokemon (General)', emoji: '🔴', script: 'pokemon-everything.js', global: 'pokemonEverythingData', tier: 'Gible Verified' },
    { key: 'world-leaders', label: 'World Leaders', emoji: '🌍', script: 'world-leaders.js', global: 'worldLeadersData', tier: 'Gible Verified' },

    // PPTGAMES
    { key: 'ppt-2000s-pop-songs', label: '2000s Pop Songs', emoji: '🎵', script: 'pptgames/ppt-2000s-pop-songs.js', global: 'ppt2000sPopSongs', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-2010s-pop-songs', label: '2010s Pop Songs', emoji: '🎶', script: 'pptgames/ppt-2010s-pop-songs.js', global: 'ppt2010sPopSongs', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-action-movies', label: 'Action Movies', emoji: '💥', script: 'pptgames/ppt-action-movies.js', global: 'pptActionMovies', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-algebra', label: 'Algebra', emoji: '📐', script: 'pptgames/ppt-algebra.js', global: 'pptAlgebra', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-anime-characters', label: 'Anime Characters', emoji: '⛩️', script: 'pptgames/ppt-anime-characters.js', global: 'pptAnimeCharacters', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-anime-movies-series', label: 'Anime Movies & Series', emoji: '🎌', script: 'pptgames/ppt-anime-movies-series.js', global: 'pptAnimeMoviesSeries', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-apple-products', label: 'Apple Products', emoji: '🍎', script: 'pptgames/ppt-apple-products.js', global: 'pptAppleProducts', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-babies', label: 'Babies', emoji: '👶', script: 'pptgames/ppt-babies.js', global: 'pptBabies', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-baseball', label: 'Baseball', emoji: '⚾', script: 'pptgames/ppt-baseball.js', global: 'pptBaseball', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-basketball', label: 'Basketball', emoji: '🏀', script: 'pptgames/ppt-basketball.js', global: 'pptBasketball', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-basketball-celebrities', label: 'Basketball Celebrities', emoji: '🏀', script: 'pptgames/ppt-basketball-celebrities.js', global: 'pptBasketballCelebrities', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-bathroom-items', label: 'Bathroom Items', emoji: '🚿', script: 'pptgames/ppt-bathroom-items.js', global: 'pptBathroomItems', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-beauty-products', label: 'Beauty Products', emoji: '💄', script: 'pptgames/ppt-beauty-products.js', global: 'pptBeautyProducts', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-bible-books', label: 'Bible Books', emoji: '📖', script: 'pptgames/ppt-bible-books.js', global: 'pptBibleBooks', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-bible-characters', label: 'Bible Characters', emoji: '✝️', script: 'pptgames/ppt-bible-characters.js', global: 'pptBibleCharacters', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-bible-objects', label: 'Bible Objects', emoji: '🕍', script: 'pptgames/ppt-bible-objects.js', global: 'pptBibleObjects', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-bible-parables', label: 'Bible Parables', emoji: '📜', script: 'pptgames/ppt-bible-parables.js', global: 'pptBibleParables', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-bible-quotes', label: 'Bible Quotes', emoji: '✝️', script: 'pptgames/ppt-bible-quotes.js', global: 'pptBibleQuotes', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-bible-verses', label: 'Bible Verses', emoji: '📖', script: 'pptgames/ppt-bible-verses.js', global: 'pptBibleVerses', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-biology', label: 'Biology', emoji: '🔬', script: 'pptgames/ppt-biology.js', global: 'pptBiology', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-birds', label: 'Birds (PPT)', emoji: '🐦', script: 'pptgames/ppt-birds.js', global: 'pptBirds', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-board-games', label: 'Board Games (PPT)', emoji: '🎲', script: 'pptgames/ppt-board-games.js', global: 'pptBoardGames', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-boba', label: 'Boba', emoji: '🧋', script: 'pptgames/ppt-boba.js', global: 'pptBoba', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-body-parts', label: 'Body Parts', emoji: '🦴', script: 'pptgames/ppt-body-parts.js', global: 'pptBodyParts', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-brainrot', label: 'Brainrot', emoji: '💀', script: 'pptgames/ppt-brainrot.js', global: 'pptBrainrot', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-brand-mascots', label: 'Brand Mascots', emoji: '🎭', script: 'pptgames/ppt-brand-mascots.js', global: 'pptBrandMascots', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-broadway-musicals', label: 'Broadway Musicals', emoji: '🎭', script: 'pptgames/ppt-broadway-musicals.js', global: 'pptBroadwayMusicals', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-bugs', label: 'Bugs', emoji: '🐛', script: 'pptgames/ppt-bugs.js', global: 'pptBugs', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-candy-brands', label: 'Candy Brands', emoji: '🍬', script: 'pptgames/ppt-candy-brands.js', global: 'pptCandyBrands', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-car-brands', label: 'Car Brands', emoji: '🚗', script: 'pptgames/ppt-car-brands.js', global: 'pptCarBrands', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-car-parts-basic', label: 'Car Parts (Basic)', emoji: '⚙️', script: 'pptgames/ppt-car-parts-basic.js', global: 'pptCarPartsBasic', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-cartoon-network', label: 'Cartoon Network', emoji: '📺', script: 'pptgames/ppt-cartoon-network.js', global: 'pptCartoonNetwork', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-cereal', label: 'Cereal', emoji: '🥣', script: 'pptgames/ppt-cereal.js', global: 'pptCereal', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-chemistry-elements', label: 'Chemistry Elements', emoji: '🧪', script: 'pptgames/ppt-chemistry-elements.js', global: 'pptChemistryElements', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-chinese-language', label: 'Chinese Language', emoji: '🇨🇳', script: 'pptgames/ppt-chinese-language.js', global: 'pptChineseLanguage', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-christmas', label: 'Christmas', emoji: '🎄', script: 'pptgames/ppt-christmas.js', global: 'pptChristmas', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-church', label: 'Church', emoji: '⛪', script: 'pptgames/ppt-church.js', global: 'pptChurch', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-classical-music', label: 'Classical Music', emoji: '🎻', script: 'pptgames/ppt-classical-music.js', global: 'pptClassicalMusic', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-clothing-brands', label: 'Clothing Brands', emoji: '👕', script: 'pptgames/ppt-clothing-brands.js', global: 'pptClothingBrands', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-colors', label: 'Colors', emoji: '🎨', script: 'pptgames/ppt-colors.js', global: 'pptColors', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-computer-parts', label: 'Computer Parts', emoji: '💻', script: 'pptgames/ppt-computer-parts.js', global: 'pptComputerParts', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-dc-comic-characters', label: 'DC Comic Characters', emoji: '🦸‍♂️', script: 'pptgames/ppt-dc-comic-characters.js', global: 'pptDcComicCharacters', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-desserts', label: 'Desserts', emoji: '🍰', script: 'pptgames/ppt-desserts.js', global: 'pptDesserts', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-disney-characters', label: 'Disney Characters', emoji: '🐭', script: 'pptgames/ppt-disney-characters.js', global: 'pptDisneyCharacters', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-disney-movies', label: 'Disney Movies (PPT)', emoji: '🏰', script: 'pptgames/ppt-disney-movies.js', global: 'pptDisneyMovies', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-disney-songs', label: 'Disney Songs', emoji: '🎤', script: 'pptgames/ppt-disney-songs.js', global: 'pptDisneySongs', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-dog-breeds', label: 'Dog Breeds', emoji: '🐕', script: 'pptgames/ppt-dog-breeds.js', global: 'pptDogBreeds', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-easter', label: 'Easter', emoji: '🥚', script: 'pptgames/ppt-easter.js', global: 'pptEaster', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-ethnic-foods', label: 'Ethnic Foods', emoji: '🍱', script: 'pptgames/ppt-ethnic-foods.js', global: 'pptEthnicFoods', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-famous-landmarks', label: 'Famous Landmarks', emoji: '🗿', script: 'pptgames/ppt-famous-landmarks.js', global: 'pptFamousLandmarks', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-famous-quotes', label: 'Famous Quotes', emoji: '💬', script: 'pptgames/ppt-famous-quotes.js', global: 'pptFamousQuotes', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-famous-youtubers', label: 'Famous YouTubers', emoji: '🤳', script: 'pptgames/ppt-famous-youtubers.js', global: 'pptFamousYoutubers', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-fast-food-chains', label: 'Fast Food Chains', emoji: '🍟', script: 'pptgames/ppt-fast-food-chains.js', global: 'pptFastFoodChains', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-fitness', label: 'Fitness', emoji: '🏋️‍♀️', script: 'pptgames/ppt-fitness.js', global: 'pptFitness', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-flowers', label: 'Flowers', emoji: '🌻', script: 'pptgames/ppt-flowers.js', global: 'pptFlowers', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-football', label: 'Football (PPT)', emoji: '🏈', script: 'pptgames/ppt-football.js', global: 'pptFootball', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-footwear', label: 'Footwear', emoji: '👟', script: 'pptgames/ppt-footwear.js', global: 'pptFootwear', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-foreign-languages', label: 'Foreign Languages', emoji: '🗣️', script: 'pptgames/ppt-foreign-languages.js', global: 'pptForeignLanguages', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-french-language', label: 'French Language', emoji: '🇫🇷', script: 'pptgames/ppt-french-language.js', global: 'pptFrenchLanguage', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-fruit', label: 'Fruit', emoji: '🍎', script: 'pptgames/ppt-fruit.js', global: 'pptFruit', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-geometry', label: 'Geometry', emoji: '📐', script: 'pptgames/ppt-geometry.js', global: 'pptGeometry', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-german-language', label: 'German Language', emoji: '🇩🇪', script: 'pptgames/ppt-german-language.js', global: 'pptGermanLanguage', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-high-school-subjects', label: 'High School Subjects', emoji: '🏫', script: 'pptgames/ppt-high-school-subjects.js', global: 'pptHighSchoolSubjects', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-household-appliances', label: 'Household Appliances', emoji: '🔌', script: 'pptgames/ppt-household-appliances.js', global: 'pptHouseholdAppliances', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-internet-logos', label: 'Internet Logos', emoji: '🌐', script: 'pptgames/ppt-internet-logos.js', global: 'pptInternetLogos', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-internet-websites', label: 'Internet Websites', emoji: '🌐', script: 'pptgames/ppt-internet-websites.js', global: 'pptInternetWebsites', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-japanese-language', label: 'Japanese Language', emoji: '🇯🇵', script: 'pptgames/ppt-japanese-language.js', global: 'pptJapaneseLanguage', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-k-pop-celebrities', label: 'K-Pop Celebrities', emoji: '🎤', script: 'pptgames/ppt-k-pop-celebrities.js', global: 'pptKpopCelebrities', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-k-pop-songs', label: 'K-Pop Songs', emoji: '🎵', script: 'pptgames/ppt-k-pop-songs.js', global: 'pptKpopSongs', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-kitchen-tools', label: 'Kitchen Tools', emoji: '🍳', script: 'pptgames/ppt-kitchen-tools.js', global: 'pptKitchenTools', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-korean-language', label: 'Korean Language', emoji: '🇰🇷', script: 'pptgames/ppt-korean-language.js', global: 'pptKoreanLanguage', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-lego', label: 'LEGO', emoji: '🧱', script: 'pptgames/ppt-lego.js', global: 'pptLego', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-literature', label: 'Literature', emoji: '📚', script: 'pptgames/ppt-literature.js', global: 'pptLiterature', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-mlb-teams', label: 'MLB Teams', emoji: '⚾', script: 'pptgames/ppt-mlb-teams.js', global: 'pptMlbTeams', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-marvel-superheroes', label: 'Marvel Superheroes', emoji: '🕷️', script: 'pptgames/ppt-marvel-superheroes.js', global: 'pptMarvelSuperheroes', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-mcdonalds', label: 'McDonalds', emoji: '🍔', script: 'pptgames/ppt-mcdonalds.js', global: 'pptMcdonalds', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-memes', label: 'Memes (PPT)', emoji: '😂', script: 'pptgames/ppt-memes.js', global: 'pptMemes', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-military', label: 'Military', emoji: '🎖️', script: 'pptgames/ppt-military.js', global: 'pptMilitary', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-minecraft', label: 'Minecraft (PPT)', emoji: '⛏️', script: 'pptgames/ppt-minecraft.js', global: 'pptMinecraft', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-mobile-games', label: 'Mobile Games', emoji: '📱', script: 'pptgames/ppt-mobile-games.js', global: 'pptMobileGames', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-movie-characters', label: 'Movie Characters', emoji: '🎬', script: 'pptgames/ppt-movie-characters.js', global: 'pptMovieCharacters', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-movie-quotes', label: 'Movie Quotes', emoji: '🎥', script: 'pptgames/ppt-movie-quotes.js', global: 'pptMovieQuotes', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-movie-stars-all-time', label: 'Movie Stars (All-Time)', emoji: '🌟', script: 'pptgames/ppt-movie-stars-all-time.js', global: 'pptMovieStarsAlltime', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-movie-stars-modern', label: 'Movie Stars (Modern)', emoji: '🎬', script: 'pptgames/ppt-movie-stars-modern.js', global: 'pptMovieStarsModern', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-movie-titles', label: 'Movie Titles', emoji: '🎦', script: 'pptgames/ppt-movie-titles.js', global: 'pptMovieTitles', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-movie-villains', label: 'Movie Villains', emoji: '😈', script: 'pptgames/ppt-movie-villains.js', global: 'pptMovieVillains', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-music-artists-all-time', label: 'Music Artists (All-Time)', emoji: '🎤', script: 'pptgames/ppt-music-artists-all-time.js', global: 'pptMusicArtistsAlltime', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-music-artists-modern', label: 'Music Artists (Modern)', emoji: '🎵', script: 'pptgames/ppt-music-artists-modern.js', global: 'pptMusicArtistsModern', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-musical-instruments', label: 'Musical Instruments', emoji: '🎺', script: 'pptgames/ppt-musical-instruments.js', global: 'pptMusicalInstruments', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-musical-key-signatures', label: 'Musical Key Signatures', emoji: '🎼', script: 'pptgames/ppt-musical-key-signatures.js', global: 'pptMusicalKeySignatures', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-musical-notes', label: 'Musical Notes', emoji: '🎵', script: 'pptgames/ppt-musical-notes.js', global: 'pptMusicalNotes', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-nba-teams', label: 'NBA Teams', emoji: '🏀', script: 'pptgames/ppt-nba-teams.js', global: 'pptNbaTeams', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-nfl-teams', label: 'NFL Teams', emoji: '🏈', script: 'pptgames/ppt-nfl-teams.js', global: 'pptNflTeams', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-nintendo-characters', label: 'Nintendo Characters', emoji: '🎮', script: 'pptgames/ppt-nintendo-characters.js', global: 'pptNintendoCharacters', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-numbers-in-words', label: 'Numbers In Words', emoji: '🔢', script: 'pptgames/ppt-numbers-in-words.js', global: 'pptNumbersInWords', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-ocean-animals', label: 'Ocean Animals', emoji: '🐙', script: 'pptgames/ppt-ocean-animals.js', global: 'pptOceanAnimals', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-olympic-sports', label: 'Olympic Sports', emoji: '🏅', script: 'pptgames/ppt-olympic-sports.js', global: 'pptOlympicSports', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-online-acronyms', label: 'Online Acronyms', emoji: '💬', script: 'pptgames/ppt-online-acronyms.js', global: 'pptOnlineAcronyms', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-pets', label: 'Pets', emoji: '🐾', script: 'pptgames/ppt-pets.js', global: 'pptPets', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-piano', label: 'Piano', emoji: '🎹', script: 'pptgames/ppt-piano.js', global: 'pptPiano', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-pixar-movie-characters', label: 'Pixar Movie Characters', emoji: '🎬', script: 'pptgames/ppt-pixar-movie-characters.js', global: 'pptPixarMovieCharacters', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-pizza-toppings', label: 'Pizza Toppings', emoji: '🍕', script: 'pptgames/ppt-pizza-toppings.js', global: 'pptPizzaToppings', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-praise-worship', label: 'Praise & Worship', emoji: '🙏', script: 'pptgames/ppt-praise-worship.js', global: 'pptPraiseWorship', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-pro-wrestling', label: 'Pro Wrestling', emoji: '🤼', script: 'pptgames/ppt-pro-wrestling.js', global: 'pptProWrestling', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-reading-backwards', label: 'Reading Backwards', emoji: '🔄', script: 'pptgames/ppt-reading-backwards.js', global: 'pptReadingBackwards', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-retro-gadgets', label: 'Retro Gadgets', emoji: '📻', script: 'pptgames/ppt-retro-gadgets.js', global: 'pptRetroGadgets', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-road-signs', label: 'Road Signs', emoji: '🚦', script: 'pptgames/ppt-road-signs.js', global: 'pptRoadSigns', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-roblox', label: 'Roblox', emoji: '🧱', script: 'pptgames/ppt-roblox.js', global: 'pptRoblox', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-school-supplies', label: 'School Supplies', emoji: '✏️', script: 'pptgames/ppt-school-supplies.js', global: 'pptSchoolSupplies', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-shakespeare', label: 'Shakespeare', emoji: '📜', script: 'pptgames/ppt-shakespeare.js', global: 'pptShakespeare', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-snack-brands', label: 'Snack Brands', emoji: '🍿', script: 'pptgames/ppt-snack-brands.js', global: 'pptSnackBrands', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-soccer-stars', label: 'Soccer Stars', emoji: '⚽', script: 'pptgames/ppt-soccer-stars.js', global: 'pptSoccerStars', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-soda-brands', label: 'Soda Brands', emoji: '🥤', script: 'pptgames/ppt-soda-brands.js', global: 'pptSodaBrands', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-spanish-language', label: 'Spanish Language', emoji: '🇪🇸', script: 'pptgames/ppt-spanish-language.js', global: 'pptSpanishLanguage', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-sports-equipment', label: 'Sports Equipment', emoji: '🏋️', script: 'pptgames/ppt-sports-equipment.js', global: 'pptSportsEquipment', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-star-trek', label: 'Star Trek', emoji: '🖖', script: 'pptgames/ppt-star-trek.js', global: 'pptStarTrek', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-star-wars', label: 'Star Wars', emoji: '🌌', script: 'pptgames/ppt-star-wars.js', global: 'pptStarWars', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-teenage-mutant-ninja-turtles', label: 'Teenage Mutant Ninja Turtles', emoji: '🐢', script: 'pptgames/ppt-teenage-mutant-ninja-turtles.js', global: 'pptTeenageMutantNinjaTurtles', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-tennis', label: 'Tennis', emoji: '🎾', script: 'pptgames/ppt-tennis.js', global: 'pptTennis', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-toddler-shows', label: 'Toddler Shows', emoji: '📺', script: 'pptgames/ppt-toddler-shows.js', global: 'pptToddlerShows', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-tools', label: 'Tools', emoji: '🔧', script: 'pptgames/ppt-tools.js', global: 'pptTools', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-toys', label: 'Toys', emoji: '🧸', script: 'pptgames/ppt-toys.js', global: 'pptToys', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-transformers', label: 'Transformers', emoji: '🤖', script: 'pptgames/ppt-transformers.js', global: 'pptTransformers', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-typing', label: 'Typing', emoji: '⌨️', script: 'pptgames/ppt-typing.js', global: 'pptTyping', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-us-city-locations', label: 'US City Locations', emoji: '🏙️', script: 'pptgames/ppt-us-city-locations.js', global: 'pptUsCityLocations', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-us-government', label: 'US Government', emoji: '🏛️', script: 'pptgames/ppt-us-government.js', global: 'pptUsGovernment', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-us-state-capitals', label: 'US State Capitals', emoji: '🗺️', script: 'pptgames/ppt-us-state-capitals.js', global: 'pptUsStateCapitals', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-us-states', label: 'US States', emoji: '🇺🇸', script: 'pptgames/ppt-us-states.js', global: 'pptUsStates', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-vegetables', label: 'Vegetables', emoji: '🥦', script: 'pptgames/ppt-vegetables.js', global: 'pptVegetables', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-video-game-consoles', label: 'Video Game Consoles', emoji: '🕹️', script: 'pptgames/ppt-video-game-consoles.js', global: 'pptVideoGameConsoles', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-video-games', label: 'Video Games', emoji: '🎮', script: 'pptgames/ppt-video-games.js', global: 'pptVideoGames', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-women-s-clothing', label: 'Women\'s Clothing', emoji: '👗', script: 'pptgames/ppt-women-s-clothing.js', global: 'pptWomensClothing', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-word-jumble', label: 'Word Jumble', emoji: '🔤', script: 'pptgames/ppt-word-jumble.js', global: 'pptWordJumble', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-word-jumble-bible', label: 'Word Jumble (Bible)', emoji: '📖', script: 'pptgames/ppt-word-jumble-bible.js', global: 'pptWordJumbleBible', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-word-plurals', label: 'Word Plurals', emoji: '📝', script: 'pptgames/ppt-word-plurals.js', global: 'pptWordPlurals', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-world-countries', label: 'World Countries', emoji: '🌍', script: 'pptgames/ppt-world-countries.js', global: 'pptWorldCountries', tier: 'PPTGAMES', shuffle: true },
    { key: 'ppt-zoo-animals', label: 'Zoo Animals', emoji: '🦁', script: 'pptgames/ppt-zoo-animals.js', global: 'pptZooAnimals', tier: 'PPTGAMES', shuffle: true },
];
if (typeof window !== 'undefined') window.CATEGORY_REGISTRY = CATEGORY_REGISTRY;
