// Instruments — images in images/instruments/
const instrumentsData = [
    // Tier 1 — Obvious (1–15)
    { n: "PIANO", u: "../images/instruments/piano.jpg" },
    { n: "ACOUSTIC GUITAR", u: "../images/instruments/acoustic-guitar.jpg" },
    { n: "VIOLIN", u: "../images/instruments/violin.jpg" },
    { n: "TRUMPET", u: "../images/instruments/trumpet.jpg" },
    { n: "DRUM SET", u: "../images/instruments/drum-set.jpg" },
    { n: "FLUTE", u: "../images/instruments/flute.jpg" },
    { n: "SAXOPHONE", u: "../images/instruments/saxophone.jpg" },
    { n: "HARP", u: "../images/instruments/harp.webp" },
    { n: "HARMONICA", u: "../images/instruments/harmonica.jpg" },
    { n: "CYMBALS", u: "../images/instruments/cymbals.jpg" },
    { n: "XYLOPHONE", u: "../images/instruments/xylophone.jpg" },
    { n: "CELLO", u: "../images/instruments/cello.jpg" },
    { n: "TROMBONE", u: "../images/instruments/trombone.jpg" },
    { n: "CLARINET", u: "../images/instruments/clarinet.png" },
    { n: "TUBA", u: "../images/instruments/tuba.jpg" },

    // Tier 2 — Familiar (16–30)
    { n: "ELECTRIC GUITAR", u: "../images/instruments/electric-guitar.jpg" },
    { n: "FRENCH HORN", u: "../images/instruments/french-horn.jpg" },
    { n: "BANJO", u: "../images/instruments/banjo.jpg" },
    { n: "ACCORDION", u: "../images/instruments/accordion.jpg" },
    { n: "UKULELE", u: "../images/instruments/ukulele.webp" },
    { n: "TAMBOURINE", u: "../images/instruments/tambourine.webp" },
    { n: "MANDOLIN", u: "../images/instruments/mandolin.jpg" },
    { n: "GONG", u: "../images/instruments/gong.jpg" },
    { n: "OBOE", u: "../images/instruments/oboe.jpg" },
    { n: "VIBRAPHONE", u: "../images/instruments/vibraphone.jpg" },
    { n: "BASS GUITAR", u: "../images/instruments/bass-guitar.jpg" },
    { n: "MARACAS", u: "../images/instruments/maracas.jpg" },
    { n: "TIMPANI", u: "../images/instruments/timpani.jpg" },
    { n: "ORGAN", u: "../images/instruments/organ.png" },
    { n: "PICCOLO", u: "../images/instruments/piccolo.jpg" },

    // Tier 3 — Knowledgeable (31–40)
    { n: "SYNTHESIZER", u: "../images/instruments/synthesizer.jpg" },
    { n: "SITAR", u: "../images/instruments/sitar.jpg" },
    { n: "ENGLISH HORN", u: "../images/instruments/english-horn.jpg" },
    { n: "LUTE", u: "../images/instruments/lute.jpg" },
    { n: "DULCIMER", u: "../images/instruments/dulcimer.jpg" },
    { n: "STEEL DRUM", u: "../images/instruments/steel-drum.jpg" },
    { n: "KALIMBA", u: "../images/instruments/kalimba.jpg" },
    { n: "BAGPIPE", u: "../images/instruments/bagpipe.jpg" },
    { n: "LYRE", u: "../images/instruments/lyre.jpg" },
    { n: "BUGLE", u: "../images/instruments/bugle.jpg" },

    // Tier 4 — Expert (41–50)
    { n: "THEREMIN", u: "../images/instruments/theremin.jpg" },
    { n: "BOUZOUKI", u: "../images/instruments/bouzouki.jpg" },
    { n: "BALALAIKA", u: "../images/instruments/balalaika.jpg" },
    { n: "HURDY-GURDY", u: "../images/instruments/hurdy-gurdy.jpg" },
    { n: "REBEC", u: "../images/instruments/rebec.jpg" },
    { n: "KOTO", u: "../images/instruments/koto.jpg" },
    { n: "SHAMISEN", u: "../images/instruments/shamisen.jpg" },
    { n: "GUZHENG", u: "../images/instruments/guzheng.webp" },
    { n: "PAN FLUTE", u: "../images/instruments/pan-flute.jpg" },
    { n: "OUD", u: "../images/instruments/oud.jpg" },

    // ── BACKUPS (51–60) ────────────────
    { n: "CORNET", u: "../images/instruments/cornet.jpg" },
    { n: "FINGER CYMBALS", u: "../images/instruments/finger-cymbals.jpg" },
    { n: "DJEMBE", u: "../images/instruments/djembe.jpg" },
    { n: "LIRA", u: "../images/instruments/lira.webp" },
    { n: "VIOL", u: "../images/instruments/viol.jpg" },
    { n: "PENNYWHISTLE", u: "../images/instruments/pennywhistle.jpg" },
    { n: "GUSLI", u: "../images/instruments/gusli.jpg" },
    { n: "CRWTH", u: "../images/instruments/crwth.jpg" },
    { n: "VIOLS", u: "../images/instruments/viols.webp" },
    { n: "HANDPAN", u: "../images/instruments/handpan.webp" },
];
if (typeof window !== 'undefined') window.instrumentsData = instrumentsData;
