// Logos — images in images/logos/
const logosData = [
    // Tier 1 — Obvious (1–15)
    { n: "APPLE", u: "../images/logos/apple.webp" },
    { n: "NIKE", u: "../images/logos/nike.webp" },
    { n: "MCDONALD'S", u: "../images/logos/mcdonalds.webp" },
    { n: "TARGET", u: "../images/logos/target.webp" },
    { n: "PEPSI", u: "../images/logos/pepsi.webp" },
    { n: "ADIDAS", u: "../images/logos/adidas.webp" },
    { n: "STARBUCKS", u: "../images/logos/starbucks.webp" },
    { n: "INSTAGRAM", u: "../images/logos/instagram.webp" },
    { n: "SNAPCHAT", u: "../images/logos/snapchat.webp" },
    { n: "TWITTER", u: "../images/logos/twitter.webp" },
    { n: "MERCEDES-BENZ", u: "../images/logos/mercedes-benz.webp" },
    { n: "PLAYSTATION", u: "../images/logos/playstation.webp" },
    { n: "XBOX", u: "../images/logos/xbox.webp" },
    { n: "SPOTIFY", u: "../images/logos/spotify.webp" },
    { n: "FERRARI", u: "../images/logos/ferrari.webp" },

    // Tier 2 — Familiar (16–30)
    { n: "TOYOTA", u: "../images/logos/toyota.webp" },
    { n: "BMW", u: "../images/logos/bmw.webp" },
    { n: "TESLA", u: "../images/logos/tesla.webp" },
    { n: "PUMA", u: "../images/logos/puma.webp" },
    { n: "MASTERCARD", u: "../images/logos/mastercard.webp" },
    { n: "SHELL", u: "../images/logos/shell.webp" },
    { n: "FIREFOX", u: "../images/logos/firefox.webp" },
    { n: "RED BULL", u: "../images/logos/red-bull.webp" },
    { n: "LACOSTE", u: "../images/logos/lacoste.webp" },
    { n: "CHANEL", u: "../images/logos/chanel.webp" },
    { n: "BLUETOOTH", u: "../images/logos/bluetooth.webp" },
    { n: "ANDROID", u: "../images/logos/android.webp" },
    { n: "PINTEREST", u: "../images/logos/pinterest.webp" },
    { n: "NBC", u: "../images/logos/nbc.webp" },
    { n: "TIKTOK", u: "../images/logos/tiktok.webp" },

    // Tier 3 — Knowledgeable (31–40)
    { n: "ROLEX", u: "../images/logos/rolex.webp" },
    { n: "VERSACE", u: "../images/logos/versace.webp" },
    { n: "AIRBNB", u: "../images/logos/airbnb.webp" },
    { n: "RALPH LAUREN", u: "../images/logos/ralph-lauren.webp" },
    { n: "LAMBORGHINI", u: "../images/logos/lamborghini.webp" },
    { n: "PORSCHE", u: "../images/logos/porsche.webp" },
    { n: "MITSUBISHI", u: "../images/logos/mitsubishi.webp" },
    { n: "BEATS", u: "../images/logos/beats.webp" },
    { n: "WWF", u: "../images/logos/wwf.webp" },
    { n: "MICHELIN", u: "../images/logos/michelin.webp" },

    // Tier 4 — Expert (41–50)
    { n: "ALFA ROMEO", u: "../images/logos/alfa-romeo.webp" },
    { n: "MASERATI", u: "../images/logos/maserati.webp" },
    { n: "BENTLEY", u: "../images/logos/bentley.webp" },
    { n: "CBS", u: "../images/logos/cbs.webp" },
    { n: "WIKIPEDIA", u: "../images/logos/wikipedia.webp" },
    { n: "ATARI", u: "../images/logos/atari.webp" },
    { n: "RENAULT", u: "../images/logos/renault.webp" },
    { n: "PEUGEOT", u: "../images/logos/peugeot.webp" },
    { n: "JAGUAR", u: "../images/logos/jaguar.webp" },
    { n: "DODGE", u: "../images/logos/dodge.webp" },

    // ── BACKUPS (51–60) ────────────────
    { n: "LINUX", u: "../images/logos/linux.webp" },
    { n: "CITROËN", u: "../images/logos/citroen.webp" },
    { n: "INFINITI", u: "../images/logos/infiniti.webp" },
    { n: "MAZDA", u: "../images/logos/mazda.webp" },
    { n: "SUBARU", u: "../images/logos/subaru.webp" },
    { n: "UNDER ARMOUR", u: "../images/logos/under-armour.webp" },
    { n: "SUZUKI", u: "../images/logos/suzuki.webp" },
    { n: "PARAMOUNT", u: "../images/logos/paramount.webp" },
    { n: "MGM", u: "../images/logos/mgm.webp" },
    { n: "ROLLS-ROYCE", u: "../images/logos/rolls-royce.webp" },
];
if (typeof window !== 'undefined') window.logosData = logosData;
