const puppetsData = [
    // Tier 1 — Obvious (1-15)
    { n: "KERMIT THE FROG", u: "../images/puppets/kermit-the-frog.webp" },
    { n: "ELMO", u: "../images/puppets/elmo.webp" },
    { n: "MARIONETTE", u: "../images/puppets/marionette.webp" },
    { n: "BIG BIRD", u: "../images/puppets/big-bird.webp" },
    { n: "SOCK PUPPET", u: "../images/puppets/sock-puppet.webp" },
    { n: "COOKIE MONSTER", u: "../images/puppets/cookie-monster.webp" },
    { n: "HAND PUPPET", u: "../images/puppets/hand-puppet.webp" },
    { n: "MISS PIGGY", u: "../images/puppets/miss-piggy.webp" },
    { n: "BERT AND ERNIE", u: "../images/puppets/bert-and-ernie.webp" },
    { n: "FINGER PUPPET", u: "../images/puppets/finger-puppet.webp" },
    { n: "OSCAR THE GROUCH", u: "../images/puppets/oscar-the-grouch.webp" },
    { n: "SHADOW PUPPET", u: "../images/puppets/shadow-puppet.webp" },
    { n: "YODA", u: "../images/puppets/yoda.webp" },
    { n: "TICKLE ME ELMO", u: "../images/puppets/tickle-me-elmo.webp" },
    { n: "ANIMAL", u: "../images/puppets/animal.webp" },

    // Tier 2 — Familiar (16-30)
    { n: "FOZZIE BEAR", u: "../images/puppets/fozzie-bear.webp" },
    { n: "COUNT VON COUNT", u: "../images/puppets/count-von-count.webp" },
    { n: "GROVER", u: "../images/puppets/grover.webp" },
    { n: "GIZMO", u: "../images/puppets/gizmo.webp" },
    { n: "ALF", u: "../images/puppets/alf.webp" },
    { n: "SLAPPY THE DUMMY", u: "../images/puppets/slappy-the-dummy.webp" },
    { n: "GONZO", u: "../images/puppets/gonzo.webp" },
    { n: "VENTRILOQUIST DUMMY", u: "../images/puppets/ventriloquist-dummy.webp" },
    { n: "BEAKER", u: "../images/puppets/beaker.webp" },
    { n: "SWEDISH CHEF", u: "../images/puppets/swedish-chef.webp" },
    { n: "ABBY CADABBY", u: "../images/puppets/abby-cadabby.webp" },
    { n: "SNUFFLEUPAGUS", u: "../images/puppets/snuffleupagus.webp" },
    { n: "PUNCH AND JUDY", u: "../images/puppets/punch-and-judy.webp" },
    { n: "LAMB CHOP", u: "../images/puppets/lamb-chop.webp" },
    { n: "STATLER AND WALDORF", u: "../images/puppets/statler-and-waldorf.webp" },

    // Tier 3 — Knowledgeable (31-40)
    { n: "AUDREY II", u: "../images/puppets/audrey-ii.webp" },
    { n: "HOWDY DOODY", u: "../images/puppets/howdy-doody.webp" },
    { n: "FRAGGLE ROCK", u: "../images/puppets/fraggle-rock.webp" },
    { n: "THUNDERBIRDS", u: "../images/puppets/thunderbirds.webp" },
    { n: "JABBA THE HUTT", u: "../images/puppets/jabba-the-hutt.webp" },
    { n: "ROWLF THE DOG", u: "../images/puppets/rowlf-the-dog.webp" },
    { n: "PEPE THE KING PRAWN", u: "../images/puppets/pepe-the-king-prawn.webp" },
    { n: "TEAM AMERICA", u: "../images/puppets/team-america.webp" },
    { n: "FALCOR", u: "../images/puppets/falcor.webp" },
    { n: "DARK CRYSTAL GELFLING", u: "../images/puppets/dark-crystal-gelfling.webp" },

    // Tier 4 — Expert (41-50)
    { n: "BUNRAKU PUPPET", u: "../images/puppets/bunraku-puppet.webp" },
    { n: "WAYANG KULIT", u: "../images/puppets/wayang-kulit.webp" },
    { n: "GUIGNOL", u: "../images/puppets/guignol.webp" },
    { n: "WATER PUPPET", u: "../images/puppets/water-puppet.webp" },
    { n: "TOPO GIGIO", u: "../images/puppets/topo-gigio.webp" },
    { n: "CHARLIE MCCARTHY", u: "../images/puppets/charlie-mccarthy.webp" },
    { n: "ACHMED THE DEAD TERRORIST", u: "../images/puppets/achmed-the-dead-terrorist.webp" },
    { n: "MOKEY FRAGGLE", u: "../images/puppets/mokey-fraggle.webp" },
    { n: "WEMBLEY FRAGGLE", u: "../images/puppets/wembley-fraggle.webp" },
    { n: "LABYRINTH GOBLIN", u: "../images/puppets/labyrinth-goblin.webp" },

    // ── BACKUPS (51-60) ────────────────
    { n: "SOCKO", u: "../images/puppets/socko.webp" },
    { n: "FLAT ERIC", u: "../images/puppets/flat-eric.webp" },
    { n: "CONKLIN", u: "../images/puppets/conklin.webp" },
    { n: "WALTER", u: "../images/puppets/walter.webp" },
    { n: "ED EUSTACE", u: "../images/puppets/ed-eustace.webp" },
    { n: "DOOZER", u: "../images/puppets/doozer.webp" },
    { n: "RED FRAGGLE", u: "../images/puppets/red-fraggle.webp" },
    { n: "BOOBER FRAGGLE", u: "../images/puppets/boober-fraggle.webp" },
    { n: "GOBO FRAGGLE", u: "../images/puppets/gobo-fraggle.webp" },
    { n: "MADAME", u: "../images/puppets/madame.webp" },
];
if (typeof window !== 'undefined') window.puppetsData = puppetsData;
