const seafoodData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "SHRIMP", u: "../images/seafood/shrimp.jpg" },
    { n: "LOBSTER", u: "../images/seafood/lobster.jpg" },
    { n: "CRAB", u: "../images/seafood/crab.jpg" },
    { n: "SALMON", u: "../images/seafood/salmon.jpg" },
    { n: "TUNA", u: "../images/seafood/tuna.jpg" },
    { n: "OYSTER", u: "../images/seafood/oyster.jpg" },
    { n: "CLAM", u: "../images/seafood/clam.jpg" },
    { n: "SQUID", u: "../images/seafood/squid.jpg" },
    { n: "OCTOPUS", u: "../images/seafood/octopus.jpg" },
    { n: "SCALLOP", u: "../images/seafood/scallop.jpg" },
    { n: "MUSSEL", u: "../images/seafood/mussel.jpg" },
    { n: "CAVIAR", u: "../images/seafood/caviar.jpg" },
    { n: "SUSHI", u: "../images/seafood/sushi.jpg" },
    { n: "FISH AND CHIPS", u: "../images/seafood/fish-and-chips.jpg" },
    { n: "CRAWFISH", u: "../images/seafood/crawfish.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "MAHI-MAHI", u: "../images/seafood/mahi-mahi.jpg" },
    { n: "HALIBUT", u: "../images/seafood/halibut.jpg" },
    { n: "SWORDFISH", u: "../images/seafood/swordfish.jpg" },
    { n: "GROUPER", u: "../images/seafood/grouper.jpg" },
    { n: "RED SNAPPER", u: "../images/seafood/red-snapper.jpg" },
    { n: "COD", u: "../images/seafood/cod.jpg" },
    { n: "HADDOCK", u: "../images/seafood/haddock.jpg" },
    { n: "TROUT", u: "../images/seafood/trout.jpg" },
    { n: "CATFISH", u: "../images/seafood/catfish.jpg" },
    { n: "TILAPIA", u: "../images/seafood/tilapia.jpg" },
    { n: "SARDINES", u: "../images/seafood/sardines.jpg" },
    { n: "ANCHOVIES", u: "../images/seafood/anchovies.jpg" },
    { n: "EEL", u: "../images/seafood/eel.jpg" },
    { n: "SEA URCHIN", u: "../images/seafood/sea-urchin.jpg" },
    { n: "PRAWN", u: "../images/seafood/prawn.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "KING CRAB", u: "../images/seafood/king-crab.jpg" },
    { n: "SNOW CRAB", u: "../images/seafood/snow-crab.jpg" },
    { n: "SOFT-SHELL CRAB", u: "../images/seafood/soft-shell-crab.jpg" },
    { n: "LANGOUSTINE", u: "../images/seafood/langoustine.jpg" },
    { n: "ABALONE", u: "../images/seafood/abalone.jpg" },
    { n: "GEODUCK", u: "../images/seafood/geoduck.jpg" },
    { n: "CONCH", u: "../images/seafood/conch.jpg" },
    { n: "WHELK", u: "../images/seafood/whelk.jpg" },
    { n: "GOOSENECK BARNACLES", u: "../images/seafood/gooseneck-barnacles.jpg" },
    { n: "CUTTLEFISH", u: "../images/seafood/cuttlefish.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "MACKEREL", u: "../images/seafood/mackerel.jpg" },
    { n: "HERRING", u: "../images/seafood/herring.jpg" },
    { n: "FLOUNDER", u: "../images/seafood/flounder.jpg" },
    { n: "SOLE", u: "../images/seafood/sole.jpg" },
    { n: "MONKFISH", u: "../images/seafood/monkfish.jpg" },
    { n: "STURGEON", u: "../images/seafood/sturgeon.jpg" },
    { n: "CHILEAN SEA BASS", u: "../images/seafood/chilean-sea-bass.jpg" },
    { n: "YELLOWTAIL", u: "../images/seafood/yellowtail.jpg" },
    { n: "BARRAMUNDI", u: "../images/seafood/barramundi.jpg" },
    { n: "BRANZINO", u: "../images/seafood/branzino.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "IMITATION CRAB", u: "../images/seafood/imitation-crab.jpg" },
    { n: "FISH STICKS", u: "../images/seafood/fish-sticks.jpg" },
    { n: "SMOKED SALMON", u: "../images/seafood/smoked-salmon.jpg" },
    { n: "CEVICHE", u: "../images/seafood/ceviche.jpg" },
    { n: "POKE BOWL", u: "../images/seafood/poke-bowl.jpg" },
    { n: "PAELLA", u: "../images/seafood/paella.jpg" },
    { n: "CLAM CHOWDER", u: "../images/seafood/clam-chowder.jpg" },
    { n: "LOBSTER ROLL", u: "../images/seafood/lobster-roll.jpg" },
    { n: "SCAMPI", u: "../images/seafood/scampi.jpg" },
    { n: "SHRIMP COCKTAIL", u: "../images/seafood/shrimp-cocktail.jpg" },
];
if (typeof window !== 'undefined') window.seafoodData = seafoodData;
