const sportsMvpsData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "LEBRON JAMES", u: "../images/sports-mvps/lebron-james.jpg" },
    { n: "MICHAEL JORDAN", u: "../images/sports-mvps/michael-jordan.jpg" },
    { n: "TOM BRADY", u: "../images/sports-mvps/tom-brady.jpg" },
    { n: "LIONEL MESSI", u: "../images/sports-mvps/lionel-messi.jpg" },
    { n: "KOBE BRYANT", u: "../images/sports-mvps/kobe-bryant.jpg" },
    { n: "PATRICK MAHOMES", u: "../images/sports-mvps/patrick-mahomes.jpg" },
    { n: "STEPHEN CURRY", u: "../images/sports-mvps/stephen-curry.jpg" },
    { n: "CRISTIANO RONALDO", u: "../images/sports-mvps/cristiano-ronaldo.jpg" },
    { n: "PEYTON MANNING", u: "../images/sports-mvps/peyton-manning.jpg" },
    { n: "MAGIC JOHNSON", u: "../images/sports-mvps/magic-johnson.jpg" },
    { n: "AARON RODGERS", u: "../images/sports-mvps/aaron-rodgers.jpg" },
    { n: "SHOHEI OHTANI", u: "../images/sports-mvps/shohei-ohtani.jpg" },
    { n: "SHAQUILLE O'NEAL", u: "../images/sports-mvps/shaquille-o-neal.jpg" },
    { n: "LAMAR JACKSON", u: "../images/sports-mvps/lamar-jackson.jpg" },
    { n: "KEVIN DURANT", u: "../images/sports-mvps/kevin-durant.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "BARRY BONDS", u: "../images/sports-mvps/barry-bonds.jpg" },
    { n: "GIANNIS ANTETOKOUNMPO", u: "../images/sports-mvps/giannis-antetokounmpo.jpg" },
    { n: "WAYNE GRETZKY", u: "../images/sports-mvps/wayne-gretzky.jpg" },
    { n: "SIDNEY CROSBY", u: "../images/sports-mvps/sidney-crosby.jpg" },
    { n: "A'JA WILSON", u: "../images/sports-mvps/a-ja-wilson.jpg" },
    { n: "BREANNA STEWART", u: "../images/sports-mvps/breanna-stewart.jpg" },
    { n: "NIKOLA JOKIC", u: "../images/sports-mvps/nikola-jokic.jpg" },
    { n: "MIKE TROUT", u: "../images/sports-mvps/mike-trout.jpg" },
    { n: "AARON JUDGE", u: "../images/sports-mvps/aaron-judge.jpg" },
    { n: "BRYCE HARPER", u: "../images/sports-mvps/bryce-harper.jpg" },
    { n: "MOOKIE BETTS", u: "../images/sports-mvps/mookie-betts.jpg" },
    { n: "BRETT FAVRE", u: "../images/sports-mvps/brett-favre.jpg" },
    { n: "STEVE NASH", u: "../images/sports-mvps/steve-nash.jpg" },
    { n: "TIM DUNCAN", u: "../images/sports-mvps/tim-duncan.jpg" },
    { n: "DIRK NOWITZKI", u: "../images/sports-mvps/dirk-nowitzki.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "ALLEN IVERSON", u: "../images/sports-mvps/allen-iverson.jpg" },
    { n: "RUSSELL WESTBROOK", u: "../images/sports-mvps/russell-westbrook.jpg" },
    { n: "JAMES HARDEN", u: "../images/sports-mvps/james-harden.jpg" },
    { n: "JOEL EMBIID", u: "../images/sports-mvps/joel-embiid.jpg" },
    { n: "ADRIAN PETERSON", u: "../images/sports-mvps/adrian-peterson.jpg" },
    { n: "CHRISTIAN YELICH", u: "../images/sports-mvps/christian-yelich.jpg" },
    { n: "MIGUEL CABRERA", u: "../images/sports-mvps/miguel-cabrera.jpg" },
    { n: "ALBERT PUJOLS", u: "../images/sports-mvps/albert-pujols.jpg" },
    { n: "ALEX RODRIGUEZ", u: "../images/sports-mvps/alex-rodriguez.jpg" },
    { n: "KEN GRIFFEY JR.", u: "../images/sports-mvps/ken-griffey-jr.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "CONNOR MCDAVID", u: "../images/sports-mvps/connor-mcdavid.jpg" },
    { n: "AUSTON MATTHEWS", u: "../images/sports-mvps/auston-matthews.jpg" },
    { n: "ALEXANDER OVECHKIN", u: "../images/sports-mvps/alexander-ovechkin.jpg" },
    { n: "MATT RYAN", u: "../images/sports-mvps/matt-ryan.jpg" },
    { n: "CAM NEWTON", u: "../images/sports-mvps/cam-newton.jpg" },
    { n: "LARRY BIRD", u: "../images/sports-mvps/larry-bird.jpg" },
    { n: "WILT CHAMBERLAIN", u: "../images/sports-mvps/wilt-chamberlain.jpg" },
    { n: "BILL RUSSELL", u: "../images/sports-mvps/bill-russell.jpg" },
    { n: "KAREEM ABDUL-JABBAR", u: "../images/sports-mvps/kareem-abdul-jabbar.jpg" },
    { n: "JULIUS ERVING", u: "../images/sports-mvps/julius-erving.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "CODY BELLINGER", u: "../images/sports-mvps/cody-bellinger.jpg" },
    { n: "RONALD ACUNA JR.", u: "../images/sports-mvps/ronald-acuna-jr.jpg" },
    { n: "FREDDIE FREEMAN", u: "../images/sports-mvps/freddie-freeman.jpg" },
    { n: "CLAYTON KERSHAW", u: "../images/sports-mvps/clayton-kershaw.jpg" },
    { n: "JUSTIN VERLANDER", u: "../images/sports-mvps/justin-verlander.jpg" },
    { n: "DERRICK ROSE", u: "../images/sports-mvps/derrick-rose.jpg" },
    { n: "CHARLES BARKLEY", u: "../images/sports-mvps/charles-barkley.jpg" },
    { n: "KARL MALONE", u: "../images/sports-mvps/karl-malone.jpg" },
    { n: "HAKEEM OLAJUWON", u: "../images/sports-mvps/hakeem-olajuwon.jpg" },
    { n: "DAVID ROBINSON", u: "../images/sports-mvps/david-robinson.jpg" },
];
if (typeof window !== 'undefined') window.sportsMvpsData = sportsMvpsData;
