const stateFlagsData = [
    { n: "TEXAS", u: "../images/state-flags/texas.webp" },
    { n: "CALIFORNIA", u: "../images/state-flags/california.webp" },
    { n: "COLORADO", u: "../images/state-flags/colorado.webp" },
    { n: "NEW MEXICO", u: "../images/state-flags/new-mexico.webp" },
    { n: "MARYLAND", u: "../images/state-flags/maryland.webp" },
    { n: "ALASKA", u: "../images/state-flags/alaska.webp" },
    { n: "HAWAII", u: "../images/state-flags/hawaii.webp" },
    { n: "SOUTH CAROLINA", u: "../images/state-flags/south-carolina.webp" },
    { n: "OHIO", u: "../images/state-flags/ohio.webp" },
    { n: "ARIZONA", u: "../images/state-flags/arizona.webp" },
    { n: "WYOMING", u: "../images/state-flags/wyoming.webp" },
    { n: "INDIANA", u: "../images/state-flags/indiana.webp" },
    { n: "TENNESSEE", u: "../images/state-flags/tennessee.webp" },
    { n: "WASHINGTON", u: "../images/state-flags/washington.webp" },
    { n: "MISSISSIPPI", u: "../images/state-flags/mississippi.webp" },
    { n: "LOUISIANA", u: "../images/state-flags/louisiana.webp" },
    { n: "RHODE ISLAND", u: "../images/state-flags/rhode-island.webp" },
    { n: "ALABAMA", u: "../images/state-flags/alabama.webp" },
    { n: "FLORIDA", u: "../images/state-flags/florida.webp" },
    { n: "GEORGIA", u: "../images/state-flags/georgia.webp" },
    { n: "ARKANSAS", u: "../images/state-flags/arkansas.webp" },
    { n: "MISSOURI", u: "../images/state-flags/missouri.webp" },
    { n: "IOWA", u: "../images/state-flags/iowa.webp" },
    { n: "MASSACHUSETTS", u: "../images/state-flags/massachusetts.webp" },
    { n: "VIRGINIA", u: "../images/state-flags/virginia.webp" },
    { n: "OKLAHOMA", u: "../images/state-flags/oklahoma.webp" },
    { n: "NEVADA", u: "../images/state-flags/nevada.webp" },
    { n: "NORTH CAROLINA", u: "../images/state-flags/north-carolina.webp" },
    { n: "CONNECTICUT", u: "../images/state-flags/connecticut.webp" },
    { n: "NEW YORK", u: "../images/state-flags/new-york.webp" },
    { n: "NEW JERSEY", u: "../images/state-flags/new-jersey.webp" },
    { n: "PENNSYLVANIA", u: "../images/state-flags/pennsylvania.webp" },
    { n: "ILLINOIS", u: "../images/state-flags/illinois.webp" },
    { n: "MICHIGAN", u: "../images/state-flags/michigan.webp" },
    { n: "WISCONSIN", u: "../images/state-flags/wisconsin.webp" },
    { n: "MINNESOTA", u: "../images/state-flags/minnesota.webp" },
    { n: "OREGON", u: "../images/state-flags/oregon.webp" },
    { n: "NORTH DAKOTA", u: "../images/state-flags/north-dakota.webp" },
    { n: "SOUTH DAKOTA", u: "../images/state-flags/south-dakota.webp" },
    { n: "MONTANA", u: "../images/state-flags/montana.webp" },
    { n: "IDAHO", u: "../images/state-flags/idaho.webp" },
    { n: "MAINE", u: "../images/state-flags/maine.webp" },
    { n: "NEW HAMPSHIRE", u: "../images/state-flags/new-hampshire.webp" },
    { n: "VERMONT", u: "../images/state-flags/vermont.webp" },
    { n: "KENTUCKY", u: "../images/state-flags/kentucky.webp" },
    { n: "DELAWARE", u: "../images/state-flags/delaware.webp" },
    { n: "WEST VIRGINIA", u: "../images/state-flags/west-virginia.webp" },
    { n: "NEBRASKA", u: "../images/state-flags/nebraska.webp" },
    { n: "KANSAS", u: "../images/state-flags/kansas.webp" },
    { n: "UTAH", u: "../images/state-flags/utah.webp" },
    
    // ── BACKUPS (items 51–60) ────────────────
    { n: "WASHINGTON D.C.", u: "../images/state-flags/washington-dc.webp" },
    { n: "PUERTO RICO", u: "../images/state-flags/puerto-rico.webp" },
    { n: "GUAM", u: "../images/state-flags/guam.webp" },
    { n: "US VIRGIN ISLANDS", u: "../images/state-flags/us-virgin-islands.webp" },
];
if (typeof window !== 'undefined') window.stateFlagsData = stateFlagsData;
