const superMarioData = [
    // Tier 1 — Obvious (items 1–15)
    { n: "MARIO", u: "../images/super-mario/mario.jpg" },
    { n: "LUIGI", u: "../images/super-mario/luigi.jpg" },
    { n: "PRINCESS PEACH", u: "../images/super-mario/princess-peach.jpg" },
    { n: "BOWSER", u: "../images/super-mario/bowser.jpg" },
    { n: "TOAD", u: "../images/super-mario/toad.jpg" },
    { n: "YOSHI", u: "../images/super-mario/yoshi.jpg" },
    { n: "SUPER MUSHROOM", u: "../images/super-mario/super-mushroom.jpg" },
    { n: "FIRE FLOWER", u: "../images/super-mario/fire-flower.jpg" },
    { n: "SUPER STAR", u: "../images/super-mario/super-star.jpg" },
    { n: "GOOMBA", u: "../images/super-mario/goomba.jpg" },
    { n: "KOOPA TROOPA", u: "../images/super-mario/koopa-troopa.jpg" },
    { n: "1-UP MUSHROOM", u: "../images/super-mario/1-up-mushroom.jpg" },
    { n: "COIN", u: "../images/super-mario/coin.jpg" },
    { n: "? BLOCK", u: "../images/super-mario/question-block.jpg" },
    { n: "WARP PIPE", u: "../images/super-mario/warp-pipe.jpg" },

    // Tier 2 — Familiar (items 16–30)
    { n: "WARIO", u: "../images/super-mario/wario.jpg" },
    { n: "WALUIGI", u: "../images/super-mario/waluigi.jpg" },
    { n: "DONKEY KONG", u: "../images/super-mario/donkey-kong.jpg" },
    { n: "BOWSER JR.", u: "../images/super-mario/bowser-jr.jpg" },
    { n: "BOO", u: "../images/super-mario/boo.jpg" },
    { n: "BOB-OMB", u: "../images/super-mario/bob-omb.jpg" },
    { n: "BULLET BILL", u: "../images/super-mario/bullet-bill.jpg" },
    { n: "PIRANHA PLANT", u: "../images/super-mario/piranha-plant.jpg" },
    { n: "CHEEP CHEEP", u: "../images/super-mario/cheep-cheep.jpg" },
    { n: "THWOMP", u: "../images/super-mario/thwomp.jpg" },
    { n: "SHY GUY", u: "../images/super-mario/shy-guy.jpg" },
    { n: "LAKITU", u: "../images/super-mario/lakitu.jpg" },
    { n: "SPINY", u: "../images/super-mario/spiny.jpg" },
    { n: "MAGIKOOPA", u: "../images/super-mario/magikoopa.jpg" },
    { n: "CHAIN CHOMP", u: "../images/super-mario/chain-chomp.jpg" },

    // Tier 3 — Knowledgeable (items 31–40)
    { n: "DRY BONES", u: "../images/super-mario/dry-bones.jpg" },
    { n: "HAMMER BRO", u: "../images/super-mario/hammer-bro.jpg" },
    { n: "TOADETTE", u: "../images/super-mario/toadette.jpg" },
    { n: "ROSALINA", u: "../images/super-mario/rosalina.jpg" },
    { n: "DAISY", u: "../images/super-mario/daisy.jpg" },
    { n: "BIRDO", u: "../images/super-mario/birdo.jpg" },
    { n: "DIDDY KONG", u: "../images/super-mario/diddy-kong.jpg" },
    { n: "POW BLOCK", u: "../images/super-mario/pow-block.jpg" },
    { n: "P-SWITCH", u: "../images/super-mario/p-switch.jpg" },
    { n: "CAPE FEATHER", u: "../images/super-mario/cape-feather.jpg" },

    // Tier 4 — Expert (items 41–50)
    { n: "SUPER LEAF", u: "../images/super-mario/super-leaf.jpg" },
    { n: "ICE FLOWER", u: "../images/super-mario/ice-flower.jpg" },
    { n: "MEGA MUSHROOM", u: "../images/super-mario/mega-mushroom.jpg" },
    { n: "PENGUIN SUIT", u: "../images/super-mario/penguin-suit.jpg" },
    { n: "PROPELLER MUSHROOM", u: "../images/super-mario/propeller-mushroom.jpg" },
    { n: "KING BOO", u: "../images/super-mario/king-boo.jpg" },
    { n: "PETEY PIRANHA", u: "../images/super-mario/petey-piranha.jpg" },
    { n: "WIGGLER", u: "../images/super-mario/wiggler.jpg" },
    { n: "BLOOPER", u: "../images/super-mario/blooper.jpg" },
    { n: "POKEY", u: "../images/super-mario/pokey.jpg" },

    // ── BACKUPS (items 51–60) ────────────────
    { n: "MONTY MOLE", u: "../images/super-mario/monty-mole.jpg" },
    { n: "BOOMERANG FLOWER", u: "../images/super-mario/boomerang-flower.jpg" },
    { n: "SUPER BELL", u: "../images/super-mario/super-bell.jpg" },
    { n: "LUMA", u: "../images/super-mario/luma.jpg" },
    { n: "NABBIT", u: "../images/super-mario/nabbit.jpg" },
    { n: "TOADSWORTH", u: "../images/super-mario/toadsworth.jpg" },
    { n: "BOOM BOOM", u: "../images/super-mario/boom-boom.jpg" },
    { n: "POM POM", u: "../images/super-mario/pom-pom.jpg" },
    { n: "IGGY KOOPA", u: "../images/super-mario/iggy-koopa.jpg" },
    { n: "SPIKE", u: "../images/super-mario/spike.jpg" },
];
if (typeof window !== 'undefined') window.superMarioData = superMarioData;
