const visualNovelsData = [
    { n: "ACE ATTORNEY", u: "../images/visual-novels/ace-attorney.webp" },
    { n: "DOKI DOKI LITERATURE CLUB", u: "../images/visual-novels/doki-doki-literature-club.webp" },
    { n: "DANGANRONPA", u: "../images/visual-novels/danganronpa.webp" },
    { n: "STEINS;GATE", u: "../images/visual-novels/steins-gate.webp" },
    { n: "CLANNAD", u: "../images/visual-novels/clannad.webp" },
    { n: "FATE/STAY NIGHT", u: "../images/visual-novels/fate-stay-night.webp" },
    { n: "HATOFUL BOYFRIEND", u: "../images/visual-novels/hatoful-boyfriend.webp" },
    { n: "VA-11 HALL-A", u: "../images/visual-novels/va-11-hall-a.webp" },
    { n: "NEKOPARA", u: "../images/visual-novels/nekopara.webp" },
    { n: "HIGURASHI WHEN THEY CRY", u: "../images/visual-novels/higurashi-when-they-cry.webp" },
    { n: "MYSTIC MESSENGER", u: "../images/visual-novels/mystic-messenger.webp" },
    { n: "ZERO ESCAPE", u: "../images/visual-novels/zero-escape.webp" },
    { n: "COFFEE TALK", u: "../images/visual-novels/coffee-talk.webp" },
    { n: "KATAWA SHOUJO", u: "../images/visual-novels/katawa-shoujo.webp" },
    { n: "THE SOMNIUM FILES", u: "../images/visual-novels/the-somnium-files.webp" },
    { n: "MONSTER PROM", u: "../images/visual-novels/monster-prom.webp" },
    { n: "DREAM DADDY", u: "../images/visual-novels/dream-daddy.webp" },
    { n: "UMINEKO WHEN THEY CRY", u: "../images/visual-novels/umineko-when-they-cry.webp" },
    { n: "MUV-LUV", u: "../images/visual-novels/muv-luv.webp" },
    { n: "SAYA NO UTA", u: "../images/visual-novels/saya-no-uta.webp" },
    { n: "AMNESIA: MEMORIES", u: "../images/visual-novels/amnesia-memories.webp" },
    { n: "CORPSE PARTY", u: "../images/visual-novels/corpse-party.webp" },
    { n: "THE FRUIT OF GRISAIA", u: "../images/visual-novels/the-fruit-of-grisaia.webp" },
    { n: "LITTLE BUSTERS!", u: "../images/visual-novels/little-busters.webp" },
    { n: "TSUKIHIME", u: "../images/visual-novels/tsukihime.webp" },
    { n: "KANON", u: "../images/visual-novels/kanon.webp" },
    { n: "AIR", u: "../images/visual-novels/air.webp" },
    { n: "REWRITE", u: "../images/visual-novels/rewrite.webp" },
    { n: "WHITE ALBUM 2", u: "../images/visual-novels/white-album-2.webp" },
    { n: "DIES IRAE", u: "../images/visual-novels/dies-irae.webp" },
    { n: "CHAOS;HEAD", u: "../images/visual-novels/chaos-head.webp" },
    { n: "ROBOTICS;NOTES", u: "../images/visual-novels/robotics-notes.webp" },
    { n: "CHAOS;CHILD", u: "../images/visual-novels/chaos-child.webp" },
    { n: "BALDR SKY", u: "../images/visual-novels/baldr-sky.webp" },
    { n: "MAJIKOI", u: "../images/visual-novels/majikoi.webp" },
    { n: "WONDERFUL EVERYDAY", u: "../images/visual-novels/wonderful-everyday.webp" },
    { n: "EVER17", u: "../images/visual-novels/ever17.webp" },
    { n: "ROOT DOUBLE", u: "../images/visual-novels/root-double.webp" },
    { n: "THE HOUSE IN FATA MORGANA", u: "../images/visual-novels/the-house-in-fata-morgana.webp" },
    { n: "G-SENJOU NO MAOU", u: "../images/visual-novels/g-senjou-no-maou.webp" },
    { n: "FAULT MILESTONE ONE", u: "../images/visual-novels/fault-milestone-one.webp" },
    { n: "ARCADE SPIRITS", u: "../images/visual-novels/arcade-spirits.webp" },
    { n: "READ ONLY MEMORIES", u: "../images/visual-novels/read-only-memories.webp" },
    { n: "LONG LIVE THE QUEEN", u: "../images/visual-novels/long-live-the-queen.webp" },
    { n: "OUR LIFE", u: "../images/visual-novels/our-life.webp" },
    { n: "CINDERELLA PHENOMENON", u: "../images/visual-novels/cinderella-phenomenon.webp" },
    { n: "HAKUOKI", u: "../images/visual-novels/hakuoki.webp" },
    { n: "CODE: REALIZE", u: "../images/visual-novels/code-realize.webp" },
    { n: "COLLAR X MALICE", u: "../images/visual-novels/collar-x-malice.webp" },
    { n: "TOKIMEKI MEMORIAL", u: "../images/visual-novels/tokimeki-memorial.webp" },
    
    // ── BACKUPS (items 51–60) ────────────────
    { n: "OLYMPIA SOIREE", u: "../images/visual-novels/olympia-soiree.webp" },
    { n: "BUSTAFELLOWS", u: "../images/visual-novels/bustafellows.webp" },
    { n: "PIOFIORE", u: "../images/visual-novels/piofiore.webp" },
    { n: "CAFE ENCHANTE", u: "../images/visual-novels/cafe-enchante.webp" },
    { n: "CUPID PARASITE", u: "../images/visual-novels/cupid-parasite.webp" },
    { n: "CLOCK ZERO", u: "../images/visual-novels/clock-zero.webp" },
    { n: "DA CAPO", u: "../images/visual-novels/da-capo.webp" },
    { n: "AMAGAMI", u: "../images/visual-novels/amagami.webp" },
    { n: "YU-NO", u: "../images/visual-novels/yu-no.webp" },
    { n: "CLOVER DAY'S", u: "../images/visual-novels/clover-days.webp" }
];
if (typeof window !== 'undefined') window.visualNovelsData = visualNovelsData;
