// Church — images in images/pptgames/Church/
const pptChurch = [
    { n: "ALTAR", u: "../images/pptgames/Church/Altar.jpg" },
    { n: "BAPTISTRY, BAPTISMAL POOL", u: "../images/pptgames/Church/Baptistry, Baptismal Pool.jpg" },
    { n: "BELL TOWER", u: "../images/pptgames/Church/Bell Tower.jpg" },
    { n: "BIBLE", u: "../images/pptgames/Church/Bible.jpg" },
    { n: "BULLETIN", u: "../images/pptgames/Church/Bulletin.jpg" },
    { n: "CANDLES", u: "../images/pptgames/Church/Candles.jpg" },
    { n: "CHALICE", u: "../images/pptgames/Church/Chalice.jpg" },
    { n: "CHOIR", u: "../images/pptgames/Church/Choir.jpg" },
    { n: "CLASSROOM, SUNDAY SCHOOL", u: "../images/pptgames/Church/Classroom, Sunday School.jpg" },
    { n: "COMMUNION BREAD", u: "../images/pptgames/Church/Communion Bread.jpg" },
    { n: "COMMUNION WINE", u: "../images/pptgames/Church/Communion Wine.jpg" },
    { n: "CONFESSIONAL", u: "../images/pptgames/Church/Confessional.jpg" },
    { n: "CROSS", u: "../images/pptgames/Church/Cross.jpg" },
    { n: "CRUCIFIX", u: "../images/pptgames/Church/Crucifix.jpg" },
    { n: "FELLOWSHIP HALL", u: "../images/pptgames/Church/Fellowship Hall.jpg" },
    { n: "HYMN", u: "../images/pptgames/Church/Hymn.jpg" },
    { n: "HYMNAL, HYMNBOOK", u: "../images/pptgames/Church/Hymnal, Hymnbook.jpg" },
    { n: "KNEELER, KNEELING BENCH", u: "../images/pptgames/Church/Kneeler, Kneeling Bench.jpg" },
    { n: "LECTERN", u: "../images/pptgames/Church/Lectern.jpg" },
    { n: "LIVESTREAM CAMERA", u: "../images/pptgames/Church/Livestream Camera.jpg" },
    { n: "LOGO", u: "../images/pptgames/Church/Logo.jpg" },
    { n: "MUSIC STAND", u: "../images/pptgames/Church/Music Stand.jpg" },
    { n: "NURSERY ROOM", u: "../images/pptgames/Church/Nursery Room.jpg" },
    { n: "OFFERING PLATE", u: "../images/pptgames/Church/Offering Plate.jpg" },
    { n: "OFFERING, COLLECTION BASKET", u: "../images/pptgames/Church/Offering, Collection Basket.jpg" },
    { n: "PASTOR, PREACHER", u: "../images/pptgames/Church/Pastor, Preacher.jpg" },
    { n: "PEWS", u: "../images/pptgames/Church/Pews.jpg" },
    { n: "PIANO", u: "../images/pptgames/Church/Piano.jpg" },
    { n: "PIPE ORGAN", u: "../images/pptgames/Church/Pipe Organ.jpg" },
    { n: "PRAYER, PRAYING HANDS", u: "../images/pptgames/Church/Prayer, Praying Hands.jpg" },
    { n: "PROJECTION SCREEN", u: "../images/pptgames/Church/Projection Screen.jpg" },
    { n: "PULPIT MICROPHONE", u: "../images/pptgames/Church/Pulpit Microphone.jpg" },
    { n: "PULPIT", u: "../images/pptgames/Church/Pulpit.jpg" },
    { n: "ROBES", u: "../images/pptgames/Church/Robes.jpg" },
    { n: "SANCTUARY", u: "../images/pptgames/Church/Sanctuary.jpg" },
    { n: "SIGN, MARQUEE SIGN", u: "../images/pptgames/Church/Sign, Marquee Sign.jpg" },
    { n: "STAINED GLASS", u: "../images/pptgames/Church/Stained Glass.jpg" },
    { n: "STEEPLE", u: "../images/pptgames/Church/Steeple.jpg" },
    { n: "TITHE ENVELOPE", u: "../images/pptgames/Church/Tithe Envelope.jpg" },
    { n: "WORSHIP BAND, PRAISE TEAM", u: "../images/pptgames/Church/Worship Band, Praise Team.jpg" }
];
if (typeof window !== "undefined") window.pptChurch = pptChurch;
