// Flowers — images in images/pptgames/Flowers/
const pptFlowers = [
    { n: "AMARYLLIS", u: "../images/pptgames/Flowers/Amaryllis.jpg" },
    { n: "ANEMONE", u: "../images/pptgames/Flowers/Anemone.jpg" },
    { n: "ASTER", u: "../images/pptgames/Flowers/Aster.jpg" },
    { n: "AZALEA", u: "../images/pptgames/Flowers/Azalea.jpg" },
    { n: "BEGONIA", u: "../images/pptgames/Flowers/Begonia.jpg" },
    { n: "BIRD OF PARADISE", u: "../images/pptgames/Flowers/Bird of Paradise.jpg" },
    { n: "BLUEBELL", u: "../images/pptgames/Flowers/Bluebell.jpg" },
    { n: "BUTTERCUP", u: "../images/pptgames/Flowers/Buttercup.jpg" },
    { n: "CALLA LILY", u: "../images/pptgames/Flowers/Calla Lily.jpg" },
    { n: "CAMELLIA", u: "../images/pptgames/Flowers/Camellia.jpg" },
    { n: "CARNATION", u: "../images/pptgames/Flowers/Carnation.jpg" },
    { n: "CHERRY BLOSSOM", u: "../images/pptgames/Flowers/Cherry Blossom.jpg" },
    { n: "CHRYSANTHEMUM", u: "../images/pptgames/Flowers/Chrysanthemum.jpg" },
    { n: "DAFFODIL", u: "../images/pptgames/Flowers/Daffodil.jpg" },
    { n: "DAHLIA", u: "../images/pptgames/Flowers/Dahlia.jpg" },
    { n: "DAISY", u: "../images/pptgames/Flowers/Daisy.jpg" },
    { n: "DANDELION", u: "../images/pptgames/Flowers/Dandelion.jpg" },
    { n: "FORGET-ME-NOT", u: "../images/pptgames/Flowers/Forget-Me-Not.jpg" },
    { n: "FOXGLOVE", u: "../images/pptgames/Flowers/Foxglove.jpg" },
    { n: "GARDENIA", u: "../images/pptgames/Flowers/Gardenia.jpg" },
    { n: "GERBERA DAISY", u: "../images/pptgames/Flowers/Gerbera Daisy.jpg" },
    { n: "GLADIOLUS", u: "../images/pptgames/Flowers/Gladiolus.jpg" },
    { n: "HEATHER", u: "../images/pptgames/Flowers/Heather.jpg" },
    { n: "HIBISCUS", u: "../images/pptgames/Flowers/Hibiscus.jpg" },
    { n: "HYDRANGEA", u: "../images/pptgames/Flowers/Hydrangea.jpg" },
    { n: "IRIS", u: "../images/pptgames/Flowers/Iris.jpg" },
    { n: "JASMINE", u: "../images/pptgames/Flowers/Jasmine.jpg" },
    { n: "LAVENDER", u: "../images/pptgames/Flowers/Lavender.jpg" },
    { n: "LILAC", u: "../images/pptgames/Flowers/Lilac.jpg" },
    { n: "LILY", u: "../images/pptgames/Flowers/Lily.jpg" },
    { n: "LOTUS", u: "../images/pptgames/Flowers/Lotus.jpg" },
    { n: "MAGNOLIA", u: "../images/pptgames/Flowers/Magnolia.jpg" },
    { n: "MARIGOLD", u: "../images/pptgames/Flowers/Marigold.jpg" },
    { n: "MORNING GLORY", u: "../images/pptgames/Flowers/Morning Glory.jpg" },
    { n: "NARCISSUS", u: "../images/pptgames/Flowers/Narcissus.jpg" },
    { n: "ORCHID", u: "../images/pptgames/Flowers/Orchid.jpg" },
    { n: "PANSY", u: "../images/pptgames/Flowers/Pansy.jpg" },
    { n: "PEONY", u: "../images/pptgames/Flowers/Peony.jpg" },
    { n: "PETUNIA", u: "../images/pptgames/Flowers/Petunia.jpg" },
    { n: "POINSETTIA", u: "../images/pptgames/Flowers/Poinsettia.jpg" },
    { n: "POPPY", u: "../images/pptgames/Flowers/Poppy.jpg" },
    { n: "PROTEA", u: "../images/pptgames/Flowers/Protea.jpg" },
    { n: "ROSE", u: "../images/pptgames/Flowers/Rose.jpg" },
    { n: "SNAPDRAGON", u: "../images/pptgames/Flowers/Snapdragon.jpg" },
    { n: "SUNFLOWER", u: "../images/pptgames/Flowers/Sunflower.jpg" },
    { n: "SWEET PEA", u: "../images/pptgames/Flowers/Sweet Pea.jpg" },
    { n: "TULIP", u: "../images/pptgames/Flowers/Tulip.jpg" },
    { n: "VIOLET", u: "../images/pptgames/Flowers/Violet.jpg" },
    { n: "WATER LILY", u: "../images/pptgames/Flowers/Water Lily.jpg" },
    { n: "WISTERIA", u: "../images/pptgames/Flowers/Wisteria.jpg" },
    { n: "ZINNIA", u: "../images/pptgames/Flowers/Zinnia.jpg" }
];
if (typeof window !== "undefined") window.pptFlowers = pptFlowers;
