// Roblox — images in images/pptgames/Roblox/
const pptRoblox = [
    { n: "99 NIGHTS IN THE FOREST", u: "../images/pptGames/Roblox/99 Nights in the Forest.jpg" },
    { n: "ADOPT ME!", u: "../images/pptGames/Roblox/Adopt Me!.jpg" },
    { n: "ALL STAR TOWER DEFENSE", u: "../images/pptGames/Roblox/All Star Tower Defense.jpg" },
    { n: "ANIME DEFENDERS", u: "../images/pptGames/Roblox/Anime Defenders.jpg" },
    { n: "ARSENAL", u: "../images/pptGames/Roblox/Arsenal.jpg" },
    { n: "BARRY'S PRISON RUN", u: "../images/pptGames/Roblox/BARRY\'S PRISON RUN.jpg" },
    { n: "BEDWARS", u: "../images/pptGames/Roblox/BedWars.jpg" },
    { n: "BEE SWARM SIMULATOR", u: "../images/pptGames/Roblox/Bee Swarm Simulator.jpg" },
    { n: "BERRY AVENUE RP", u: "../images/pptGames/Roblox/Berry Avenue RP.jpg" },
    { n: "BLADE BALL", u: "../images/pptGames/Roblox/Blade Ball.jpg" },
    { n: "BLOX FRUITS", u: "../images/pptGames/Roblox/Blox Fruits.jpg" },
    { n: "BLUE LOCK RIVALS", u: "../images/pptGames/Roblox/Blue Lock Rivals.jpg" },
    { n: "BROOKHAVEN RP", u: "../images/pptGames/Roblox/Brookhaven RP.jpg" },
    { n: "BUILD A BOAT FOR TREASURE", u: "../images/pptGames/Roblox/Build A Boat For Treasure.jpg" },
    { n: "CATALOG AVATAR CREATOR", u: "../images/pptGames/Roblox/Catalog Avatar Creator.jpg" },
    { n: "DOORS", u: "../images/pptGames/Roblox/DOORS.jpg" },
    { n: "DANDY’S WORLD", u: "../images/pptGames/Roblox/Dandy’s World.jpg" },
    { n: "DEAD RAILS", u: "../images/pptGames/Roblox/Dead Rails.jpg" },
    { n: "DRESS TO IMPRESS", u: "../images/pptGames/Roblox/Dress To Impress.jpg" },
    { n: "ESCAPE TSUNAMI FOR BRAINROTS", u: "../images/pptGames/Roblox/Escape Tsunami For Brainrots.jpg" },
    { n: "EVADE", u: "../images/pptGames/Roblox/Evade.jpg" },
    { n: "FISCH", u: "../images/pptGames/Roblox/Fisch.jpg" },
    { n: "FISH IT", u: "../images/pptGames/Roblox/Fish It.jpg" },
    { n: "FLEE THE FACILITY", u: "../images/pptGames/Roblox/Flee the Facility.jpg" },
    { n: "FORSAKEN", u: "../images/pptGames/Roblox/Forsaken.jpg" },
    { n: "GROW A GARDEN", u: "../images/pptGames/Roblox/Grow a Garden.jpg" },
    { n: "HIDE AND SEEK EXTREME", u: "../images/pptGames/Roblox/Hide and Seek Extreme.jpg" },
    { n: "JAILBREAK", u: "../images/pptGames/Roblox/Jailbreak.jpg" },
    { n: "JUJUTSU SHENANIGANS", u: "../images/pptGames/Roblox/Jujutsu Shenanigans.jpg" },
    { n: "KING LEGACY", u: "../images/pptGames/Roblox/King Legacy.jpg" },
    { n: "LIVETOPIA", u: "../images/pptGames/Roblox/Livetopia.jpg" },
    { n: "MEEPCITY", u: "../images/pptGames/Roblox/MeepCity.jpg" },
    { n: "MURDER MYSTERY 2", u: "../images/pptGames/Roblox/Murder Mystery 2.jpg" },
    { n: "NATURAL DISASTER SURVIVAL", u: "../images/pptGames/Roblox/Natural Disaster Survival.jpg" },
    { n: "PLS DONATE", u: "../images/pptGames/Roblox/PLS DONATE.jpg" },
    { n: "PET SIMULATOR X", u: "../images/pptGames/Roblox/Pet Simulator X.jpg" },
    { n: "PIGGY", u: "../images/pptGames/Roblox/Piggy.jpg" },
    { n: "PLANTS VS BRAINROTS", u: "../images/pptGames/Roblox/Plants Vs Brainrots.jpg" },
    { n: "RIVALS", u: "../images/pptGames/Roblox/RIVALS.jpg" },
    { n: "RAINBOW FRIENDS", u: "../images/pptGames/Roblox/Rainbow Friends.jpg" },
    { n: "ROYALE HIGH", u: "../images/pptGames/Roblox/Royale High.jpg" },
    { n: "SLAP BATTLES", u: "../images/pptGames/Roblox/Slap Battles.jpg" },
    { n: "STEAL A BRAINROT", u: "../images/pptGames/Roblox/Steal a Brainrot.jpg" },
    { n: "THE STRONGEST BATTLEGROUNDS", u: "../images/pptGames/Roblox/The Strongest Battlegrounds.jpg" },
    { n: "TOILET TOWER DEFENSE", u: "../images/pptGames/Roblox/Toilet Tower Defense.jpg" },
    { n: "TOWER DEFENSE SIMULATOR", u: "../images/pptGames/Roblox/Tower Defense Simulator.jpg" },
    { n: "TOWER OF HELL", u: "../images/pptGames/Roblox/Tower of Hell.jpg" },
    { n: "TOWER OF MISERY", u: "../images/pptGames/Roblox/Tower of Misery.jpg" },
    { n: "WELCOME TO BLOXBURG", u: "../images/pptGames/Roblox/Welcome to Bloxburg.jpg" },
    { n: "WORK AT A PIZZA PLACE", u: "../images/pptGames/Roblox/Work at a Pizza Place.jpg" }
];
if (typeof window !== "undefined") window.pptRoblox = pptRoblox;
