// Typing — images in images/pptgames/Typing/
const pptTyping = [
    { n: "A", u: "../images/pptgames/Typing/A.jpg" },
    { n: "APOSTROPHE", u: "../images/pptgames/Typing/Apostrophe.jpg" },
    { n: "B", u: "../images/pptgames/Typing/B.jpg" },
    { n: "BACKQUOTE", u: "../images/pptgames/Typing/Backquote.jpg" },
    { n: "BACKSLASH", u: "../images/pptgames/Typing/Backslash.jpg" },
    { n: "BACKSPACE, DELETE", u: "../images/pptgames/Typing/Backspace, Delete.jpg" },
    { n: "C", u: "../images/pptgames/Typing/C.jpg" },
    { n: "CAPS LOCK", u: "../images/pptgames/Typing/Caps Lock.jpg" },
    { n: "COMMA", u: "../images/pptgames/Typing/Comma.jpg" },
    { n: "D", u: "../images/pptgames/Typing/D.jpg" },
    { n: "DASH, MINUS", u: "../images/pptgames/Typing/Dash, Minus.jpg" },
    { n: "E", u: "../images/pptgames/Typing/E.jpg" },
    { n: "EQUAL", u: "../images/pptgames/Typing/Equal.jpg" },
    { n: "F", u: "../images/pptgames/Typing/F.jpg" },
    { n: "G", u: "../images/pptgames/Typing/G.jpg" },
    { n: "H", u: "../images/pptgames/Typing/H.jpg" },
    { n: "I", u: "../images/pptgames/Typing/I.jpg" },
    { n: "J", u: "../images/pptgames/Typing/J.jpg" },
    { n: "K", u: "../images/pptgames/Typing/K.jpg" },
    { n: "L", u: "../images/pptgames/Typing/L.jpg" },
    { n: "LEFT BRACKET", u: "../images/pptgames/Typing/Left Bracket.jpg" },
    { n: "M", u: "../images/pptgames/Typing/M.jpg" },
    { n: "N", u: "../images/pptgames/Typing/N.jpg" },
    { n: "O", u: "../images/pptgames/Typing/O.jpg" },
    { n: "P", u: "../images/pptgames/Typing/P.jpg" },
    { n: "PERIOD", u: "../images/pptgames/Typing/Period.jpg" },
    { n: "Q", u: "../images/pptgames/Typing/Q.jpg" },
    { n: "R", u: "../images/pptgames/Typing/R.jpg" },
    { n: "RIGHT BRACKET", u: "../images/pptgames/Typing/Right Bracket.jpg" },
    { n: "S", u: "../images/pptgames/Typing/S.jpg" },
    { n: "SEMI-COLON", u: "../images/pptgames/Typing/Semi-colon.jpg" },
    { n: "SLASH", u: "../images/pptgames/Typing/Slash.jpg" },
    { n: "T", u: "../images/pptgames/Typing/T.jpg" },
    { n: "TAB", u: "../images/pptgames/Typing/Tab.jpg" },
    { n: "U", u: "../images/pptgames/Typing/U.jpg" },
    { n: "V", u: "../images/pptgames/Typing/V.jpg" },
    { n: "W", u: "../images/pptgames/Typing/W.jpg" },
    { n: "X", u: "../images/pptgames/Typing/X.jpg" },
    { n: "Y", u: "../images/pptgames/Typing/Y.jpg" },
    { n: "Z", u: "../images/pptgames/Typing/Z.jpg" }
];
if (typeof window !== "undefined") window.pptTyping = pptTyping;
