// Tools — images in images/pptgames/Tools/
const pptTools = [
    { n: "ALLEN, HEX WRENCH", u: "../images/pptgames/Tools/Allen, Hex Wrench.jpg" },
    { n: "AXE", u: "../images/pptgames/Tools/Axe.jpg" },
    { n: "BOLT", u: "../images/pptgames/Tools/Bolt.jpg" },
    { n: "CAULKING GUN", u: "../images/pptgames/Tools/Caulking Gun.jpg" },
    { n: "CHISEL", u: "../images/pptgames/Tools/Chisel.jpg" },
    { n: "CIRCULAR SAW", u: "../images/pptgames/Tools/Circular Saw.jpg" },
    { n: "CLAMP, C-CLAMP", u: "../images/pptgames/Tools/Clamp, C-Clamp.jpg" },
    { n: "CROWBAR", u: "../images/pptgames/Tools/Crowbar.jpg" },
    { n: "DREMEL, ROTARY TOOL", u: "../images/pptgames/Tools/Dremel, Rotary Tool.jpg" },
    { n: "DRILL", u: "../images/pptgames/Tools/Drill.jpg" },
    { n: "FILE", u: "../images/pptgames/Tools/File.jpg" },
    { n: "FLASHLIGHT", u: "../images/pptgames/Tools/Flashlight.jpg" },
    { n: "HACKSAW", u: "../images/pptgames/Tools/Hacksaw.jpg" },
    { n: "HAMMER", u: "../images/pptgames/Tools/Hammer.jpg" },
    { n: "HEAT GUN", u: "../images/pptgames/Tools/Heat Gun.jpg" },
    { n: "LADDER", u: "../images/pptgames/Tools/Ladder.jpg" },
    { n: "LEVEL", u: "../images/pptgames/Tools/Level.jpg" },
    { n: "MALLET", u: "../images/pptgames/Tools/Mallet.jpg" },
    { n: "MULTIMETER", u: "../images/pptgames/Tools/Multimeter.jpg" },
    { n: "NAILS", u: "../images/pptgames/Tools/Nails.jpg" },
    { n: "NUT", u: "../images/pptgames/Tools/Nut.jpg" },
    { n: "PAINT ROLLER", u: "../images/pptgames/Tools/Paint Roller.jpg" },
    { n: "PAINTBRUSH", u: "../images/pptgames/Tools/Paintbrush.jpg" },
    { n: "PICKAXE", u: "../images/pptgames/Tools/Pickaxe.jpg" },
    { n: "PLIERS", u: "../images/pptgames/Tools/Pliers.jpg" },
    { n: "SANDER", u: "../images/pptgames/Tools/Sander.jpg" },
    { n: "SAW", u: "../images/pptgames/Tools/Saw.jpg" },
    { n: "SCREWDRIVER", u: "../images/pptgames/Tools/Screwdriver.jpg" },
    { n: "SCREWS", u: "../images/pptgames/Tools/Screws.jpg" },
    { n: "SHOVEL", u: "../images/pptgames/Tools/Shovel.jpg" },
    { n: "SOCKET WRENCH, RATCHET", u: "../images/pptgames/Tools/Socket Wrench, Ratchet.jpg" },
    { n: "STAPLE GUN", u: "../images/pptgames/Tools/Staple Gun.jpg" },
    { n: "STUD FINDER", u: "../images/pptgames/Tools/Stud Finder.jpg" },
    { n: "TAPE MEASURE", u: "../images/pptgames/Tools/Tape Measure.jpg" },
    { n: "TROWEL", u: "../images/pptgames/Tools/Trowel.jpg" },
    { n: "UTILITY KNIFE", u: "../images/pptgames/Tools/Utility Knife.jpg" },
    { n: "VICE", u: "../images/pptgames/Tools/Vice.jpg" },
    { n: "WHEELBARROW", u: "../images/pptgames/Tools/Wheelbarrow.jpg" },
    { n: "WIRE STRIPPER", u: "../images/pptgames/Tools/Wire Stripper.jpg" },
    { n: "WRENCH", u: "../images/pptgames/Tools/Wrench.jpg" }
];
if (typeof window !== "undefined") window.pptTools = pptTools;
