// Bugs — images in images/pptgames/Bugs/
const pptBugs = [
    { n: "ANT", u: "../images/pptgames/Bugs/Ant.jpg" },
    { n: "ANTLION", u: "../images/pptgames/Bugs/Antlion.jpg" },
    { n: "APHID", u: "../images/pptgames/Bugs/Aphid.jpg" },
    { n: "BED BUG", u: "../images/pptgames/Bugs/Bed Bug.jpg" },
    { n: "BLACK WIDOW", u: "../images/pptgames/Bugs/Black Widow.jpg" },
    { n: "BUMBLEBEE", u: "../images/pptgames/Bugs/Bumblebee.jpg" },
    { n: "BUTTERFLY", u: "../images/pptgames/Bugs/Butterfly.jpg" },
    { n: "CATERPILLAR", u: "../images/pptgames/Bugs/Caterpillar.jpg" },
    { n: "CENTIPEDE", u: "../images/pptgames/Bugs/Centipede.jpg" },
    { n: "CICADA", u: "../images/pptgames/Bugs/Cicada.jpg" },
    { n: "COCKROACH", u: "../images/pptgames/Bugs/Cockroach.jpg" },
    { n: "CRICKET", u: "../images/pptgames/Bugs/Cricket.jpg" },
    { n: "DADDY LONGLEGS", u: "../images/pptgames/Bugs/Daddy Longlegs.jpg" },
    { n: "DRAGONFLY", u: "../images/pptgames/Bugs/Dragonfly.jpg" },
    { n: "DUNG BEETLE", u: "../images/pptgames/Bugs/Dung Beetle.jpg" },
    { n: "EARWIG", u: "../images/pptgames/Bugs/Earwig.jpg" },
    { n: "FIREFLY", u: "../images/pptgames/Bugs/Firefly.jpg" },
    { n: "FLEA", u: "../images/pptgames/Bugs/Flea.jpg" },
    { n: "GRASSHOPPER, LOCUST", u: "../images/pptgames/Bugs/Grasshopper, Locust.jpg" },
    { n: "HONEYBEE", u: "../images/pptgames/Bugs/Honeybee.jpg" },
    { n: "HOUSEFLY, FLY", u: "../images/pptgames/Bugs/Housefly, Fly.jpg" },
    { n: "JUNE BUG", u: "../images/pptgames/Bugs/June Bug.jpg" },
    { n: "LADYBUG", u: "../images/pptgames/Bugs/Ladybug.jpg" },
    { n: "LOUSE, LICE", u: "../images/pptgames/Bugs/Louse, Lice.jpg" },
    { n: "MILLIPEDE", u: "../images/pptgames/Bugs/Millipede.jpg" },
    { n: "MOSQUITO", u: "../images/pptgames/Bugs/Mosquito.jpg" },
    { n: "MOTH", u: "../images/pptgames/Bugs/Moth.jpg" },
    { n: "PILL BUG, ROLY POLY", u: "../images/pptgames/Bugs/Pill Bug, Roly Poly.jpg" },
    { n: "PRAYING MANTIS", u: "../images/pptgames/Bugs/Praying Mantis.jpg" },
    { n: "SCORPION", u: "../images/pptgames/Bugs/Scorpion.jpg" },
    { n: "SILVERFISH", u: "../images/pptgames/Bugs/Silverfish.jpg" },
    { n: "SPIDER (HOUSE)", u: "../images/pptgames/Bugs/Spider (House).jpg" },
    { n: "STAG BEETLE", u: "../images/pptgames/Bugs/Stag Beetle.jpg" },
    { n: "STINK BUG", u: "../images/pptgames/Bugs/Stink Bug.jpg" },
    { n: "TARANTULA", u: "../images/pptgames/Bugs/Tarantula.jpg" },
    { n: "TERMITE", u: "../images/pptgames/Bugs/Termite.jpg" },
    { n: "TICK", u: "../images/pptgames/Bugs/Tick.jpg" },
    { n: "WALKING STICK, STICK BUG", u: "../images/pptgames/Bugs/Walking Stick, Stick Bug.jpg" },
    { n: "WASP, YELLOW JACKET", u: "../images/pptgames/Bugs/Wasp, Yellow Jacket.jpg" },
    { n: "WATER STRIDER", u: "../images/pptgames/Bugs/Water Strider.jpg" }
];
if (typeof window !== "undefined") window.pptBugs = pptBugs;
