// Biology — images in images/pptgames/Biology/
const pptBiology = [
    { n: "ATP", u: "../images/pptGames/Biology/ATP.jpg" },
    { n: "ANIMAL CELL", u: "../images/pptGames/Biology/Animal Cell.jpg" },
    { n: "ANTIBODY", u: "../images/pptGames/Biology/Antibody.jpg" },
    { n: "BACTERIA", u: "../images/pptGames/Biology/Bacteria.jpg" },
    { n: "BIOME", u: "../images/pptGames/Biology/Biome.jpg" },
    { n: "CELL MEMBRANE", u: "../images/pptGames/Biology/Cell Membrane.jpg" },
    { n: "CELL WALL", u: "../images/pptGames/Biology/Cell Wall.jpg" },
    { n: "CHLOROPLAST", u: "../images/pptGames/Biology/Chloroplast.jpg" },
    { n: "CIRCULATORY SYSTEM", u: "../images/pptGames/Biology/Circulatory System.jpg" },
    { n: "DNA", u: "../images/pptGames/Biology/DNA.jpg" },
    { n: "DIGESTIVE SYSTEM", u: "../images/pptGames/Biology/Digestive System.jpg" },
    { n: "ECOSYSTEM", u: "../images/pptGames/Biology/Ecosystem.jpg" },
    { n: "ENDOPLASMIC RETICULUM", u: "../images/pptGames/Biology/Endoplasmic Reticulum.jpg" },
    { n: "ENZYME", u: "../images/pptGames/Biology/Enzyme.jpg" },
    { n: "EXCRETORY, URINARY SYSTEM", u: "../images/pptGames/Biology/Excretory, Urinary System.jpg" },
    { n: "FOOD CHAIN", u: "../images/pptGames/Biology/Food Chain.jpg" },
    { n: "FOOD WEB", u: "../images/pptGames/Biology/Food Web.jpg" },
    { n: "GENE", u: "../images/pptGames/Biology/Gene.jpg" },
    { n: "GOLGI APPARATUS", u: "../images/pptGames/Biology/Golgi Apparatus.jpg" },
    { n: "MEIOSIS", u: "../images/pptGames/Biology/Meiosis.jpg" },
    { n: "METAMORPHOSIS", u: "../images/pptGames/Biology/Metamorphosis.jpg" },
    { n: "MICROSCOPE", u: "../images/pptGames/Biology/Microscope.jpg" },
    { n: "MITOCHONDRIA", u: "../images/pptGames/Biology/Mitochondria.jpg" },
    { n: "MITOSIS", u: "../images/pptGames/Biology/Mitosis.jpg" },
    { n: "MUSCULAR SYSTEM", u: "../images/pptGames/Biology/Muscular System.jpg" },
    { n: "NERVOUS SYSTEM", u: "../images/pptGames/Biology/Nervous System.jpg" },
    { n: "NEURON (NERVE CELL)", u: "../images/pptGames/Biology/Neuron (Nerve Cell).jpg" },
    { n: "NUCLEOTIDE", u: "../images/pptGames/Biology/Nucleotide.jpg" },
    { n: "NUCLEUS", u: "../images/pptGames/Biology/Nucleus.jpg" },
    { n: "OSMOSIS", u: "../images/pptGames/Biology/Osmosis.jpg" },
    { n: "PETRI DISH", u: "../images/pptGames/Biology/Petri Dish.jpg" },
    { n: "PHOTOSYNTHESIS", u: "../images/pptGames/Biology/Photosynthesis.jpg" },
    { n: "PLANT CELL", u: "../images/pptGames/Biology/Plant Cell.jpg" },
    { n: "PUNNETT SQUARE", u: "../images/pptGames/Biology/Punnett Square.jpg" },
    { n: "RED BLOOD CELL", u: "../images/pptGames/Biology/Red Blood Cell.jpg" },
    { n: "RESPIRATORY SYSTEM", u: "../images/pptGames/Biology/Respiratory System.jpg" },
    { n: "SKELETON (SKELETAL SYSTEM)", u: "../images/pptGames/Biology/Skeleton (Skeletal System).jpg" },
    { n: "SKIN (INTEGUMENTARY SYSTEM)", u: "../images/pptGames/Biology/Skin (Integumentary System).jpg" },
    { n: "SYMBIOSIS", u: "../images/pptGames/Biology/Symbiosis.jpg" },
    { n: "TAXONOMY", u: "../images/pptGames/Biology/Taxonomy.jpg" },
    { n: "VACUOLE", u: "../images/pptGames/Biology/Vacuole.jpg" },
    { n: "VIRUS", u: "../images/pptGames/Biology/Virus.jpg" },
    { n: "WHITE BLOOD CELL", u: "../images/pptGames/Biology/White Blood Cell.jpg" },
    { n: "X CHROMOSOME", u: "../images/pptGames/Biology/X Chromosome.jpg" },
    { n: "Y CHROMOSOME", u: "../images/pptGames/Biology/Y Chromosome.jpg" }
];
if (typeof window !== "undefined") window.pptBiology = pptBiology;
