// Babies — images in images/pptgames/Babies/
const pptBabies = [
    { n: "BABY CARRIER", u: "../images/pptGames/Babies/Baby Carrier.jpg" },
    { n: "BABY FOOD", u: "../images/pptGames/Babies/Baby Food.jpg" },
    { n: "BABY MONITOR", u: "../images/pptGames/Babies/Baby Monitor.jpg" },
    { n: "BABY POWDER", u: "../images/pptGames/Babies/Baby Powder.jpg" },
    { n: "BABY SHAMPOO, WASH", u: "../images/pptGames/Babies/Baby Shampoo, Wash.jpg" },
    { n: "BASSINET", u: "../images/pptGames/Babies/Bassinet.jpg" },
    { n: "BATH TUB", u: "../images/pptGames/Babies/Bath Tub.jpg" },
    { n: "BIB", u: "../images/pptGames/Babies/Bib.jpg" },
    { n: "BLANKET, SWADDLE", u: "../images/pptGames/Babies/Blanket, Swaddle.jpg" },
    { n: "BOOTIES", u: "../images/pptGames/Babies/Booties.jpg" },
    { n: "BOTTLE", u: "../images/pptGames/Babies/Bottle.jpg" },
    { n: "BOUNCER, JUMPER", u: "../images/pptGames/Babies/Bouncer, Jumper.jpg" },
    { n: "BREAST PUMP", u: "../images/pptGames/Babies/Breast Pump.jpg" },
    { n: "BULB SYRINGE, NASAL ASPIRATOR", u: "../images/pptGames/Babies/Bulb Syringe, Nasal Aspirator.jpg" },
    { n: "BURP CLOTH", u: "../images/pptGames/Babies/Burp Cloth.jpg" },
    { n: "CAR SEAT", u: "../images/pptGames/Babies/Car Seat.jpg" },
    { n: "CHANGING TABLE", u: "../images/pptGames/Babies/Changing Table.jpg" },
    { n: "CRIB", u: "../images/pptGames/Babies/Crib.jpg" },
    { n: "DIAPER BAG", u: "../images/pptGames/Babies/Diaper Bag.jpg" },
    { n: "DIAPER GENIE", u: "../images/pptGames/Babies/Diaper Genie.jpg" },
    { n: "DIAPER", u: "../images/pptGames/Babies/Diaper.jpg" },
    { n: "FORMULA", u: "../images/pptGames/Babies/Formula.jpg" },
    { n: "GERBER BABY", u: "../images/pptGames/Babies/Gerber Baby.jpg" },
    { n: "HIGH CHAIR", u: "../images/pptGames/Babies/High Chair.jpg" },
    { n: "HOODED TOWEL", u: "../images/pptGames/Babies/Hooded Towel.jpg" },
    { n: "MOBILE", u: "../images/pptGames/Babies/Mobile.jpg" },
    { n: "NURSING PILLOW", u: "../images/pptGames/Babies/Nursing Pillow.jpg" },
    { n: "ONESIE", u: "../images/pptGames/Babies/Onesie.jpg" },
    { n: "PACIFIER, BINKY (SOOTHIE)", u: "../images/pptGames/Babies/Pacifier, Binky (Soothie).jpg" },
    { n: "PLAYPEN", u: "../images/pptGames/Babies/Playpen.jpg" },
    { n: "RATTLE", u: "../images/pptGames/Babies/Rattle.jpg" },
    { n: "SIPPY CUP", u: "../images/pptGames/Babies/Sippy Cup.jpg" },
    { n: "SLEEPER", u: "../images/pptGames/Babies/Sleeper.jpg" },
    { n: "STROLLER", u: "../images/pptGames/Babies/Stroller.jpg" },
    { n: "SWING, ROCKER", u: "../images/pptGames/Babies/Swing, Rocker.jpg" },
    { n: "TEDDY BEAR", u: "../images/pptGames/Babies/Teddy Bear.jpg" },
    { n: "TEETHER, TEETHING TOY", u: "../images/pptGames/Babies/Teether, Teething Toy.jpg" },
    { n: "THERMOMETER", u: "../images/pptGames/Babies/Thermometer.jpg" },
    { n: "WALKER", u: "../images/pptGames/Babies/Walker.jpg" },
    { n: "WIPES", u: "../images/pptGames/Babies/Wipes.jpg" }
];
if (typeof window !== "undefined") window.pptBabies = pptBabies;
