// Fruit — images in images/pptgames/Fruit/
const pptFruit = [
    { n: "APPLE", u: "../images/pptgames/Fruit/Apple.jpg" },
    { n: "APRICOT", u: "../images/pptgames/Fruit/Apricot.jpg" },
    { n: "AVOCADO", u: "../images/pptgames/Fruit/Avocado.jpg" },
    { n: "BANANA", u: "../images/pptgames/Fruit/Banana.jpg" },
    { n: "BLACKBERRY", u: "../images/pptgames/Fruit/Blackberry.jpg" },
    { n: "BLUEBERRY", u: "../images/pptgames/Fruit/Blueberry.jpg" },
    { n: "CANTALOUPE", u: "../images/pptgames/Fruit/Cantaloupe.jpg" },
    { n: "CHERRIES", u: "../images/pptgames/Fruit/Cherries.jpg" },
    { n: "COCONUT", u: "../images/pptgames/Fruit/Coconut.jpg" },
    { n: "CRANBERRY", u: "../images/pptgames/Fruit/Cranberry.jpg" },
    { n: "DRAGONFRUIT", u: "../images/pptgames/Fruit/Dragonfruit.jpg" },
    { n: "FIG", u: "../images/pptgames/Fruit/Fig.jpg" },
    { n: "GRAPEFRUIT", u: "../images/pptgames/Fruit/Grapefruit.jpg" },
    { n: "GRAPES", u: "../images/pptgames/Fruit/Grapes.jpg" },
    { n: "GUAVA", u: "../images/pptgames/Fruit/Guava.jpg" },
    { n: "HONEYDEW MELON", u: "../images/pptgames/Fruit/Honeydew Melon.jpg" },
    { n: "JACKFRUIT", u: "../images/pptgames/Fruit/Jackfruit.jpg" },
    { n: "KIWI", u: "../images/pptgames/Fruit/Kiwi.jpg" },
    { n: "LEMON", u: "../images/pptgames/Fruit/Lemon.jpg" },
    { n: "LIME", u: "../images/pptgames/Fruit/Lime.jpg" },
    { n: "LYCHEE", u: "../images/pptgames/Fruit/Lychee.jpg" },
    { n: "MANGO", u: "../images/pptgames/Fruit/Mango.jpg" },
    { n: "MANGOSTEEN", u: "../images/pptgames/Fruit/Mangosteen.jpg" },
    { n: "NECTARINE", u: "../images/pptgames/Fruit/Nectarine.jpg" },
    { n: "ORANGE", u: "../images/pptgames/Fruit/Orange.jpg" },
    { n: "PAPAYA", u: "../images/pptgames/Fruit/Papaya.jpg" },
    { n: "PASSIONFRUIT", u: "../images/pptgames/Fruit/Passionfruit.jpg" },
    { n: "PEACH", u: "../images/pptgames/Fruit/Peach.jpg" },
    { n: "PEAR", u: "../images/pptgames/Fruit/Pear.jpg" },
    { n: "PERSIMMON", u: "../images/pptgames/Fruit/Persimmon.jpg" },
    { n: "PINEAPPLE", u: "../images/pptgames/Fruit/Pineapple.jpg" },
    { n: "PLUM", u: "../images/pptgames/Fruit/Plum.jpg" },
    { n: "POMEGRANATE", u: "../images/pptgames/Fruit/Pomegranate.jpg" },
    { n: "RAMBUTAN", u: "../images/pptgames/Fruit/Rambutan.jpg" },
    { n: "RASPBERRY", u: "../images/pptgames/Fruit/Raspberry.jpg" },
    { n: "STARFRUIT", u: "../images/pptgames/Fruit/Starfruit.jpg" },
    { n: "STRAWBERRY", u: "../images/pptgames/Fruit/Strawberry.jpg" },
    { n: "TANGERINE", u: "../images/pptgames/Fruit/Tangerine.jpg" },
    { n: "TOMATO", u: "../images/pptgames/Fruit/Tomato.jpg" },
    { n: "WATERMELON", u: "../images/pptgames/Fruit/Watermelon.jpg" }
];
if (typeof window !== "undefined") window.pptFruit = pptFruit;
