// Fitness — images in images/pptgames/Fitness/
const pptFitness = [
    { n: "BARBELL", u: "../images/pptGames/Fitness/Barbell.jpg" },
    { n: "BENCH PRESS", u: "../images/pptGames/Fitness/Bench Press.jpg" },
    { n: "BICEP CURL", u: "../images/pptGames/Fitness/Bicep Curl.jpg" },
    { n: "BURPEE", u: "../images/pptGames/Fitness/Burpee.jpg" },
    { n: "DUFFLE BAG, GYM BAG", u: "../images/pptGames/Fitness/Duffle Bag, Gym Bag.jpg" },
    { n: "DUMBBELL", u: "../images/pptGames/Fitness/Dumbbell.jpg" },
    { n: "ELLIPTICAL", u: "../images/pptGames/Fitness/Elliptical.jpg" },
    { n: "EXERCISE, YOGA BALL", u: "../images/pptGames/Fitness/Exercise, Yoga Ball.jpg" },
    { n: "FITBIT", u: "../images/pptGames/Fitness/Fitbit.jpg" },
    { n: "FOAM ROLLER", u: "../images/pptGames/Fitness/Foam Roller.jpg" },
    { n: "HEART RATE MONITOR", u: "../images/pptGames/Fitness/Heart Rate Monitor.jpg" },
    { n: "JUMP ROPE", u: "../images/pptGames/Fitness/Jump Rope.jpg" },
    { n: "KETTLEBELL", u: "../images/pptGames/Fitness/Kettlebell.jpg" },
    { n: "LEGGINGS", u: "../images/pptGames/Fitness/Leggings.jpg" },
    { n: "LUNGE", u: "../images/pptGames/Fitness/Lunge.jpg" },
    { n: "MEDICINE BALL", u: "../images/pptGames/Fitness/Medicine Ball.jpg" },
    { n: "PILATES RING", u: "../images/pptGames/Fitness/Pilates Ring.jpg" },
    { n: "PLANK", u: "../images/pptGames/Fitness/Plank.jpg" },
    { n: "PROTEIN SHAKE", u: "../images/pptGames/Fitness/Protein Shake.jpg" },
    { n: "PULL UP, CHIN UP", u: "../images/pptGames/Fitness/Pull Up, Chin Up.jpg" },
    { n: "PUSH UP", u: "../images/pptGames/Fitness/Push Up.jpg" },
    { n: "RESISTANCE BAND", u: "../images/pptGames/Fitness/Resistance Band.jpg" },
    { n: "ROWING MACHINE", u: "../images/pptGames/Fitness/Rowing Machine.jpg" },
    { n: "RUNNING SHOES, SNEAKERS", u: "../images/pptGames/Fitness/Running Shoes, Sneakers.jpg" },
    { n: "SIT UP", u: "../images/pptGames/Fitness/Sit Up.jpg" },
    { n: "SPORTS BRA", u: "../images/pptGames/Fitness/Sports Bra.jpg" },
    { n: "SQUAT RACK", u: "../images/pptGames/Fitness/Squat Rack.jpg" },
    { n: "STATIONARY, EXERCISE BIKE", u: "../images/pptGames/Fitness/Stationary, Exercise Bike.jpg" },
    { n: "STEP AEROBICS, WORKOUT", u: "../images/pptGames/Fitness/Step Aerobics, Workout.jpg" },
    { n: "STOPWATCH", u: "../images/pptGames/Fitness/Stopwatch.jpg" },
    { n: "SWEATBAND", u: "../images/pptGames/Fitness/Sweatband.jpg" },
    { n: "TANK TOP", u: "../images/pptGames/Fitness/Tank Top.jpg" },
    { n: "TREADMILL", u: "../images/pptGames/Fitness/Treadmill.jpg" },
    { n: "TRICEP DIP", u: "../images/pptGames/Fitness/Tricep Dip.jpg" },
    { n: "WATER BOTTLE", u: "../images/pptGames/Fitness/Water Bottle.jpg" },
    { n: "WEIGHT BENCH", u: "../images/pptGames/Fitness/Weight Bench.jpg" },
    { n: "WEIGHT PLATE", u: "../images/pptGames/Fitness/Weight Plate.jpg" },
    { n: "WRIST WRAPS", u: "../images/pptGames/Fitness/Wrist Wraps.jpg" },
    { n: "YOGA MAT", u: "../images/pptGames/Fitness/Yoga Mat.jpg" },
    { n: "ZUMBA", u: "../images/pptGames/Fitness/Zumba.jpg" }
];
if (typeof window !== "undefined") window.pptFitness = pptFitness;
