// LEGO — images in images/pptgames/LEGO/
const pptLego = [
    { n: "4-99", u: "../images/pptgames/LEGO/4-99.jpg" },
    { n: "ADULT FAN OF LEGO", u: "../images/pptgames/LEGO/Adult Fan of Lego.jpg" },
    { n: "BENNY THE SPACEMAN", u: "../images/pptgames/LEGO/Benny the Spaceman.jpg" },
    { n: "BRICK SEPARATOR", u: "../images/pptgames/LEGO/Brick Separator.jpg" },
    { n: "BRICKHEADZ", u: "../images/pptgames/LEGO/BrickHeadz.jpg" },
    { n: "BRICKLINK LOGO", u: "../images/pptgames/LEGO/BrickLink Logo.jpg" },
    { n: "BRICKCON LOGO", u: "../images/pptgames/LEGO/Brickcon Logo.jpg" },
    { n: "BRICKSET LOGO", u: "../images/pptgames/LEGO/Brickset Logo.jpg" },
    { n: "DOUBLE DECKER COUCH", u: "../images/pptgames/LEGO/Double Decker Couch.jpg" },
    { n: "EMMET", u: "../images/pptgames/LEGO/Emmet.jpg" },
    { n: "GREEBLE, GREEBLING", u: "../images/pptgames/LEGO/Greeble, Greebling.jpg" },
    { n: "GREEN BASEPLATE", u: "../images/pptgames/LEGO/Green Baseplate.jpg" },
    { n: "ILLEGAL BUILD TECHNIQUE", u: "../images/pptgames/LEGO/Illegal Build Technique.jpg" },
    { n: "LEGO ARCHITECTURE", u: "../images/pptgames/LEGO/LEGO Architecture.jpg" },
    { n: "LEGO BIONICLE", u: "../images/pptgames/LEGO/LEGO BIONICLE.jpg" },
    { n: "LEGO BOTANICAL COLLECTION", u: "../images/pptgames/LEGO/LEGO Botanical Collection.jpg" },
    { n: "LEGO CITY", u: "../images/pptgames/LEGO/LEGO City.jpg" },
    { n: "LEGO CREATOR 3-IN-1", u: "../images/pptgames/LEGO/LEGO Creator 3-in-1.jpg" },
    { n: "LEGO DUPLO", u: "../images/pptgames/LEGO/LEGO DUPLO.jpg" },
    { n: "LEGO FRIENDS", u: "../images/pptgames/LEGO/LEGO Friends.jpg" },
    { n: "LEGO HARRY POTTER", u: "../images/pptgames/LEGO/LEGO Harry Potter.jpg" },
    { n: "LEGO MASTERS", u: "../images/pptgames/LEGO/LEGO Masters.jpg" },
    { n: "LEGO MOVIE 2", u: "../images/pptgames/LEGO/LEGO Movie 2.jpg" },
    { n: "LEGO MOVIE", u: "../images/pptgames/LEGO/LEGO Movie.jpg" },
    { n: "LEGO NINJAGO", u: "../images/pptgames/LEGO/LEGO Ninjago.jpg" },
    { n: "LEGO SPEED CHAMPIONS", u: "../images/pptgames/LEGO/LEGO Speed Champions.jpg" },
    { n: "LEGO STAR WARS", u: "../images/pptgames/LEGO/LEGO Star Wars.jpg" },
    { n: "LEGO TECHNIC", u: "../images/pptgames/LEGO/LEGO Technic.jpg" },
    { n: "LEGOLAND", u: "../images/pptgames/LEGO/LEGOLAND.jpg" },
    { n: "LEGO BUILDER APP", u: "../images/pptgames/LEGO/Lego Builder App.jpg" },
    { n: "LEGO CLASSIC", u: "../images/pptgames/LEGO/Lego Classic.jpg" },
    { n: "LEGO DIGITAL DESIGNER (LDD)", u: "../images/pptgames/LEGO/Lego Digital Designer (LDD).jpg" },
    { n: "LEGO INSIDERS CARD", u: "../images/pptgames/LEGO/Lego Insiders Card.jpg" },
    { n: "LEGO MASTERS TROPHY", u: "../images/pptgames/LEGO/Lego Masters Trophy.jpg" },
    { n: "LEGO VIP BLUE CARD", u: "../images/pptgames/LEGO/Lego VIP Blue Card.jpg" },
    { n: "MR. GOLD MINIFIGURE", u: "../images/pptgames/LEGO/Mr. Gold Minifigure.jpg" },
    { n: "NICE PARTS USE", u: "../images/pptgames/LEGO/Nice Parts Use.jpg" },
    { n: "PICK-A-BRICK CUP", u: "../images/pptgames/LEGO/Pick-a-Brick Cup.jpg" },
    { n: "PICK-A-BRICK WALL", u: "../images/pptgames/LEGO/Pick-a-Brick Wall.jpg" },
    { n: "PRESIDENT BUSINESS, LORD BUSINESS", u: "../images/pptgames/LEGO/President Business, Lord Business.jpg" },
    { n: "RED 2X4 BRICK", u: "../images/pptgames/LEGO/Red 2x4 Brick.jpg" },
    { n: "THE GOLDEN SEPARATOR", u: "../images/pptgames/LEGO/The Golden Separator.jpg" },
    { n: "UNI-KITTY", u: "../images/pptgames/LEGO/Uni-Kitty.jpg" },
    { n: "WYLDSTYLE (LUCY)", u: "../images/pptgames/LEGO/Wyldstyle (Lucy).jpg" }
];
if (typeof window !== "undefined") window.pptLego = pptLego;
