// Boba — images in images/pptgames/Boba/
const pptBoba = [
    { n: "ALOE VERA", u: "../images/pptgames/Boba/Aloe Vera.jpg" },
    { n: "BOBA GUYS", u: "../images/pptgames/Boba/Boba Guys.jpg" },
    { n: "BROWN SUGAR", u: "../images/pptgames/Boba/Brown Sugar.jpg" },
    { n: "CHATIME", u: "../images/pptgames/Boba/Chatime.jpg" },
    { n: "CHEESE, MILK FOAM", u: "../images/pptgames/Boba/Cheese, Milk Foam.jpg" },
    { n: "CHOCOLATE", u: "../images/pptgames/Boba/Chocolate.jpg" },
    { n: "COCO (FRESH TEA & JUICE)", u: "../images/pptgames/Boba/CoCo (Fresh Tea & Juice).jpg" },
    { n: "COCONUT JELLY", u: "../images/pptgames/Boba/Coconut Jelly.jpg" },
    { n: "COFFEE", u: "../images/pptgames/Boba/Coffee.jpg" },
    { n: "CRYSTAL BOBA", u: "../images/pptgames/Boba/Crystal Boba.jpg" },
    { n: "GONG CHA", u: "../images/pptgames/Boba/Gong Cha.jpg" },
    { n: "GRASS JELLY", u: "../images/pptgames/Boba/Grass Jelly.jpg" },
    { n: "GREEN APPLE", u: "../images/pptgames/Boba/Green Apple.jpg" },
    { n: "HAPPY LEMON", u: "../images/pptgames/Boba/Happy Lemon.jpg" },
    { n: "HOKKAIDO MILK TEA", u: "../images/pptgames/Boba/Hokkaido Milk Tea.jpg" },
    { n: "HONEYDEW", u: "../images/pptgames/Boba/Honeydew.jpg" },
    { n: "JASMINE GREEN", u: "../images/pptgames/Boba/Jasmine Green.jpg" },
    { n: "KIWI", u: "../images/pptgames/Boba/Kiwi.jpg" },
    { n: "KUNG FU TEA", u: "../images/pptgames/Boba/Kung Fu Tea.jpg" },
    { n: "LEMON", u: "../images/pptgames/Boba/Lemon.jpg" },
    { n: "LYCHEE JELLY", u: "../images/pptgames/Boba/Lychee Jelly.jpg" },
    { n: "LYCHEE", u: "../images/pptgames/Boba/Lychee.jpg" },
    { n: "MANGO", u: "../images/pptgames/Boba/Mango.jpg" },
    { n: "MATCHA", u: "../images/pptgames/Boba/Matcha.jpg" },
    { n: "OKINAWA MILK TEA", u: "../images/pptgames/Boba/Okinawa Milk Tea.jpg" },
    { n: "ORANGE", u: "../images/pptgames/Boba/Orange.jpg" },
    { n: "PASSION FRUIT", u: "../images/pptgames/Boba/Passion Fruit.jpg" },
    { n: "PEACH", u: "../images/pptgames/Boba/Peach.jpg" },
    { n: "PINEAPPLE", u: "../images/pptgames/Boba/Pineapple.jpg" },
    { n: "POPPING BOBA", u: "../images/pptgames/Boba/Popping Boba.jpg" },
    { n: "PUDDING, EGG PUDDING", u: "../images/pptgames/Boba/Pudding, Egg Pudding.jpg" },
    { n: "RED BEAN", u: "../images/pptgames/Boba/Red Bean.jpg" },
    { n: "SHARETEA", u: "../images/pptgames/Boba/ShareTea.jpg" },
    { n: "STRAWBERRY", u: "../images/pptgames/Boba/Strawberry.jpg" },
    { n: "TAPIOCA PEARLS, BOBA BALLS", u: "../images/pptgames/Boba/Tapioca Pearls, Boba Balls.jpg" },
    { n: "TARO", u: "../images/pptgames/Boba/Taro.jpg" },
    { n: "THAI MILK TEA", u: "../images/pptgames/Boba/Thai Milk Tea.jpg" },
    { n: "TIGER SUGAR", u: "../images/pptgames/Boba/Tiger Sugar.jpg" },
    { n: "WATERMELON", u: "../images/pptgames/Boba/Watermelon.jpg" },
    { n: "WINTERMELON", u: "../images/pptgames/Boba/Wintermelon.jpg" }
];
if (typeof window !== "undefined") window.pptBoba = pptBoba;
