// Tennis — images in images/pptgames/Tennis/
const pptTennis = [
    { n: "ALLEY, DOUBLES ALLEY", u: "../images/pptGames/Tennis/Alley, Doubles Alley.jpg" },
    { n: "BACKHAND (TWO-HANDED)", u: "../images/pptGames/Tennis/Backhand (Two-handed).jpg" },
    { n: "BACKHAND", u: "../images/pptGames/Tennis/Backhand.jpg" },
    { n: "BALL BOY, BALL GIRL", u: "../images/pptGames/Tennis/Ball Boy, Ball Girl.jpg" },
    { n: "BASELINE", u: "../images/pptGames/Tennis/Baseline.jpg" },
    { n: "CENTER COURT", u: "../images/pptGames/Tennis/Center Court.jpg" },
    { n: "CENTER STRAP", u: "../images/pptGames/Tennis/Center Strap.jpg" },
    { n: "CLAY COURT", u: "../images/pptGames/Tennis/Clay Court.jpg" },
    { n: "DEUCE", u: "../images/pptGames/Tennis/Deuce.jpg" },
    { n: "DOUBLES SIDELINE", u: "../images/pptGames/Tennis/Doubles Sideline.jpg" },
    { n: "DROP SHOT", u: "../images/pptGames/Tennis/Drop Shot.jpg" },
    { n: "FOREHAND", u: "../images/pptGames/Tennis/Forehand.jpg" },
    { n: "GRASS COURT", u: "../images/pptGames/Tennis/Grass Court.jpg" },
    { n: "GRIP TAPE", u: "../images/pptGames/Tennis/Grip Tape.jpg" },
    { n: "HARD COURT", u: "../images/pptGames/Tennis/Hard Court.jpg" },
    { n: "HEADBAND", u: "../images/pptGames/Tennis/Headband.jpg" },
    { n: "LEFT SERVICE BOX", u: "../images/pptGames/Tennis/Left Service Box.jpg" },
    { n: "LINE JUDGES", u: "../images/pptGames/Tennis/Line Judges.jpg" },
    { n: "LOB", u: "../images/pptGames/Tennis/Lob.jpg" },
    { n: "NET CORD SENSOR", u: "../images/pptGames/Tennis/Net Cord Sensor.jpg" },
    { n: "NET", u: "../images/pptGames/Tennis/Net.jpg" },
    { n: "NO MAN’S LAND", u: "../images/pptGames/Tennis/No Man’s Land.jpg" },
    { n: "POLO SHIRT", u: "../images/pptGames/Tennis/Polo Shirt.jpg" },
    { n: "RIGHT SERVICE BOX", u: "../images/pptGames/Tennis/Right Service Box.jpg" },
    { n: "SERVE", u: "../images/pptGames/Tennis/Serve.jpg" },
    { n: "SERVICE LINE", u: "../images/pptGames/Tennis/Service Line.jpg" },
    { n: "SINGLES SIDELINE", u: "../images/pptGames/Tennis/Singles Sideline.jpg" },
    { n: "SKIRT, DRESS", u: "../images/pptGames/Tennis/Skirt, Dress.jpg" },
    { n: "STRINGS", u: "../images/pptGames/Tennis/Strings.jpg" },
    { n: "T (CENTER SERVICE LINE)", u: "../images/pptGames/Tennis/T (Center Service Line).jpg" },
    { n: "TENNIS BAG", u: "../images/pptGames/Tennis/Tennis Bag.jpg" },
    { n: "TENNIS BALLS", u: "../images/pptGames/Tennis/Tennis Balls.jpg" },
    { n: "TENNIS RACKET", u: "../images/pptGames/Tennis/Tennis Racket.jpg" },
    { n: "TENNIS SHOES", u: "../images/pptGames/Tennis/Tennis Shoes.jpg" },
    { n: "UMPIRE CHAIR", u: "../images/pptGames/Tennis/Umpire Chair.jpg" },
    { n: "UMPIRE", u: "../images/pptGames/Tennis/Umpire.jpg" },
    { n: "VIBRATION DAMPENER", u: "../images/pptGames/Tennis/Vibration Dampener.jpg" },
    { n: "VISOR", u: "../images/pptGames/Tennis/Visor.jpg" },
    { n: "WIMBLEDON TROPHY (CHALLENGE CUP)", u: "../images/pptGames/Tennis/Wimbledon Trophy (Challenge Cup).jpg" },
    { n: "WRISTBAND", u: "../images/pptGames/Tennis/Wristband.jpg" }
];
if (typeof window !== "undefined") window.pptTennis = pptTennis;
