// Piano — images in images/pptgames/Piano/
const pptPiano = [
    { n: "A KEY", u: "../images/pptgames/Piano/A Key.jpg" },
    { n: "ACCENT", u: "../images/pptgames/Piano/Accent.jpg" },
    { n: "B", u: "../images/pptgames/Piano/B.jpg" },
    { n: "BABY GRAND", u: "../images/pptgames/Piano/Baby Grand.jpg" },
    { n: "BB KEY", u: "../images/pptgames/Piano/Bb Key.jpg" },
    { n: "C KEY", u: "../images/pptgames/Piano/C Key.jpg" },
    { n: "C#, DB KEY", u: "../images/pptgames/Piano/C#, Db Key.jpg" },
    { n: "CRESCENDO (GETTING LOUDER)", u: "../images/pptgames/Piano/Crescendo (Getting louder).jpg" },
    { n: "D KEY", u: "../images/pptgames/Piano/D Key.jpg" },
    { n: "D#, EB KEY", u: "../images/pptgames/Piano/D#, Eb Key.jpg" },
    { n: "DAMPERS", u: "../images/pptgames/Piano/Dampers.jpg" },
    { n: "DECRESCENDO (GETTING SOFTER)", u: "../images/pptgames/Piano/Decrescendo (Getting softer).jpg" },
    { n: "DIGITAL PIANO", u: "../images/pptgames/Piano/Digital Piano.jpg" },
    { n: "E KEY", u: "../images/pptgames/Piano/E Key.jpg" },
    { n: "F KEY", u: "../images/pptgames/Piano/F Key.jpg" },
    { n: "F# KEY", u: "../images/pptgames/Piano/F# Key.jpg" },
    { n: "FERMATA (HOLD, PAUSE)", u: "../images/pptgames/Piano/Fermata (Hold, Pause).jpg" },
    { n: "FORTE (LOUD)", u: "../images/pptgames/Piano/Forte (Loud).jpg" },
    { n: "FORTISSIMO (VERY LOUD)", u: "../images/pptgames/Piano/Fortissimo (Very Loud).jpg" },
    { n: "G KEY", u: "../images/pptgames/Piano/G Key.jpg" },
    { n: "G#, AB KEY", u: "../images/pptgames/Piano/G#, Ab Key.jpg" },
    { n: "GRAND PIANO", u: "../images/pptgames/Piano/Grand Piano.jpg" },
    { n: "HAMMERS", u: "../images/pptgames/Piano/Hammers.jpg" },
    { n: "KEYBOARD", u: "../images/pptgames/Piano/Keyboard.jpg" },
    { n: "METRONOME", u: "../images/pptgames/Piano/Metronome.jpg" },
    { n: "MEZZO FORTE (MODERATELY LOUD)", u: "../images/pptgames/Piano/Mezzo Forte (Moderately Loud).jpg" },
    { n: "MEZZO PIANO (MODERATELY SOFT)", u: "../images/pptgames/Piano/Mezzo Piano (Moderately Soft).jpg" },
    { n: "MIDDLE C", u: "../images/pptgames/Piano/Middle C.jpg" },
    { n: "PIANISSIMO (VERY SOFT)", u: "../images/pptgames/Piano/Pianissimo (Very Soft).jpg" },
    { n: "PIANO (SOFT)", u: "../images/pptgames/Piano/Piano (Soft).jpg" },
    { n: "PIANO BENCH", u: "../images/pptgames/Piano/Piano Bench.jpg" },
    { n: "PIANO STRINGS", u: "../images/pptgames/Piano/Piano Strings.jpg" },
    { n: "REPEAT", u: "../images/pptgames/Piano/Repeat.jpg" },
    { n: "SFORZANDO", u: "../images/pptgames/Piano/Sforzando.jpg" },
    { n: "SOFT, UNA CORDA PEDAL", u: "../images/pptgames/Piano/Soft, Una Corda Pedal.jpg" },
    { n: "SOSTENUTO PEDAL", u: "../images/pptgames/Piano/Sostenuto Pedal.jpg" },
    { n: "STACCATO", u: "../images/pptgames/Piano/Staccato.jpg" },
    { n: "SUSTAIN PEDAL", u: "../images/pptgames/Piano/Sustain Pedal.jpg" },
    { n: "TENUTO (HOLD)", u: "../images/pptgames/Piano/Tenuto (Hold).jpg" },
    { n: "TUNER, TUNING HAMMER", u: "../images/pptgames/Piano/Tuner, Tuning Hammer.jpg" },
    { n: "TUNING PINS", u: "../images/pptgames/Piano/Tuning Pins.jpg" },
    { n: "UPRIGHT PIANO", u: "../images/pptgames/Piano/Upright Piano.jpg" }
];
if (typeof window !== "undefined") window.pptPiano = pptPiano;
