// Cereal — images in images/pptgames/Cereal/
const pptCereal = [
    { n: "ALPHA-BITS", u: "../images/pptgames/Cereal/Alpha-Bits.jpg" },
    { n: "APPLE JACKS", u: "../images/pptgames/Cereal/Apple Jacks.jpg" },
    { n: "BOO BERRY", u: "../images/pptgames/Cereal/Boo Berry.jpg" },
    { n: "CAPTAIN CRUNCH", u: "../images/pptgames/Cereal/Captain Crunch.jpg" },
    { n: "CHEERIOS", u: "../images/pptgames/Cereal/Cheerios.jpg" },
    { n: "CHEX (WHEAT)", u: "../images/pptgames/Cereal/Chex (Wheat).jpg" },
    { n: "CINNAMON TOAST CRUNCH", u: "../images/pptgames/Cereal/Cinnamon Toast Crunch.jpg" },
    { n: "COCOA KRISPIES", u: "../images/pptgames/Cereal/Cocoa Krispies.jpg" },
    { n: "COCOA PEBBLES", u: "../images/pptgames/Cereal/Cocoa Pebbles.jpg" },
    { n: "COCOA PUFFS", u: "../images/pptgames/Cereal/Cocoa Puffs.jpg" },
    { n: "COOKIE CRISP", u: "../images/pptgames/Cereal/Cookie Crisp.jpg" },
    { n: "CORN POPS", u: "../images/pptgames/Cereal/Corn Pops.jpg" },
    { n: "COUNT CHOCULA", u: "../images/pptgames/Cereal/Count Chocula.jpg" },
    { n: "CRISPIX", u: "../images/pptgames/Cereal/Crispix.jpg" },
    { n: "CRUNCH BERRIES", u: "../images/pptgames/Cereal/Crunch Berries.jpg" },
    { n: "FRANKEN BERRY", u: "../images/pptgames/Cereal/Franken Berry.jpg" },
    { n: "FROOT LOOPS", u: "../images/pptgames/Cereal/Froot Loops.jpg" },
    { n: "FROSTED FLAKES", u: "../images/pptgames/Cereal/Frosted Flakes.jpg" },
    { n: "FROSTED MINI-WHEATS", u: "../images/pptgames/Cereal/Frosted Mini-Wheats.jpg" },
    { n: "FRUITY PEBBLES", u: "../images/pptgames/Cereal/Fruity Pebbles.jpg" },
    { n: "GOLDEN GRAHAMS", u: "../images/pptgames/Cereal/Golden Grahams.jpg" },
    { n: "GRAPE-NUTS", u: "../images/pptgames/Cereal/Grape-Nuts.jpg" },
    { n: "HONEY BUNCHES OF OATS", u: "../images/pptgames/Cereal/Honey Bunches of Oats.jpg" },
    { n: "HONEY NUT CHEERIOS", u: "../images/pptgames/Cereal/Honey Nut Cheerios.jpg" },
    { n: "HONEY SMACKS", u: "../images/pptgames/Cereal/Honey Smacks.jpg" },
    { n: "HONEYCOMB", u: "../images/pptgames/Cereal/Honeycomb.jpg" },
    { n: "KIX", u: "../images/pptgames/Cereal/Kix.jpg" },
    { n: "KRAVE", u: "../images/pptgames/Cereal/Krave.jpg" },
    { n: "LIFE", u: "../images/pptgames/Cereal/Life.jpg" },
    { n: "LUCKY CHARMS", u: "../images/pptgames/Cereal/Lucky Charms.jpg" },
    { n: "OH'S", u: "../images/pptgames/Cereal/Oh\'s.jpg" },
    { n: "QUAKER OATMEAL SQUARES", u: "../images/pptgames/Cereal/Quaker Oatmeal Squares.jpg" },
    { n: "RAISIN BRAN", u: "../images/pptgames/Cereal/Raisin Bran.jpg" },
    { n: "REESE'S PUFFS", u: "../images/pptgames/Cereal/Reese\'s Puffs.jpg" },
    { n: "RICE KRISPIES", u: "../images/pptgames/Cereal/Rice Krispies.jpg" },
    { n: "SHREDDED WHEAT", u: "../images/pptgames/Cereal/Shredded Wheat.jpg" },
    { n: "SPECIAL K", u: "../images/pptgames/Cereal/Special K.jpg" },
    { n: "TOTAL", u: "../images/pptgames/Cereal/Total.jpg" },
    { n: "TRIX", u: "../images/pptgames/Cereal/Trix.jpg" },
    { n: "WHEATIES", u: "../images/pptgames/Cereal/Wheaties.jpg" }
];
if (typeof window !== "undefined") window.pptCereal = pptCereal;
