// Memes (PPT) — images in images/pptgames/Memes/
const pptMemes = [
    { n: "ARTHUR FIST", u: "../images/pptgames/Memes/Arthur Fist.jpg" },
    { n: "BAD LUCK BRIAN", u: "../images/pptgames/Memes/Bad Luck Brian.jpg" },
    { n: "BERNIE SANDERS MITTENS", u: "../images/pptgames/Memes/Bernie Sanders Mittens.jpg" },
    { n: "CEILING CAT", u: "../images/pptgames/Memes/Ceiling Cat.jpg" },
    { n: "CHANGE MY MIND", u: "../images/pptgames/Memes/Change My Mind.jpg" },
    { n: "CHLOE, SIDE-EYEING CHLOE", u: "../images/pptgames/Memes/Chloe, Side-Eyeing Chloe.jpg" },
    { n: "CHOCOLATE RAIN", u: "../images/pptgames/Memes/Chocolate Rain.jpg" },
    { n: "CRYING JORDAN", u: "../images/pptgames/Memes/Crying Jordan.jpg" },
    { n: "DISASTER GIRL", u: "../images/pptgames/Memes/Disaster Girl.jpg" },
    { n: "DISTRACTED BOYFRIEND", u: "../images/pptgames/Memes/Distracted Boyfriend.jpg" },
    { n: "DOGE", u: "../images/pptgames/Memes/Doge.jpg" },
    { n: "DRAKE", u: "../images/pptgames/Memes/Drake.jpg" },
    { n: "DRAMATIC CHIPMUNK", u: "../images/pptgames/Memes/Dramatic Chipmunk.jpg" },
    { n: "EMOTIONAL DAMAGE", u: "../images/pptgames/Memes/Emotional Damage.jpg" },
    { n: "EPIC HANDSHAKE", u: "../images/pptgames/Memes/Epic Handshake.jpg" },
    { n: "GALAXY BRAIN, EXPANDING BRAIN", u: "../images/pptgames/Memes/Galaxy Brain, Expanding Brain.jpg" },
    { n: "GIGACHAD", u: "../images/pptgames/Memes/GigaChad.jpg" },
    { n: "GRUMPY CAT", u: "../images/pptgames/Memes/Grumpy Cat.jpg" },
    { n: "IS THIS A PIGEON", u: "../images/pptgames/Memes/Is This A Pigeon.jpg" },
    { n: "IT'S OVER 9000!", u: "../images/pptgames/Memes/It\'s Over 9000!.jpg" },
    { n: "KERMIT, KERMIT SIPPING TEA", u: "../images/pptgames/Memes/Kermit, Kermit Sipping Tea.jpg" },
    { n: "KHABY LAME", u: "../images/pptgames/Memes/Khaby Lame.jpg" },
    { n: "MOST INTERESTING MAN IN THE WORLD", u: "../images/pptgames/Memes/Most Interesting Man in the World.jpg" },
    { n: "NUMA NUMA", u: "../images/pptgames/Memes/Numa Numa.jpg" },
    { n: "NYAN CAT", u: "../images/pptgames/Memes/Nyan Cat.jpg" },
    { n: "O RLY OWL", u: "../images/pptgames/Memes/O RLY Owl.jpg" },
    { n: "ONE DOES NOT SIMPLY...", u: "../images/pptgames/Memes/One Does Not Simply....jpg" },
    { n: "OVERLY ATTACHED GIRLFRIEND", u: "../images/pptgames/Memes/Overly Attached Girlfriend.jpg" },
    { n: "PEPE THE FROG", u: "../images/pptgames/Memes/Pepe the Frog.jpg" },
    { n: "RICKROLL", u: "../images/pptgames/Memes/Rickroll.jpg" },
    { n: "SALT BAE", u: "../images/pptgames/Memes/Salt Bae.jpg" },
    { n: "SANIC", u: "../images/pptgames/Memes/Sanic.jpg" },
    { n: "SPONGEBOB MOCKING", u: "../images/pptgames/Memes/SpongeBob Mocking.jpg" },
    { n: "STONKS", u: "../images/pptgames/Memes/Stonks.jpg" },
    { n: "SUCCESS KID", u: "../images/pptgames/Memes/Success Kid.jpg" },
    { n: "SURPRISED PIKACHU", u: "../images/pptgames/Memes/Surprised Pikachu.jpg" },
    { n: "THIS IS FINE", u: "../images/pptgames/Memes/This Is Fine.jpg" },
    { n: "TROLLFACE", u: "../images/pptgames/Memes/Trollface.jpg" },
    { n: "TWO BUTTONS", u: "../images/pptgames/Memes/Two Buttons.jpg" },
    { n: "WOMAN YELLING AT CAT", u: "../images/pptgames/Memes/Woman Yelling at Cat.jpg" }
];
if (typeof window !== "undefined") window.pptMemes = pptMemes;
