// Pets — images in images/pptgames/Pets/
const pptPets = [
    { n: "ALPACA", u: "../images/pptgames/Pets/Alpaca.jpg" },
    { n: "ANTS, ANT FARM", u: "../images/pptgames/Pets/Ants, Ant Farm.jpg" },
    { n: "AXOLOTL (SALAMANDER)", u: "../images/pptgames/Pets/Axolotl (Salamander).jpg" },
    { n: "BETTA FISH", u: "../images/pptgames/Pets/Betta Fish.jpg" },
    { n: "BUDGIE, PARAKEET", u: "../images/pptgames/Pets/Budgie, Parakeet.jpg" },
    { n: "CANARY", u: "../images/pptgames/Pets/Canary.jpg" },
    { n: "CAT", u: "../images/pptgames/Pets/Cat.jpg" },
    { n: "CHAMELEON", u: "../images/pptgames/Pets/Chameleon.jpg" },
    { n: "CHICKEN (SILKIE)", u: "../images/pptgames/Pets/Chicken (Silkie).jpg" },
    { n: "CHINCHILLA", u: "../images/pptgames/Pets/Chinchilla.jpg" },
    { n: "DOG (LABRADOR RETRIEVER)", u: "../images/pptgames/Pets/Dog (Labrador Retriever).jpg" },
    { n: "DUCK", u: "../images/pptgames/Pets/Duck.jpg" },
    { n: "FERRET", u: "../images/pptgames/Pets/Ferret.jpg" },
    { n: "FROG", u: "../images/pptgames/Pets/Frog.jpg" },
    { n: "GECKO, LEOPARD GECKO", u: "../images/pptgames/Pets/Gecko, Leopard Gecko.jpg" },
    { n: "GERBIL", u: "../images/pptgames/Pets/Gerbil.jpg" },
    { n: "GOAT, PYGMY GOAT", u: "../images/pptgames/Pets/Goat, Pygmy Goat.jpg" },
    { n: "GOLDFISH", u: "../images/pptgames/Pets/Goldfish.jpg" },
    { n: "GUINEA PIG", u: "../images/pptgames/Pets/Guinea Pig.jpg" },
    { n: "HAMSTER", u: "../images/pptgames/Pets/Hamster.jpg" },
    { n: "HEDGEHOG", u: "../images/pptgames/Pets/Hedgehog.jpg" },
    { n: "HORSE (MINIATURE HORSE)", u: "../images/pptgames/Pets/Horse (Miniature Horse).jpg" },
    { n: "IGUANA", u: "../images/pptgames/Pets/Iguana.jpg" },
    { n: "KOI", u: "../images/pptgames/Pets/Koi.jpg" },
    { n: "LIZARD, BEARDED DRAGON", u: "../images/pptgames/Pets/Lizard, Bearded Dragon.jpg" },
    { n: "LLAMA", u: "../images/pptgames/Pets/Llama.jpg" },
    { n: "MONKEY", u: "../images/pptgames/Pets/Monkey.jpg" },
    { n: "MOUSE", u: "../images/pptgames/Pets/Mouse.jpg" },
    { n: "PARROT", u: "../images/pptgames/Pets/Parrot.jpg" },
    { n: "PIG, MINI PIG", u: "../images/pptgames/Pets/Pig, Mini Pig.jpg" },
    { n: "RABBIT", u: "../images/pptgames/Pets/Rabbit.jpg" },
    { n: "RAT", u: "../images/pptgames/Pets/Rat.jpg" },
    { n: "SALAMANDER (NEWT)", u: "../images/pptgames/Pets/Salamander (Newt).jpg" },
    { n: "SHEEP, LAMB", u: "../images/pptgames/Pets/Sheep, Lamb.jpg" },
    { n: "SKUNK", u: "../images/pptgames/Pets/Skunk.jpg" },
    { n: "SNAKE (BALL PYTHON)", u: "../images/pptgames/Pets/Snake (Ball Python).jpg" },
    { n: "SQUIRREL", u: "../images/pptgames/Pets/Squirrel.jpg" },
    { n: "SUGAR GLIDER", u: "../images/pptgames/Pets/Sugar Glider.jpg" },
    { n: "TARANTULA", u: "../images/pptgames/Pets/Tarantula.jpg" },
    { n: "TURTLE", u: "../images/pptgames/Pets/Turtle.jpg" }
];
if (typeof window !== "undefined") window.pptPets = pptPets;
