// Easter — images in images/pptgames/Easter/
const pptEaster = [
    { n: "BABY CHICKS", u: "../images/pptgames/Easter/Baby Chicks.jpg" },
    { n: "BASKETS", u: "../images/pptgames/Easter/Baskets.jpg" },
    { n: "BONNET, HAT", u: "../images/pptgames/Easter/Bonnet, Hat.jpg" },
    { n: "BOW TIE", u: "../images/pptgames/Easter/Bow Tie.jpg" },
    { n: "BUTTERFLIES", u: "../images/pptgames/Easter/Butterflies.jpg" },
    { n: "CADBURY CREME EGG", u: "../images/pptgames/Easter/Cadbury Creme Egg.jpg" },
    { n: "CARROT", u: "../images/pptgames/Easter/Carrot.jpg" },
    { n: "CHOCOLATE RABBIT", u: "../images/pptgames/Easter/Chocolate Rabbit.jpg" },
    { n: "CHURCH", u: "../images/pptgames/Easter/Church.jpg" },
    { n: "CROSS", u: "../images/pptgames/Easter/Cross.jpg" },
    { n: "CROWN OF THORNS", u: "../images/pptgames/Easter/Crown of Thorns.jpg" },
    { n: "DAFFODILS", u: "../images/pptgames/Easter/Daffodils.jpg" },
    { n: "DEVILED EGGS", u: "../images/pptgames/Easter/Deviled Eggs.jpg" },
    { n: "DOVE", u: "../images/pptgames/Easter/Dove.jpg" },
    { n: "EASTER BUNNY", u: "../images/pptgames/Easter/Easter Bunny.jpg" },
    { n: "EASTER EGGS", u: "../images/pptgames/Easter/Easter Eggs.jpg" },
    { n: "EASTER GRASS", u: "../images/pptgames/Easter/Easter Grass.jpg" },
    { n: "EASTER PARADE", u: "../images/pptgames/Easter/Easter Parade.jpg" },
    { n: "EGG DECORATING", u: "../images/pptgames/Easter/Egg Decorating.jpg" },
    { n: "EGG HUNT", u: "../images/pptgames/Easter/Egg Hunt.jpg" },
    { n: "EMPTY TOMB", u: "../images/pptgames/Easter/Empty Tomb.jpg" },
    { n: "GARDEN OF GETHSEMANE", u: "../images/pptgames/Easter/Garden of Gethsemane.jpg" },
    { n: "HOLY GRAIL", u: "../images/pptgames/Easter/Holy Grail.jpg" },
    { n: "HOT CROSS BUNS", u: "../images/pptgames/Easter/Hot Cross Buns.jpg" },
    { n: "JELLY BEANS", u: "../images/pptgames/Easter/Jelly Beans.jpg" },
    { n: "JUDAS ISCARIOT", u: "../images/pptgames/Easter/Judas Iscariot.jpg" },
    { n: "LAMB", u: "../images/pptgames/Easter/Lamb.jpg" },
    { n: "LAST SUPPER", u: "../images/pptgames/Easter/Last Supper.jpg" },
    { n: "LILIES", u: "../images/pptgames/Easter/Lilies.jpg" },
    { n: "MARSHMALLOW PEEPS", u: "../images/pptgames/Easter/Marshmallow Peeps.jpg" },
    { n: "PAAS KIT", u: "../images/pptgames/Easter/Paas Kit.jpg" },
    { n: "PALM BRANCH", u: "../images/pptgames/Easter/Palm Branch.jpg" },
    { n: "PASCHAL CANDLE", u: "../images/pptgames/Easter/Paschal Candle.jpg" },
    { n: "PLASTIC EGG", u: "../images/pptgames/Easter/Plastic Egg.jpg" },
    { n: "PONTIUS PILATE", u: "../images/pptgames/Easter/Pontius Pilate.jpg" },
    { n: "RESURRECTION", u: "../images/pptgames/Easter/Resurrection.jpg" },
    { n: "ROBIN EGGS", u: "../images/pptgames/Easter/Robin Eggs.jpg" },
    { n: "SIMNEL CAKE", u: "../images/pptgames/Easter/Simnel Cake.jpg" },
    { n: "TULIPS", u: "../images/pptgames/Easter/Tulips.jpg" },
    { n: "WHITE ROBE", u: "../images/pptgames/Easter/White Robe.jpg" }
];
if (typeof window !== "undefined") window.pptEaster = pptEaster;
