// Toys — images in images/pptgames/Toys/
const pptToys = [
    { n: "AMERICAN GIRL DOLLS", u: "../images/pptgames/Toys/American Girl Dolls.jpg" },
    { n: "BAKUGAN", u: "../images/pptgames/Toys/Bakugan.jpg" },
    { n: "BARBIE", u: "../images/pptgames/Toys/Barbie.jpg" },
    { n: "BEANIE BABIES", u: "../images/pptgames/Toys/Beanie Babies.jpg" },
    { n: "BEYBLADE", u: "../images/pptgames/Toys/Beyblade.jpg" },
    { n: "BRATZ", u: "../images/pptgames/Toys/Bratz.jpg" },
    { n: "BUILD A BEAR", u: "../images/pptgames/Toys/Build A Bear.jpg" },
    { n: "CARE BEARS", u: "../images/pptgames/Toys/Care Bears.jpg" },
    { n: "DUPLO", u: "../images/pptgames/Toys/Duplo.jpg" },
    { n: "EASY-BAKE OVEN", u: "../images/pptgames/Toys/Easy-Bake Oven.jpg" },
    { n: "FIDGET SPINNERS", u: "../images/pptgames/Toys/Fidget Spinners.jpg" },
    { n: "FISHER-PRICE LITTLE PEOPLE", u: "../images/pptgames/Toys/Fisher-Price Little People.jpg" },
    { n: "FUNKO POP", u: "../images/pptgames/Toys/Funko POP.jpg" },
    { n: "FURBY", u: "../images/pptgames/Toys/Furby.jpg" },
    { n: "G.I.JOE", u: "../images/pptgames/Toys/G.I.Joe.jpg" },
    { n: "HATCHIMALS", u: "../images/pptgames/Toys/Hatchimals.jpg" },
    { n: "HOT WHEELS", u: "../images/pptgames/Toys/Hot Wheels.jpg" },
    { n: "K'NEX", u: "../images/pptgames/Toys/K\'NEX.jpg" },
    { n: "LEGO", u: "../images/pptgames/Toys/LEGO.jpg" },
    { n: "LOL SURPRISE DOLLS", u: "../images/pptgames/Toys/LOL Surprise Dolls.jpg" },
    { n: "MAGNA TILES", u: "../images/pptgames/Toys/Magna Tiles.jpg" },
    { n: "MATCHBOX CARS", u: "../images/pptgames/Toys/Matchbox Cars.jpg" },
    { n: "MR. POTATO HEAD", u: "../images/pptgames/Toys/Mr. Potato Head.jpg" },
    { n: "NERF", u: "../images/pptgames/Toys/Nerf.jpg" },
    { n: "PLAY-DOH", u: "../images/pptgames/Toys/Play-Doh.jpg" },
    { n: "PLAYMOBIL", u: "../images/pptgames/Toys/Playmobil.jpg" },
    { n: "POKEMON CARDS", u: "../images/pptgames/Toys/Pokemon Cards.jpg" },
    { n: "POLLY POCKET", u: "../images/pptgames/Toys/Polly Pocket.jpg" },
    { n: "POP IT", u: "../images/pptgames/Toys/Pop It.jpg" },
    { n: "PUZZLES", u: "../images/pptgames/Toys/Puzzles.jpg" },
    { n: "RC REMOTE CONTROL CARS", u: "../images/pptgames/Toys/RC Remote Control Cars.jpg" },
    { n: "RUBIK'S CUBE", u: "../images/pptgames/Toys/Rubik\'s Cube.jpg" },
    { n: "SHOPKINS", u: "../images/pptgames/Toys/Shopkins.jpg" },
    { n: "SLINKY", u: "../images/pptgames/Toys/Slinky.jpg" },
    { n: "SQUISHMALLOWS", u: "../images/pptgames/Toys/Squishmallows.jpg" },
    { n: "STAR WARS ACTION FIGURES", u: "../images/pptgames/Toys/Star Wars Action Figures.jpg" },
    { n: "TAMAGOTCHI", u: "../images/pptgames/Toys/Tamagotchi.jpg" },
    { n: "TICKLE ME ELMO", u: "../images/pptgames/Toys/Tickle Me Elmo.jpg" },
    { n: "TRANSFORMERS", u: "../images/pptgames/Toys/Transformers.jpg" },
    { n: "ZHU ZHU PETS", u: "../images/pptgames/Toys/Zhu Zhu Pets.jpg" }
];
if (typeof window !== "undefined") window.pptToys = pptToys;
