// Tools — images in images/pptgames/Tools/
const pptTools = [
    { n: "ALLEN, HEX WRENCH", u: "../images/pptGames/Tools/Allen, Hex Wrench.jpg" },
    { n: "AXE", u: "../images/pptGames/Tools/Axe.jpg" },
    { n: "BOLT", u: "../images/pptGames/Tools/Bolt.jpg" },
    { n: "CAULKING GUN", u: "../images/pptGames/Tools/Caulking Gun.jpg" },
    { n: "CHISEL", u: "../images/pptGames/Tools/Chisel.jpg" },
    { n: "CIRCULAR SAW", u: "../images/pptGames/Tools/Circular Saw.jpg" },
    { n: "CLAMP, C-CLAMP", u: "../images/pptGames/Tools/Clamp, C-Clamp.jpg" },
    { n: "CROWBAR", u: "../images/pptGames/Tools/Crowbar.jpg" },
    { n: "DREMEL, ROTARY TOOL", u: "../images/pptGames/Tools/Dremel, Rotary Tool.jpg" },
    { n: "DRILL", u: "../images/pptGames/Tools/Drill.jpg" },
    { n: "FILE", u: "../images/pptGames/Tools/File.jpg" },
    { n: "FLASHLIGHT", u: "../images/pptGames/Tools/Flashlight.jpg" },
    { n: "HACKSAW", u: "../images/pptGames/Tools/Hacksaw.jpg" },
    { n: "HAMMER", u: "../images/pptGames/Tools/Hammer.jpg" },
    { n: "HEAT GUN", u: "../images/pptGames/Tools/Heat Gun.jpg" },
    { n: "LADDER", u: "../images/pptGames/Tools/Ladder.jpg" },
    { n: "LEVEL", u: "../images/pptGames/Tools/Level.jpg" },
    { n: "MALLET", u: "../images/pptGames/Tools/Mallet.jpg" },
    { n: "MULTIMETER", u: "../images/pptGames/Tools/Multimeter.jpg" },
    { n: "NAILS", u: "../images/pptGames/Tools/Nails.jpg" },
    { n: "NUT", u: "../images/pptGames/Tools/Nut.jpg" },
    { n: "PAINT ROLLER", u: "../images/pptGames/Tools/Paint Roller.jpg" },
    { n: "PAINTBRUSH", u: "../images/pptGames/Tools/Paintbrush.jpg" },
    { n: "PICKAXE", u: "../images/pptGames/Tools/Pickaxe.jpg" },
    { n: "PLIERS", u: "../images/pptGames/Tools/Pliers.jpg" },
    { n: "SANDER", u: "../images/pptGames/Tools/Sander.jpg" },
    { n: "SAW", u: "../images/pptGames/Tools/Saw.jpg" },
    { n: "SCREWDRIVER", u: "../images/pptGames/Tools/Screwdriver.jpg" },
    { n: "SCREWS", u: "../images/pptGames/Tools/Screws.jpg" },
    { n: "SHOVEL", u: "../images/pptGames/Tools/Shovel.jpg" },
    { n: "SOCKET WRENCH, RATCHET", u: "../images/pptGames/Tools/Socket Wrench, Ratchet.jpg" },
    { n: "STAPLE GUN", u: "../images/pptGames/Tools/Staple Gun.jpg" },
    { n: "STUD FINDER", u: "../images/pptGames/Tools/Stud Finder.jpg" },
    { n: "TAPE MEASURE", u: "../images/pptGames/Tools/Tape Measure.jpg" },
    { n: "TROWEL", u: "../images/pptGames/Tools/Trowel.jpg" },
    { n: "UTILITY KNIFE", u: "../images/pptGames/Tools/Utility Knife.jpg" },
    { n: "VICE", u: "../images/pptGames/Tools/Vice.jpg" },
    { n: "WHEELBARROW", u: "../images/pptGames/Tools/Wheelbarrow.jpg" },
    { n: "WIRE STRIPPER", u: "../images/pptGames/Tools/Wire Stripper.jpg" },
    { n: "WRENCH", u: "../images/pptGames/Tools/Wrench.jpg" }
];
if (typeof window !== "undefined") window.pptTools = pptTools;
