// Birds (PPT) — images in images/pptgames/Birds/
const pptBirds = [
    { n: "ALBATROSS", u: "../images/pptGames/Birds/Albatross.jpg" },
    { n: "BLUE JAY", u: "../images/pptGames/Birds/Blue Jay.jpg" },
    { n: "CANARY", u: "../images/pptGames/Birds/Canary.jpg" },
    { n: "CARDINAL", u: "../images/pptGames/Birds/Cardinal.jpg" },
    { n: "CHICKEN", u: "../images/pptGames/Birds/Chicken.jpg" },
    { n: "COCKATOO", u: "../images/pptGames/Birds/Cockatoo.jpg" },
    { n: "CROW", u: "../images/pptGames/Birds/Crow.jpg" },
    { n: "DODO", u: "../images/pptGames/Birds/Dodo.jpg" },
    { n: "DOVE", u: "../images/pptGames/Birds/Dove.jpg" },
    { n: "DUCK", u: "../images/pptGames/Birds/Duck.jpg" },
    { n: "EAGLE", u: "../images/pptGames/Birds/Eagle.jpg" },
    { n: "EMU", u: "../images/pptGames/Birds/Emu.jpg" },
    { n: "FALCON", u: "../images/pptGames/Birds/Falcon.jpg" },
    { n: "FLAMINGO", u: "../images/pptGames/Birds/Flamingo.jpg" },
    { n: "GOLDFINCH", u: "../images/pptGames/Birds/Goldfinch.jpg" },
    { n: "GOOSE", u: "../images/pptGames/Birds/Goose.jpg" },
    { n: "HAWK", u: "../images/pptGames/Birds/Hawk.jpg" },
    { n: "HERON", u: "../images/pptGames/Birds/Heron.jpg" },
    { n: "HUMMINGBIRD", u: "../images/pptGames/Birds/Hummingbird.jpg" },
    { n: "MAGPIE", u: "../images/pptGames/Birds/Magpie.jpg" },
    { n: "OSTRICH", u: "../images/pptGames/Birds/Ostrich.jpg" },
    { n: "OWL", u: "../images/pptGames/Birds/Owl.jpg" },
    { n: "PARROT", u: "../images/pptGames/Birds/Parrot.jpg" },
    { n: "PEACOCK", u: "../images/pptGames/Birds/Peacock.jpg" },
    { n: "PELICAN", u: "../images/pptGames/Birds/Pelican.jpg" },
    { n: "PENGUIN", u: "../images/pptGames/Birds/Penguin.jpg" },
    { n: "PIGEON", u: "../images/pptGames/Birds/Pigeon.jpg" },
    { n: "PUFFIN", u: "../images/pptGames/Birds/Puffin.jpg" },
    { n: "QUAIL", u: "../images/pptGames/Birds/Quail.jpg" },
    { n: "RAVEN", u: "../images/pptGames/Birds/Raven.jpg" },
    { n: "ROBIN", u: "../images/pptGames/Birds/Robin.jpg" },
    { n: "SEAGULL", u: "../images/pptGames/Birds/Seagull.jpg" },
    { n: "SPARROW", u: "../images/pptGames/Birds/Sparrow.jpg" },
    { n: "STARLING", u: "../images/pptGames/Birds/Starling.jpg" },
    { n: "STORK", u: "../images/pptGames/Birds/Stork.jpg" },
    { n: "SWAN", u: "../images/pptGames/Birds/Swan.jpg" },
    { n: "TOUCAN", u: "../images/pptGames/Birds/Toucan.jpg" },
    { n: "TURKEY", u: "../images/pptGames/Birds/Turkey.jpg" },
    { n: "VULTURE", u: "../images/pptGames/Birds/Vulture.jpg" },
    { n: "WOODPECKER", u: "../images/pptGames/Birds/Woodpecker.jpg" }
];
if (typeof window !== "undefined") window.pptBirds = pptBirds;
